import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ApiClient, ApiError } from './api';
import type { Agent, AuthUser, GraphData, Json, Run, Skill, SystemStatus, Tool, Workflow } from './types';
import { VisualBuilder } from './VisualBuilder';
import { RunConsole } from './RunConsole';
import { AuthScreen } from './AuthScreen';

type Page='overview'|'agents'|'workflows'|'runs'|'skills'|'tools'|'system'|'settings';
const nav:Array<[Page,string,string]>=[['overview','总览','⌂'],['agents','Agent 编排','◇'],['workflows','工作流','⌘'],['runs','运行中心','▷'],['skills','技能治理','✦'],['tools','工具目录','⬡'],['system','系统管理','▦'],['settings','连接设置','⚙']];
const fmt=(v?:string|null)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—';
const short=(v?:string,n=12)=>v&&v.length>n?`${v.slice(0,n)}…`:v||'—';
const split=(v:string)=>v.split(',').map(x=>x.trim()).filter(Boolean);
const json=(v:string):Json=>{try{return JSON.parse(v||'{}')}catch{throw new Error('JSON 格式不正确')}};
const statusLabel:Record<string,string>={succeeded:'成功',failed:'失败',running:'运行中',queued:'排队中',created:'已创建',canceled:'已取消',cancel_requested:'取消中',published:'已发布',candidate:'候选',validated:'已验证',rejected:'已拒绝',retired:'已退役'};

function App(){
 const [page,setPage]=useState<Page>((location.hash.slice(1) as Page)||'overview');
 const [baseUrl,setBaseUrl]=useState(localStorage.getItem('apiUrl')||import.meta.env.VITE_API_BASE_URL||'/');
 const [adminKey,setAdminKey]=useState(localStorage.getItem('adminKey')||''); const [actor,setActor]=useState(localStorage.getItem('actor')||'operator');
 const [token,setToken]=useState(localStorage.getItem('authToken')||''); const [user,setUser]=useState<AuthUser|null>(null); const [authReady,setAuthReady]=useState(false); const authRequestSeq=useRef(0);
 const api=useMemo(()=>new ApiClient(baseUrl,{adminKey,actor,token}),[baseUrl,adminKey,actor,token]);
 const [online,setOnline]=useState(false); const [toast,setToast]=useState<{text:string;bad?:boolean}|null>(null);
 const notify=(text:string,bad=false)=>{setToast({text,bad});setTimeout(()=>setToast(null),3200)};
 useEffect(()=>{location.hash=page},[page]);
 // Restore a persisted session only when the application first opens. A login
 // response is already authoritative; checking /me again during that state
 // update can let a stale request incorrectly clear the new session.
 useEffect(()=>{const seq=++authRequestSeq.current;const savedToken=localStorage.getItem('authToken')||'';if(!savedToken){setAuthReady(true);return}const restoreApi=new ApiClient(localStorage.getItem('apiUrl')||'/',{adminKey:localStorage.getItem('adminKey')||'',actor:localStorage.getItem('actor')||'operator',token:savedToken});restoreApi.get<{user:AuthUser}>('/api/auth/me').then(v=>{if(seq!==authRequestSeq.current)return;setUser(v.user);setActor(v.user.email);localStorage.setItem('actor',v.user.email);setOnline(true)}).catch(()=>{if(seq!==authRequestSeq.current)return;if(localStorage.getItem('authToken')===savedToken){localStorage.removeItem('authToken');setToken('');setUser(null)}}).finally(()=>{if(seq===authRequestSeq.current)setAuthReady(true)});},[]);
 useEffect(()=>{if(user)api.get('/api/system/status').then(()=>setOnline(true)).catch(()=>setOnline(false))},[api,user]);
 const authenticated=(value:{token:string;user:AuthUser})=>{authRequestSeq.current++;localStorage.setItem('apiUrl','/');localStorage.setItem('authToken',value.token);localStorage.setItem('actor',value.user.email);setBaseUrl('/');setActor(value.user.email);setToken(value.token);setUser(value.user);setPage('overview');setAuthReady(true);setOnline(true)};
 const logout=async()=>{try{await api.post('/api/auth/logout')}finally{localStorage.removeItem('authToken');setToken('');setUser(null)}};
 const saveSettings=async(u:string,k:string,a:string)=>{const nextUrl=u.trim()||'/';localStorage.setItem('apiUrl',nextUrl);localStorage.setItem('adminKey',k);localStorage.setItem('actor',a);setBaseUrl(nextUrl);setAdminKey(k);setActor(a);try{await new ApiClient(nextUrl,{adminKey:k,actor:a,token}).get('/api/system/status');setOnline(true);notify('已连接到 FastAPI 后端')}catch(e){setOnline(false);notify(`连接失败：${(e as Error).message}`,true)}};
 if(!authReady)return <div className="auth-loading"><span className="spinner"/>正在验证登录状态…</div>;
 if(!user)return <AuthScreen api={api} onAuthenticated={authenticated}/>;
 return <div className="shell">
  <aside><div className="brand"><span className="brandmark">A</span><div><b>AgentForge</b><small>智能体运行平台</small></div></div><nav>{nav.map(([id,label,icon])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><i>{icon}</i>{label}</button>)}</nav><div className="side-foot"><div className={`health ${online?'ok':''}`}><span/> {online?'后端服务正常':'后端未连接'}</div><small>{short(baseUrl,28)}</small></div></aside>
  <main><header><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p>{subtitles[page]}</p></div><div className="header-actions"><button className="icon-btn" onClick={()=>location.reload()}>↻</button><div className="user-chip"><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><span><b>{user.name}</b><small>{user.email}</small></span></div><button className="logout-btn" onClick={logout}>退出</button></div></header>
   <section className="content">{page==='overview'&&<Overview api={api} go={setPage}/>} {page==='agents'&&<VisualBuilder api={api} notify={notify}/>} {page==='workflows'&&<Workflows api={api} notify={notify}/>} {page==='runs'&&<RunConsole api={api} notify={notify}/>} {page==='skills'&&<Skills api={api} notify={notify} actor={actor}/>} {page==='tools'&&<Tools api={api} notify={notify}/>} {page==='system'&&<System api={api} notify={notify}/>} {page==='settings'&&<Settings baseUrl={baseUrl} adminKey={adminKey} actor={actor} save={saveSettings}/>}</section>
  </main>{toast&&<div className={`toast ${toast.bad?'bad':''}`}>{toast.bad?'!':'✓'} {toast.text}</div>}
 </div>
}
const subtitles:Record<Page,string>={overview:'掌握智能体资产与运行态势',agents:'设计 Agent、层级关系与执行路径',workflows:'持久化、加载与管理编排版本',runs:'发起任务并追踪每个执行事件',skills:'从运行轨迹提炼、验证并发布技能',tools:'管理 Agent 可发现的工具元数据',system:'模型配置、安全审计与项目快照',settings:'配置后端地址和管理身份'};
type Ctx={api:ApiClient;notify:(s:string,b?:boolean)=>void};
function useLoad<T>(fn:()=>Promise<T>,deps:unknown[]=[]){const [data,setData]=useState<T|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=useCallback(()=>{setLoading(true);setError('');fn().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},deps);useEffect(load,[load]);return{data,setData,loading,error,reload:load}}
function Empty({loading,error,text='暂无数据'}:{loading?:boolean;error?:string;text?:string}){return <div className="empty">{loading?<><span className="spinner"/>正在读取后端数据…</>:error?<><b>连接失败</b><span>{error}</span></>:<><b>{text}</b><span>可使用右上角操作创建第一条记录</span></>}</div>}
function Status({value}:{value:string}){return <span className={`status s-${value}`}>{statusLabel[value]||value}</span>}
function Modal({title,onClose,children,wide=false}:{title:string;onClose:()=>void;children:React.ReactNode;wide?:boolean}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={`modal ${wide?'wide':''}`}><div className="modal-head"><h2>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}
function Field({label,children,span=false}:{label:string;children:React.ReactNode;span?:boolean}){return <label className={span?'span':''}><span>{label}</span>{children}</label>}
function Metric({label,value,hint,icon}:{label:string;value:React.ReactNode;hint:string;icon:string}){return <article className="metric"><div className="metric-icon">{icon}</div><div><small>{label}</small><strong>{value}</strong><p>{hint}</p></div></article>}

function Overview({api,go}:{api:ApiClient;go:(p:Page)=>void}){const q=useLoad(async()=>{const [m,r,w,s,status]=await Promise.all([api.get<any>('/api/system/metrics'),api.get<Run[]>('/api/runs'),api.get<Workflow[]>('/api/workflows'),api.get<Skill[]>('/api/skills'),api.get<SystemStatus>('/api/system/status')]);return{m,r,w,s,status}},[api]);if(!q.data)return <Empty loading={q.loading} error={q.error}/>;const d=q.data, counts=d.m.runs?.status_counts||{};return <>
 <div className="metrics"><Metric icon="⌘" label="工作流" value={d.m.workflows.total} hint="已持久化编排"/><Metric icon="▷" label="总运行" value={d.m.runs.total} hint={`${counts.running||0} 个正在运行`}/><Metric icon="✦" label="技能资产" value={d.m.skills.total} hint={`${d.s.filter(x=>x.status==='published').length} 个已发布`}/><Metric icon="⬡" label="工具" value={d.m.tools.total} hint="已登记目录项"/></div>
 <div className="grid two"><article className="panel"><div className="panel-head"><div><h2>近期运行</h2><p>最近执行状态与工作流</p></div><button className="link" onClick={()=>go('runs')}>查看全部 →</button></div><div className="run-list">{d.r.slice(0,6).map(x=><div key={x.id} className="run-row"><span className={`run-dot s-${x.status}`}/><div><b>{short(x.id,20)}</b><small>{d.w.find(y=>y.id===x.workflow_id)?.name||'当前编排'}</small></div><Status value={x.status}/><time>{fmt(x.updated_at)}</time></div>)}{!d.r.length&&<Empty/>}</div></article>
 <article className="panel"><div className="panel-head"><div><h2>模型资源</h2><p>端、边、云运行环境</p></div></div><div className="model-stack">{Object.entries(d.status.models).map(([k,v])=><div className="model-card" key={k}><span className={`model-badge ${k}`}>{k==='device'?'端':k==='edge'?'边':'云'}</span><div><b>{v.model||'未指定模型'}</b><small>{v.base_url||'未配置服务地址'}</small></div><Status value={v.configured?'succeeded':'failed'}/></div>)}</div></article></div>
 <article className="panel quick"><div><h2>快速开始</h2><p>从编排到运行，让智能体工作流真正执行起来。</p></div><button onClick={()=>go('agents')} className="primary">新建 Agent</button><button onClick={()=>go('workflows')}>管理工作流</button><button onClick={()=>go('runs')}>发起运行</button></article>
 </>}

function Agents({api,notify}:Ctx){const q=useLoad(()=>Promise.all([api.get<Agent[]>('/api/agents'),api.get<GraphData>('/api/export')]),[api]);const [create,setCreate]=useState(false),[connect,setConnect]=useState(false),[selected,setSelected]=useState<Agent|null>(null);const data=q.data,agents=data?.[0]||[],graph=data?.[1];const act=async(fn:()=>Promise<unknown>,msg:string)=>{try{await fn();notify(msg);setCreate(false);setConnect(false);q.reload()}catch(e){notify((e as Error).message,true)}};return <><div className="toolbar"><div className="search">⌕ <input placeholder="搜索 Agent" onChange={e=>{const v=e.target.value.toLowerCase();document.querySelectorAll<HTMLElement>('[data-agent]').forEach(x=>x.style.display=x.dataset.agent?.includes(v)?'':'none')}}/></div><button onClick={()=>setConnect(true)}>连接节点</button><button className="primary" onClick={()=>setCreate(true)}>＋ 新建 Agent</button></div>
 {!data?<Empty loading={q.loading} error={q.error}/>:<div className="builder"><div className="canvas"><div className="canvas-grid"/><div className="canvas-title"><b>当前编排</b><span>{agents.length} 节点 · {graph?.connections?.length||0} 连线</span></div>{agents.map((a,i)=>{const col=i%3,row=Math.floor(i/3);return <div data-agent={a.name.toLowerCase()} onClick={()=>setSelected(a)} className={`agent-node ${graph?.entry_id===a.id||graph?.entry===a.id?'entry':''}`} style={{left:70+col*265,top:100+row*180}} key={a.id}><div><span className="node-icon">AI</span><div><b>{a.name}</b><small>{a.model||'自动调度模型'}</small></div></div><p>{a.description||'尚未填写 Agent 职责说明'}</p><footer><span>{a.children?.length||0} 子 Agent</span><span>打开详情 →</span></footer></div>})}{!agents.length&&<div className="canvas-empty">创建第一个 Agent 开始编排</div>}</div><aside className="inspector">{selected?<><div className="inspector-head"><span className="node-icon">AI</span><div><h3>{selected.name}</h3><small>{selected.id}</small></div></div><Section title="角色说明"><p>{selected.description||'未填写'}</p></Section><Section title="系统提示词"><pre>{selected.sys_prompt||'未配置'}</pre></Section><Section title="运行配置"><KV label="模型" value={selected.model||'自动'}/><KV label="子 Agent" value={String(selected.children?.length||0)}/></Section><div className="inspector-actions"><button onClick={()=>act(()=>api.post('/api/graph/entry',{agent_id:selected.id}),'已设置编排入口')}>设为入口</button><button className="danger" onClick={()=>confirm('确认删除该 Agent？')&&act(()=>api.delete(`/api/agents/${selected.id}`),'Agent 已删除')}>删除</button></div></>:<div className="select-tip">选择画布中的节点查看配置</div>}</aside></div>}
 {create&&<AgentForm close={()=>setCreate(false)} submit={v=>act(()=>api.post('/api/agents',v),'Agent 已创建')}/>} {connect&&<ConnectForm agents={agents} close={()=>setConnect(false)} submit={v=>act(()=>api.post('/api/connections',v),'连接已创建')}/>}</>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <div className="section"><h4>{title}</h4>{children}</div>} function KV({label,value}:{label:string;value:string}){return <div className="kv"><span>{label}</span><b>{value}</b></div>}
function AgentForm({close,submit}:{close:()=>void;submit:(v:unknown)=>void}){const [f,setF]=useState({name:'',model:'',description:'',sys_prompt:'',config:'{}'});return <Modal title="新建 Agent" onClose={close}><form onSubmit={e=>{e.preventDefault();submit({...f,config:json(f.config)})}} className="form-grid"><Field label="名称"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="模型"><input placeholder="留空则自动调度" value={f.model} onChange={e=>setF({...f,model:e.target.value})}/></Field><Field label="职责描述" span><input value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><Field label="系统提示词" span><textarea rows={7} value={f.sys_prompt} onChange={e=>setF({...f,sys_prompt:e.target.value})}/></Field><Field label="高级配置 JSON" span><textarea className="code" rows={3} value={f.config} onChange={e=>setF({...f,config:e.target.value})}/></Field><FormActions close={close}/></form></Modal>}
function ConnectForm({agents,close,submit}:{agents:Agent[];close:()=>void;submit:(v:unknown)=>void}){const [f,setF]=useState({source_id:'',target_id:'END'});return <Modal title="连接节点" onClose={close}><form onSubmit={e=>{e.preventDefault();submit({...f,conditional:false})}} className="form-grid"><Field label="起点"><select required value={f.source_id} onChange={e=>setF({...f,source_id:e.target.value})}><option value="">请选择</option>{agents.map(a=><option value={a.id}>{a.name}</option>)}</select></Field><Field label="终点"><select value={f.target_id} onChange={e=>setF({...f,target_id:e.target.value})}><option value="END">结束 END</option>{agents.map(a=><option value={a.id}>{a.name}</option>)}</select></Field><FormActions close={close}/></form></Modal>}
function FormActions({close,label='确认创建'}:{close:()=>void;label?:string}){return <div className="form-actions span"><button type="button" onClick={close}>取消</button><button className="primary" type="submit">{label}</button></div>}

function Workflows({api,notify}:Ctx){const q=useLoad(()=>api.get<Workflow[]>('/api/workflows'),[api]);const [modal,setModal]=useState(false),[detail,setDetail]=useState<Workflow|null>(null),[versions,setVersions]=useState<Workflow[]>([]);const act=async(fn:()=>Promise<any>,msg:string)=>{try{await fn();notify(msg);setModal(false);q.reload()}catch(e){notify((e as Error).message,true)}};const open=async(w:Workflow)=>{setDetail(w);try{setVersions(await api.get(`/api/workflows/${w.id}/versions`))}catch(e){notify((e as Error).message,true)}};return <><div className="toolbar"><div className="filter-tabs"><button className="active">全部 {q.data?.length||0}</button></div><button className="primary" onClick={()=>setModal(true)}>＋ 保存当前编排</button></div>{!q.data?<Empty loading={q.loading} error={q.error}/>:<div className="cards">{q.data.map(w=><article className="asset-card" key={w.id} onClick={()=>open(w)}><div className="asset-top"><span className="asset-icon">⌘</span><Status value="published"/></div><h3>{w.name}</h3><p>{w.description||'暂无描述'}</p><div className="tags">{w.tags.map(t=><span>{t}</span>)}</div><footer><span>v{w.version} · {w.graph?.agents?.length||0} 节点</span><time>{fmt(w.updated_at)}</time></footer></article>)}{!q.data.length&&<Empty/>}</div>}
 {modal&&<WorkflowForm close={()=>setModal(false)} submit={v=>act(()=>api.post('/api/workflows',v),'工作流已保存')}/>} {detail&&<Modal wide title={detail.name} onClose={()=>setDetail(null)}><div className="detail-grid"><div><Section title="工作流信息"><p>{detail.description||'暂无描述'}</p><KV label="ID" value={detail.id}/><KV label="当前版本" value={`v${detail.version}`}/><KV label="节点数量" value={String(detail.graph?.agents?.length||0)}/></Section><div className="button-row"><button className="primary" onClick={()=>act(()=>api.post(`/api/workflows/${detail.id}/load`),'已加载到编排器')}>加载工作流</button><button onClick={()=>act(()=>api.post('/api/runs',{workflow_id:detail.id,input:{input:'请开始执行任务'},recursion_limit:50}),'运行已启动')}>快速运行</button><button className="danger" onClick={()=>confirm('确认删除？')&&act(()=>api.delete(`/api/workflows/${detail.id}`),'工作流已删除')}>删除</button></div></div><div><h4>版本历史</h4><div className="timeline">{versions.map(v=><div><span>v{v.version}</span><div><b>{v.version===detail.version?'当前版本':'历史快照'}</b><small>{fmt(v.updated_at)}</small></div>{v.version!==detail.version&&<button onClick={()=>act(()=>api.post(`/api/workflows/${detail.id}/rollback/${v.version}`),'已回滚并生成新版本')}>回滚</button>}</div>)}</div></div></div></Modal>}</>}
function WorkflowForm({close,submit}:{close:()=>void;submit:(v:unknown)=>void}){const [f,setF]=useState({name:'',description:'',tags:''});return <Modal title="保存当前编排" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();submit({...f,tags:split(f.tags)})}}><Field label="名称"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="标签"><input placeholder="逗号分隔" value={f.tags} onChange={e=>setF({...f,tags:e.target.value})}/></Field><Field label="描述" span><textarea rows={5} value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><FormActions close={close} label="保存工作流"/></form></Modal>}

function Runs({api,notify}:Ctx){const q=useLoad(()=>Promise.all([api.get<Run[]>('/api/runs'),api.get<Workflow[]>('/api/workflows')]),[api]);const [create,setCreate]=useState(false),[detail,setDetail]=useState<Run|null>(null),[traces,setTraces]=useState<Json[]>([]);const data=q.data,runs=data?.[0]||[],wfs=data?.[1]||[];useEffect(()=>{const active=runs.some(x=>['running','queued','cancel_requested'].includes(x.status));if(active){const t=setInterval(q.reload,2500);return()=>clearInterval(t)}},[runs,q.reload]);const act=async(fn:()=>Promise<any>,msg:string)=>{try{const r=await fn();notify(msg);setCreate(false);q.reload();return r}catch(e){notify((e as Error).message,true)}};const open=async(r:Run)=>{setDetail(await api.get(`/api/runs/${r.id}`));const x=await api.get<{events:Json[]}>(`/api/runs/${r.id}/skill-traces`);setTraces(x.events)};return <><div className="toolbar"><div className="filter-tabs"><button className="active">全部</button><button>运行中 {runs.filter(x=>x.status==='running').length}</button><button>失败 {runs.filter(x=>x.status==='failed').length}</button></div><button className="primary" onClick={()=>setCreate(true)}>▷ 发起运行</button></div>{!data?<Empty loading={q.loading} error={q.error}/>:<article className="panel table-wrap"><table><thead><tr><th>运行 ID</th><th>工作流</th><th>状态</th><th>事件</th><th>重试</th><th>更新时间</th><th/></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td><button className="id-link" onClick={()=>open(r)}>{r.id}</button></td><td>{wfs.find(w=>w.id===r.workflow_id)?.name||'当前编排'}</td><td><Status value={r.status}/></td><td>{r.events?.length||0}</td><td>{r.retry_count}</td><td>{fmt(r.updated_at)}</td><td><button className="more" onClick={()=>open(r)}>•••</button></td></tr>)}</tbody></table>{!runs.length&&<Empty/>}</article>}
 {create&&<RunForm workflows={wfs} close={()=>setCreate(false)} submit={v=>act(()=>api.post('/api/runs',v),'运行已进入队列')}/>} {detail&&<Modal wide title={`运行详情 · ${detail.id}`} onClose={()=>setDetail(null)}><div className="run-detail-head"><Status value={detail.status}/><span>工作流：{wfs.find(w=>w.id===detail.workflow_id)?.name||'当前编排'}</span><span>创建：{fmt(detail.created_at)}</span></div>{detail.error&&<div className="error-box">{detail.error}</div>}<div className="detail-grid"><div><h4>事件时间线</h4><div className="event-list">{detail.events.map((e,i)=><div key={i}><span>{i+1}</span><div><b>{String(e.type||'event')}</b><small>{String(e.node||e.name||'图执行')}</small></div><code>{String(e.timestamp||'')}</code></div>)}{!detail.events.length&&<Empty text="尚无执行事件"/>}</div></div><div><h4>输入与结果</h4><pre className="json-view">{JSON.stringify({input:detail.input,state:detail.state},null,2)}</pre><h4>技能轨迹（{traces.length}）</h4><div className="trace-list">{traces.map((x,i)=><code key={i}>{String(x.event_type||x.type||'skill event')}</code>)}</div></div></div><div className="button-row"><button onClick={()=>act(()=>api.post(`/api/runs/${detail.id}/retry`),'重试运行已创建')}>重试运行</button>{!['succeeded','failed','canceled'].includes(detail.status)&&<button className="danger" onClick={()=>act(()=>api.post(`/api/runs/${detail.id}/cancel`,{reason:'由控制台取消'}),'已请求取消')}>取消运行</button>}<button onClick={()=>act(()=>api.post('/api/skills/candidates/from-run',{run_id:detail.id}),'已从运行生成候选技能')}>生成候选技能</button></div></Modal>}</>}
function RunForm({workflows,close,submit}:{workflows:Workflow[];close:()=>void;submit:(v:unknown)=>void}){const [wf,setWf]=useState(''),[input,setInput]=useState('{\n  "input": "请分析任务并输出结果"\n}'),[limit,setLimit]=useState(50);return <Modal title="发起后台运行" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();submit({workflow_id:wf||null,input:json(input),recursion_limit:limit})}}><Field label="工作流" span><select value={wf} onChange={e=>setWf(e.target.value)}><option value="">当前内存编排</option>{workflows.map(w=><option value={w.id}>{w.name} · v{w.version}</option>)}</select></Field><Field label="运行输入 JSON" span><textarea className="code" rows={8} value={input} onChange={e=>setInput(e.target.value)}/></Field><Field label="递归上限"><input type="number" min="1" value={limit} onChange={e=>setLimit(+e.target.value)}/></Field><FormActions close={close} label="启动运行"/></form></Modal>}

function Skills({api,notify,actor}:Ctx&{actor:string}){const q=useLoad(()=>api.get<Skill[]>('/api/skills'),[api]);const [create,setCreate]=useState(false),[detail,setDetail]=useState<Skill|null>(null),[versions,setVersions]=useState<Skill[]>([]),[search,setSearch]=useState(''),[matches,setMatches]=useState<any[]>([]);const act=async(fn:()=>Promise<any>,msg:string)=>{try{const v=await fn();notify(msg);setCreate(false);q.reload();if(detail&&v?.id===detail.id)setDetail(v)}catch(e){notify((e as Error).message,true)}};const open=async(s:Skill)=>{setDetail(await api.get(`/api/skills/${s.id}`));setVersions(await api.get(`/api/skills/${s.id}/versions`))};const doSearch=async()=>{try{setMatches((await api.post<{matches:any[]}>('/api/skills/search',{query:search,top_k:5})).matches)}catch(e){notify((e as Error).message,true)}};return <><div className="toolbar"><div className="search">⌕ <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="检索已发布技能"/><button onClick={doSearch}>检索</button></div><button className="primary" onClick={()=>setCreate(true)}>＋ 新建技能</button></div>{matches.length>0&&<div className="search-results"><b>检索结果</b>{matches.map((m,i)=><span key={i}>{m.skill?.name||m.name||m.skill_id} <em>{Number(m.score||0).toFixed(3)}</em></span>)}</div>}{!q.data?<Empty loading={q.loading} error={q.error}/>:<div className="cards">{q.data.map(s=><article className="asset-card skill-card" onClick={()=>open(s)} key={s.id}><div className="asset-top"><span className="asset-icon purple">✦</span><Status value={s.status}/></div><h3>{s.name}</h3><p>{s.description||s.content?.slice(0,90)||'暂无描述'}</p><div className="tags">{s.tags.map(t=><span>{t}</span>)}</div><footer><span>v{s.version} · 灰度 {s.rollout_percent??100}%</span><time>{fmt(s.updated_at)}</time></footer></article>)}{!q.data.length&&<Empty/>}</div>}
 {create&&<SkillForm close={()=>setCreate(false)} submit={v=>act(()=>api.post('/api/skills',v),'候选技能已创建')}/>} {detail&&<Modal wide title={detail.name} onClose={()=>setDetail(null)}><div className="skill-head"><Status value={detail.status}/><span>v{detail.version}</span><span>灰度 {detail.rollout_percent??100}%</span><span>{detail.approved_by?`审批：${detail.approved_by}`:'尚未审批'}</span></div><div className="detail-grid"><div><h4>技能 Markdown</h4><pre className="markdown">{detail.content}</pre></div><div><h4>治理操作</h4><div className="governance"><button onClick={()=>act(()=>api.post(`/api/skills/${detail.id}/validate`),'技能验证完成')}>执行验证</button><button className="primary" onClick={()=>act(()=>api.post(`/api/skills/${detail.id}/publish`,{approved_by:actor}),'技能已发布')}>批准并发布</button><button onClick={()=>{const p=prompt('灰度比例 0-100',String(detail.rollout_percent??100));if(p!==null)act(()=>api.post(`/api/skills/${detail.id}/rollout`,{percent:+p,approved_by:actor}),'灰度比例已更新')}}>调整灰度</button><button onClick={()=>act(()=>api.post(`/api/skills/${detail.id}/reject`,{reason:'控制台审核拒绝'}),'技能已拒绝')}>拒绝候选</button><button className="danger" onClick={()=>act(()=>api.post(`/api/skills/${detail.id}/retire`,{reason:'控制台退役'}),'技能已退役')}>退役</button></div><h4>版本历史</h4><div className="timeline compact">{versions.map(v=><div><span>v{v.version}</span><div><b>{statusLabel[v.status]||v.status}</b><small>{fmt(v.updated_at)}</small></div>{v.version!==detail.version&&<button onClick={()=>act(()=>api.post(`/api/skills/${detail.id}/rollback/${v.version}`,{approved_by:actor,reason:'控制台回滚'}),'技能已回滚')}>回滚</button>}</div>)}</div><h4>验证信息</h4><pre className="json-view small">{JSON.stringify(detail.validation||{},null,2)}</pre></div></div></Modal>}</>}
function SkillForm({close,submit}:{close:()=>void;submit:(v:unknown)=>void}){const [f,setF]=useState({name:'',description:'',tags:'',content:'# 技能名称\n\n## 适用场景\n\n## 执行步骤\n\n1. \n\n## 验证与回滚\n'});return <Modal wide title="新建候选技能" onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();submit({...f,tags:split(f.tags)})}}><Field label="技能名称"><input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="标签"><input value={f.tags} onChange={e=>setF({...f,tags:e.target.value})}/></Field><Field label="描述" span><input value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><Field label="技能 Markdown" span><textarea className="code" rows={16} required value={f.content} onChange={e=>setF({...f,content:e.target.value})}/></Field><FormActions close={close}/></form></Modal>}

function Tools({api,notify}:Ctx){const q=useLoad(()=>api.get<Tool[]>('/api/tools'),[api]);const [create,setCreate]=useState(false),[edit,setEdit]=useState<Tool|null>(null);const act=async(fn:()=>Promise<any>,msg:string)=>{try{await fn();notify(msg);setCreate(false);setEdit(null);q.reload()}catch(e){notify((e as Error).message,true)}};return <><div className="toolbar"><div className="filter-tabs"><button className="active">全部</button><button>已启用 {q.data?.filter(x=>x.enabled).length||0}</button></div><button className="primary" onClick={()=>setCreate(true)}>＋ 登记工具</button></div>{!q.data?<Empty loading={q.loading} error={q.error}/>:<article className="panel table-wrap"><table><thead><tr><th>工具</th><th>标识</th><th>分类</th><th>标签</th><th>状态</th><th>更新时间</th><th/></tr></thead><tbody>{q.data.map(t=><tr><td><b>{t.display_name}</b><small className="block">{t.description}</small></td><td><code>{t.name}</code></td><td>{t.category}</td><td><div className="tags">{t.tags.map(x=><span>{x}</span>)}</div></td><td><Status value={t.enabled?'succeeded':'canceled'}/></td><td>{fmt(t.updated_at)}</td><td><button onClick={()=>setEdit(t)}>编辑</button> <button className="danger-link" onClick={()=>confirm('确认删除？')&&act(()=>api.delete(`/api/tools/${t.id}`),'工具已删除')}>删除</button></td></tr>)}</tbody></table>{!q.data.length&&<Empty/>}</article>}{(create||edit)&&<ToolForm tool={edit} close={()=>{setCreate(false);setEdit(null)}} submit={v=>act(()=>edit?api.put(`/api/tools/${edit.id}`,v):api.post('/api/tools',v),edit?'工具已更新':'工具已登记')}/>}</>}
function ToolForm({tool,close,submit}:{tool:Tool|null;close:()=>void;submit:(v:unknown)=>void}){const [f,setF]=useState({name:tool?.name||'',display_name:tool?.display_name||'',description:tool?.description||'',category:tool?.category||'general',enabled:tool?.enabled??true,tags:(tool?.tags||[]).join(',')});return <Modal title={tool?'编辑工具':'登记工具'} onClose={close}><form className="form-grid" onSubmit={e=>{e.preventDefault();submit({...f,tags:split(f.tags),metadata:tool?.metadata||{}})}}><Field label="显示名称"><input required value={f.display_name} onChange={e=>setF({...f,display_name:e.target.value})}/></Field><Field label="唯一标识"><input disabled={!!tool} required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="分类"><input value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></Field><Field label="标签"><input value={f.tags} onChange={e=>setF({...f,tags:e.target.value})}/></Field><Field label="描述" span><textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><Field label="启用"><input type="checkbox" checked={f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/></Field><FormActions close={close} label={tool?'保存修改':'登记工具'}/></form></Modal>}

function System({api,notify}:Ctx){const q=useLoad(()=>Promise.all([api.get<SystemStatus>('/api/system/status'),api.get<any>('/api/system/metrics'),api.get<{records:Json[]}>('/api/system/audit-logs?limit=100')]),[api]);const exportData=async()=>{try{const d=await api.get('/api/system/export');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'}));a.download=`agentforge-snapshot-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href);notify('系统快照已导出')}catch(e){notify((e as Error).message,true)}};if(!q.data)return <Empty loading={q.loading} error={q.error}/>;const [s,m,a]=q.data;return <><div className="toolbar"><div/><button onClick={q.reload}>↻ 刷新状态</button><button className="primary" onClick={exportData}>↓ 导出系统快照</button></div><div className="grid two"><article className="panel"><div className="panel-head"><div><h2>模型连接</h2><p>后端当前解析到的运行资源</p></div></div><div className="model-stack">{Object.entries(s.models).map(([k,v])=><div className="model-card"><span className={`model-badge ${k}`}>{k==='device'?'端':k==='edge'?'边':'云'}</span><div><b>{v.model||'未配置'}</b><small>{v.base_url||'未配置 endpoint'}</small></div><Status value={v.configured?'succeeded':'failed'}/></div>)}</div></article><article className="panel"><div className="panel-head"><div><h2>能力与安全</h2><p>运行时功能开关</p></div></div>{Object.entries(s.capabilities).map(([k,v])=><div className="kv"><span>{k.replaceAll('_',' ')}</span><Status value={v?'succeeded':'failed'}/></div>)}<div className="kv"><span>管理员密钥保护</span><Status value={s.security?.admin_key_enabled?'succeeded':'failed'}/></div></article></div><article className="panel"><div className="panel-head"><div><h2>API 审计日志</h2><p>最近 100 次写操作及授权结果</p></div><span>{a.records.length} 条记录</span></div><div className="audit-list">{a.records.map((x:any,i)=><div key={i}><Status value={x.authorized?'succeeded':'failed'}/><code>{x.method}</code><b>{x.path}</b><span>{x.actor||'anonymous'}</span><time>{fmt(x.ts)}</time><em>{x.status_code}</em></div>)}{!a.records.length&&<Empty text="暂无审计记录"/>}</div></article><article className="panel storage"><h2>存储位置</h2>{Object.entries(s.storage).map(([k,v])=><KV label={k} value={v}/>)}</article></>}
function Settings({baseUrl,adminKey,actor,save}:{baseUrl:string;adminKey:string;actor:string;save:(u:string,k:string,a:string)=>void}){const [u,setU]=useState(baseUrl),[k,setK]=useState(adminKey),[a,setA]=useState(actor);return <div className="settings-card"><div className="settings-icon">⚙</div><h2>后端连接</h2><p>凭据仅保存在当前浏览器的 localStorage，不会出现在导出的系统快照中。</p><form onSubmit={e=>{e.preventDefault();save(u,k,a)}} className="settings-form"><Field label="FastAPI 服务地址"><input required value={u} onChange={e=>setU(e.target.value)}/><small>开发环境推荐使用 /，由 Vite 代理到 127.0.0.1:8000</small></Field><Field label="操作者标识（X-Actor）"><input required value={a} onChange={e=>setA(e.target.value)}/></Field><Field label="管理员密钥（X-Admin-Key）"><input type="password" value={k} onChange={e=>setK(e.target.value)} placeholder="后端未开启时可留空"/></Field><button className="primary" type="submit">保存并重新连接</button></form></div>}
export default App;
