import { createPortal } from 'react-dom';
import type { Run, Workflow } from './types';
import './workflow-editor-features.css';

export function ApplicationObserveDrawer({runs,detail,busy,close,select}:{runs:Run[];detail:Run|null;busy:boolean;close:()=>void;select:(run:Run)=>void}){
  return createPortal(<div className="workflow-side-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="workflow-side-drawer"><header><div><b>运行观测</b><small>当前应用的测试与发布运行</small></div><button onClick={close}>×</button></header>{busy&&!runs.length?<div className="workflow-drawer-empty"><span className="spinner"/>正在加载运行记录…</div>:!runs.length?<div className="workflow-drawer-empty">暂无运行记录，请先测试或调试应用。</div>:<div className="workflow-observe-body"><div className="workflow-run-list">{runs.map(run=><button className={detail?.id===run.id?'active':''} onClick={()=>select(run)} key={run.id}><span className={`run-state ${run.status}`}/><div><b>{run.status}</b><small>{run.id}</small></div><time>{formatDate(run.created_at)}</time></button>)}</div><section className="workflow-run-detail">{detail?<><div className="workflow-detail-summary"><b>{detail.status}</b><span>耗时：{String((detail.metadata as any)?.duration_ms??'—')} ms</span><span>事件：{detail.events?.length||0}</span></div>{detail.error&&<div className="workflow-run-error">{detail.error}</div>}<div className="workflow-event-list">{(detail.events||[]).map((event:any,index)=><article key={event.sequence||index}><div><b>{eventName(event.type)}</b><time>{event.timestamp?formatDate(event.timestamp):''}</time></div><p>{event.message||event.node||'运行事件'}</p>{(event.model||event.executor)&&<small>{event.model||'未记录模型'} · {event.executor||'未记录执行器'}</small>}{(event.tool_calls||[]).map((call:any,i:number)=><code key={i}>{call.display_name||call.name||'工具'} · {call.status}</code>)}</article>)}</div></>:<div className="workflow-drawer-empty">选择一条运行查看节点、模型和工具事件。</div>}</section></div>}</aside></div>,document.body);
}

export function ApplicationVersionDrawer({currentVersion,versions,busy,close,activate}:{currentVersion:number;versions:Workflow[];busy:boolean;close:()=>void;activate:(version:number)=>void}){
  return createPortal(<div className="workflow-side-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="workflow-side-drawer version-drawer"><header><div><b>版本管理</b><small>每次发布生成新版本；切换版本不会创建额外版本</small></div><button onClick={close}>×</button></header>{busy&&!versions.length?<div className="workflow-drawer-empty"><span className="spinner"/>正在读取版本…</div>:<div className="workflow-version-list">{versions.map(item=><article key={item.version}><span>v{item.version}</span><div><b>{item.version===currentVersion?'当前版本':'已发布版本'}</b><small>{formatDate(String((item.metadata as any)?.published_at||item.updated_at))} · {item.graph?.agents?.length||0} 个节点</small></div>{item.version!==currentVersion&&<button disabled={busy} onClick={()=>activate(item.version)}>选择此版本</button>}</article>)}{!versions.length&&<div className="workflow-drawer-empty">尚未发布版本，点击发布后将生成 v1。</div>}</div>}</aside></div>,document.body);
}

function eventName(type:string){return({plan_created:'执行计划',node_start:'节点开始',node_end:'节点完成',tool_result:'工具结果',approval_required:'等待审批',final:'执行完成'} as Record<string,string>)[type]||type}
function formatDate(value:string){if(!value)return'';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString('zh-CN',{hour12:false})}
