import { useState } from 'react';
import type { ApiClient } from './api';
import type { ModelConnection } from './types';

type Preset = { provider: string; name: string; base_url?: string };
type Tier = 'device' | 'edge' | 'cloud';
const tiers: Array<[Tier, string]> = [['device', '端'], ['edge', '边'], ['cloud', '云']];
const runnable = (model: ModelConnection) => model.enabled && model.configured && model.test_status === 'succeeded';

export function ModelConnectionModal({ api, models, presets, close, done }: { api: ApiClient; models: ModelConnection[]; presets: Preset[]; close: () => void; done: () => Promise<unknown>; }) {
  const [form, setForm] = useState({ name: '', provider: presets[0]?.provider || 'openai', model_id: '', base_url: '', api_key_env: '', tier: 'cloud' as Tier, auto_default: false, enabled: true });
  const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [testResult, setTestResult] = useState(''); const [pendingDelete, setPendingDelete] = useState<ModelConnection | null>(null);
  const autoReady = tiers.every(([tier]) => models.some(model => model.tier === tier && model.auto_default && runnable(model)));
  const set = (key: string, value: string | boolean) => setForm(old => ({ ...old, [key]: value }));
  const beginCreate = (tier: Tier, autoDefault: boolean) => { setError(''); setTestResult(''); setForm(old => ({ ...old, tier, auto_default: autoDefault })); };
  const create = async () => { setBusy('create'); setError(''); try { await api.post('/api/model-connections', form); await done(); setForm(old => ({ ...old, name: '', model_id: '', base_url: '', api_key_env: '' })); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  const test = async (id: string) => { setBusy(id); setError(''); try { const value = await api.post<any>(`/api/model-connections/${id}/test`); setTestResult(`${value.test_result?.model || '模型'} 真实推理成功 · ${value.test_result?.latency_ms || 0} ms`); await done(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  const setDefault = async (model: ModelConnection) => { setBusy(`default-${model.id}`); setError(''); try { await api.put(`/api/model-connections/${model.id}`, { auto_default: true }); await done(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  const remove = async () => { if (!pendingDelete) return; setBusy(`delete-${pendingDelete.id}`); setError(''); try { await api.delete(`/api/model-connections/${pendingDelete.id}`); setPendingDelete(null); await done(); } catch (e) { setError((e as Error).message); setPendingDelete(null); } finally { setBusy(''); } };
  const connectionRow = (model: ModelConnection, allowDefault: boolean) => <div className="model-connection-row" key={model.id}><span><b className={runnable(model) ? 'model-ready-text' : ''}>{model.name}{model.auto_default && <mark>AUTO 默认</mark>}</b><small>{model.provider} · {model.model_id || '未填写模型 ID'}</small></span><em className={model.test_status}>{model.test_status === 'succeeded' ? '测试成功' : model.test_status === 'failed' ? '测试失败' : '待测试'}</em>{allowDefault && !model.auto_default && <button disabled={busy === `default-${model.id}`} onClick={() => setDefault(model)}>设为 AUTO 默认</button>}<button disabled={busy === model.id} onClick={() => test(model.id)}>{busy === model.id ? '测试中…' : '连接测试'}</button><button className="danger model-delete-button" disabled={busy === `delete-${model.id}`} onClick={() => setPendingDelete(model)}>删除</button></div>;
  const formPanel = (tier: Tier, autoDefault: boolean) => <div className="model-connection-form import-form"><div className="model-connect-help">密钥只写在后端 <code>.env</code>，这里填写对应的变量名。DeepSeek 默认使用 <code>OPENAI_API_KEY</code>；Ollama 可留空。</div><label>连接名称<input value={form.name} onFocus={() => beginCreate(tier, autoDefault)} onChange={e => set('name', e.target.value)} placeholder={autoDefault ? `${tiers.find(item => item[0] === tier)?.[1]}侧 AUTO 默认模型` : '例如：业务专用模型'} /></label><label>提供商<select value={form.provider} onFocus={() => beginCreate(tier, autoDefault)} onChange={e => { const preset = presets.find(p => p.provider === e.target.value); setForm(old => ({ ...old, provider: e.target.value, base_url: preset?.base_url || old.base_url, name: old.name || preset?.name || '', tier, auto_default: autoDefault })); }}>{presets.map(p => <option key={p.provider} value={p.provider}>{p.name}</option>)}</select></label><label>模型 ID<input value={form.model_id} onFocus={() => beginCreate(tier, autoDefault)} onChange={e => set('model_id', e.target.value)} placeholder="以服务商实际 model_id 为准" /></label><label>OpenAI 兼容 Base URL<input value={form.base_url} onFocus={() => beginCreate(tier, autoDefault)} onChange={e => set('base_url', e.target.value)} placeholder="https://api.example.com/v1" /></label><label>API Key 环境变量<input value={form.api_key_env} onFocus={() => beginCreate(tier, autoDefault)} onChange={e => set('api_key_env', e.target.value)} placeholder="例如 OPENAI_API_KEY" /><small>只保存变量名，密钥不会写入配置目录。</small></label><footer><button className="primary" disabled={busy === 'create' || !form.name.trim() || !form.model_id.trim() || !form.base_url.trim()} onClick={create}>{busy === 'create' ? '创建中…' : autoDefault ? '保存为 AUTO 默认模型' : '创建其他模型'}</button></footer></div>;
  return <div className="overlay"><div className="external-import-modal model-connection-modal"><header><div><h2>模型连接管理</h2><p>先配置 AUTO 的端、边、云默认模型；再按需添加 Agent 固定使用的其他模型。</p></div><button onClick={close}>×</button></header><details className={`model-config-group model-auto-group ${autoReady ? 'ready' : ''}`} open><summary><span><b>Auto 模型配置</b><small>端、边、云均测试成功后，AUTO 才可用。</small></span><em>{autoReady ? '已就绪 ✓' : '未就绪'}</em></summary><div className="model-group-body">{tiers.map(([tier, label]) => { const tierModels = models.filter(model => model.tier === tier); const defaultModel = tierModels.find(model => model.auto_default); const ready = Boolean(defaultModel && runnable(defaultModel)); return <details className={`model-tier-config ${ready ? 'ready' : ''}`} key={tier}><summary><span><b>{label}模型配置</b><small>{defaultModel ? `${defaultModel.name} · ${defaultModel.model_id}` : `尚未设置${label}模型`}</small></span><em>{ready ? '已配置 ✓' : '待配置'}</em></summary><div className="model-tier-body">{tierModels.length ? tierModels.map(model => connectionRow(model, true)) : <p>尚未配置{label}模型。</p>}{formPanel(tier, true)}</div></details>; })}</div></details><details className="model-config-group"><summary><span><b>其他模型配置</b><small>配置成功后，可在 Agent 的模型下拉框中固定选择。</small></span><em>{models.filter(model => !model.auto_default && runnable(model)).length} 个可用</em></summary><div className="model-group-body"><div className="other-model-list">{models.filter(model => !model.auto_default).map(model => connectionRow(model, false))}{!models.some(model => !model.auto_default) && <p>尚未添加其他模型。</p>}</div>{formPanel('cloud', false)}</div></details>{error && <div className="import-error model-modal-error">{error}</div>}{testResult && <div className="model-test-result model-modal-result">✓ {testResult}</div>}<footer className="model-modal-footer"><button onClick={close}>关闭</button></footer>{pendingDelete && <div className="model-delete-layer" onMouseDown={event => event.target === event.currentTarget && setPendingDelete(null)}><section role="alertdialog" aria-modal="true" aria-labelledby="model-delete-title"><h3 id="model-delete-title">删除模型连接</h3><p>确定删除“{pendingDelete.name}”吗？删除后无法恢复。</p><footer><button onClick={() => setPendingDelete(null)}>取消</button><button className="danger" autoFocus disabled={busy === `delete-${pendingDelete.id}`} onClick={remove}>{busy === `delete-${pendingDelete.id}` ? '删除中…' : '确认删除'}</button></footer></section></div>}</div></div>;
}
