import { useEffect, useMemo, useState } from 'react';
import type { ApiClient } from './api';
import type { Json, Run, Workflow } from './types';
type Props={api:ApiClient;notify:(s:string,b?:boolean)=>void};
const terminal=new Set(['succeeded','failed','canceled']);
const fmt=(s?:string|null)=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—';
const duration=(ms?:number)=>{if(ms==null)return'计算中';const sec=Math.max(0,Math.floor(ms/1000));return sec<60?`${sec} 秒`:`${Math.floor(sec/60)} 分 ${sec%60} 秒`};

export function RunConsole({api,notify}:Props){
 const [runs,setRuns]=useState<Run[]>([]),[workflows,setWorkflows]=useState<Workflow[]>([]),[selected,setSelected]=useState<Run|null>(null),[events,setEvents]=useState<Json[]>([]),[showCreate,setShowCreate]=useState(false),[expanded,setExpanded]=useState(true),[now,setNow]=useState(Date.now());
 const load=async()=>{try{const [r,w]=await Promise.all([api.get<Run[]>('/api/runs'),api.get<Workflow[]>('/api/workflows')]);setRuns(r);setWorkflows(w);if(selected){const latest=r.find(x=>x.id===selected.id);if(latest)setSelected(latest)}}catch(e){notify((e as Error).message,true)}};
 useEffect(()=>{load()},[api]); useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!selected)return;setEvents(selected.events||[]);setExpanded(!terminal.has(selected.status));if(terminal.has(selected.status))return;const base=api.baseUrl.replace(/\/$/,'');const token=encodeURIComponent(api.getAuthToken());const source=new EventSource(`${base}/api/runs/${selected.id}/events?after=${selected.events?.length||0}&access_token=${token}`);source.addEventListener('run_event',e=>{const item=JSON.parse((e as MessageEvent).data);setEvents(old=>[...old,item])});source.addEventListener('run_completed',async()=>{source.close();const done=await api.get<Run>(`/api/runs/${selected.id}`);setSelected(done);setExpanded(false);load()});source.onerror=()=>source.close();return()=>source.close()},[selected?.id,selected?.status,api]);
 const elapsed=useMemo(()=>{if(!selected)return 0;const saved=Number((selected.metadata as any)?.duration_ms);if(saved)return saved;const start=String((selected.metadata as any)?.started_at||selected.created_at);return now-new Date(start).getTime()},[selected,now]);
 const summary=(selected?.metadata as any)?.summary;
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);let input:Json;try{input=JSON.parse(String(f.get('input')))}catch{notify('运行输入必须是合法 JSON',true);return}try{const run=await api.post<Run>('/api/runs',{workflow_id:f.get('workflow_id')||null,input,recursion_limit:50});setShowCreate(false);setSelected(run);setRuns(x=>[run,...x]);notify('任务已开始运行')}catch(e){notify((e as Error).message,true)}};
 return <div className="run-console"><aside className="run-sidebar"><button className="new-task" onClick={()=>setShowCreate(true)}>＋ 新任务</button><div className="run-history">{runs.map(r=><button className={selected?.id===r.id?'active':''} onClick={()=>setSelected(r)} key={r.id}><span className={`run-state ${r.status}`}/><div><b>{workflows.find(w=>w.id===r.workflow_id)?.name||'临时编排'}</b><small>{r.id}</small></div><time>{fmt(r.created_at).slice(5,16)}</time></button>)}</div></aside><section className="transcript">{!selected?<div className="transcript-empty"><span>✦</span><h2>开始一项智能体任务</h2><p>选择已发布工作流，运行过程中的 Agent 切换、工具调用和结果会实时显示在这里。</p><button className="primary" onClick={()=>setShowCreate(true)}>发起任务</button></div>:<><div className="task-heading"><div><span className={`task-dot ${selected.status}`}/><div><h2>{workflows.find(w=>w.id===selected.workflow_id)?.name||'临时编排任务'}</h2><p>{String(selected.input?.input||'结构化任务')}</p></div></div><button onClick={()=>setExpanded(v=>!v)}>{expanded?'收起过程':'展开完整过程'} · {events.length}</button></div>
  <div className={`process-stream ${expanded?'':'collapsed'}`}>{events.map((e:any,i)=><EventBlock event={e} key={e.sequence||i}/>)}</div>
  {terminal.has(selected.status)&&<div className="final-answer"><div className="final-label">最终总结</div><h2>{summary?.title||'运行完成'}</h2><p className="overview-text">{summary?.overview||`本次任务共产生 ${events.length} 条执行事件。`}</p>{summary?.steps?.map((s:any)=><div className="summary-step" key={s.order}><span>{s.order}</span><div><b>{s.agent}</b><p>{s.output||'该步骤没有文本输出'}</p><small>{s.executor||'未知执行器'} · {s.model||'默认模型'}</small></div></div>)}<div className="final-output"><h3>最终输出</h3><pre>{summary?.final_output||JSON.stringify(selected.state,null,2)}</pre></div><div className="completion-meta">完成于 {fmt(selected.finished_at)} · 总用时 {duration(elapsed)} · {events.length} 条运行事件</div></div>}
  {!terminal.has(selected.status)&&<div className="working-indicator"><i/><span>{(selected.metadata as any)?.active_agent?`${(selected.metadata as any).active_agent} 正在工作`:'正在准备下一步'} · 已运行 {duration(elapsed)}</span></div>}
 </>}</section>
 {showCreate&&<div className="overlay"><div className="modal"><div className="modal-head"><h2>发起智能体任务</h2><button onClick={()=>setShowCreate(false)}>×</button></div><form className="form-grid" onSubmit={create}><label className="span"><span>工作流</span><select name="workflow_id" required><option value="">请选择已保存工作流</option>{workflows.map(w=><option value={w.id}>{w.name} · v{w.version}</option>)}</select></label><label className="span"><span>任务输入 JSON</span><textarea name="input" className="code" rows={9} defaultValue={'{\n  "input": "请描述你希望智能体完成的任务"\n}'}/></label><div className="form-actions span"><button type="button" onClick={()=>setShowCreate(false)}>取消</button><button className="primary">开始运行</button></div></form></div></div>}</div>
}
function EventBlock({event:e}:{event:any}){if(e.type==='node_start')return <div className="event agent-start"><span className="event-icon">AI</span><div><b>正在调用 {e.node}</b><p>{e.message||'开始处理当前步骤'}</p><small>{fmt(e.timestamp)}</small></div></div>;if(e.type==='node_end')return <div className="event agent-output"><span className="event-line"/><div><b>{e.node} 完成</b>{(e.tool_calls||[]).map((t:any,i:number)=><div className="tool-call" key={i}>⌁ 接下来调用 {t.name||t.tool||'工具'} <code>{JSON.stringify(t.arguments||{})}</code></div>)}<p>{e.output||extractOutput(e.update)||'步骤已完成，未产生可见文本。'}</p><small>{e.executor||'执行器未记录'} {e.model?`· ${e.model}`:''}</small></div></div>;if(e.type==='route')return <div className="event route-event"><span>↳</span><p>{e.message||`下一步：${(e.targets||[]).join('、')||'结束'}`}</p></div>;if(e.type==='final')return <div className="event final-event"><span>✓</span><p>所有工作流节点执行完成，正在整理最终总结。</p></div>;return <div className="event system-event"><span>·</span><p>{e.message||e.type}</p></div>}
function extractOutput(update:any){const m=update?.messages;return Array.isArray(m)&&m.length?m[m.length-1]?.content:''}
