import { useEffect, useMemo, useState } from 'react';
import type { ApiClient } from './api';
import type { Json, Run, Workflow } from './types';
type Props={api:ApiClient;notify:(s:string,b?:boolean)=>void};
const terminal=new Set(['succeeded','failed','canceled']);
const fmt=(s?:string|null)=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—';
const duration=(ms?:number)=>{if(ms==null)return'计算中';const sec=Math.max(0,Math.floor(ms/1000));return sec<60?`${sec} 秒`:`${Math.floor(sec/60)} 分 ${sec%60} 秒`};

export function RunConsole({api,notify}:Props){
 const [runs,setRuns]=useState<Run[]>([]),[workflows,setWorkflows]=useState<Workflow[]>([]),[selected,setSelected]=useState<Run|null>(null),[events,setEvents]=useState<Json[]>([]),[showCreate,setShowCreate]=useState(false),[expanded,setExpanded]=useState(true),[now,setNow]=useState(Date.now());
 const load=async()=>{try{const [r,w]=await Promise.all([api.get<Run[]>('/api/runs'),api.get<Workflow[]>('/api/workflows')]);setRuns(r);setWorkflows(w);if(selected){const latest=r.find(x=>x.id===selected.id);if(latest)setSelected(latest)}}catch(e){notify((e as Error).message,true)}};
 useEffect(()=>{load()},[api]); useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(!selected)return;setEvents(selected.events||[]);setExpanded(!terminal.has(selected.status));if(terminal.has(selected.status))return;const base=api.baseUrl.replace(/\/$/,'');const token=encodeURIComponent(api.getAuthToken());const source=new EventSource(`${base}/api/runs/${selected.id}/events?after=${selected.events?.length||0}&access_token=${token}`);source.addEventListener('run_event',e=>{const item=JSON.parse((e as MessageEvent).data);setEvents(old=>[...old,item])});source.addEventListener('run_completed',async()=>{source.close();const done=await api.get<Run>(`/api/runs/${selected.id}`);setSelected(done);setExpanded(false);load()});source.onerror=()=>source.close();return()=>source.close()},[selected?.id,selected?.status,api]);
 const elapsed=useMemo(()=>{if(!selected)return 0;const saved=Number((selected.metadata as any)?.duration_ms);if(saved)return saved;const start=String((selected.metadata as any)?.started_at||selected.created_at);return now-new Date(start).getTime()},[selected,now]);
 const summary=(selected?.metadata as any)?.summary;
 const todos=(selected?.metadata as any)?.todos||events.find((e:any)=>e.type==='plan_created')?.todos||[];
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);let input:Json;try{input=JSON.parse(String(f.get('input')))}catch{notify('运行输入必须是合法 JSON',true);return}try{const run=await api.post<Run>('/api/runs',{workflow_id:f.get('workflow_id')||null,input,recursion_limit:50});setShowCreate(false);setSelected(run);setRuns(x=>[run,...x]);notify('任务已开始运行')}catch(e){notify((e as Error).message,true)}};
 return <div className="run-console"><aside className="run-sidebar"><button className="new-task" onClick={()=>setShowCreate(true)}>＋ 新任务</button><div className="run-history">{runs.map(r=><button className={selected?.id===r.id?'active':''} onClick={()=>setSelected(r)} key={r.id}><span className={`run-state ${r.status}`}/><div><b>{workflows.find(w=>w.id===r.workflow_id)?.name||'临时编排'}</b><small>{r.id}</small></div><time>{fmt(r.created_at).slice(5,16)}</time></button>)}</div></aside><section className="transcript">{!selected?<div className="transcript-empty"><span>✦</span><h2>开始一项智能体任务</h2><p>选择已发布工作流，运行过程中的 Agent 切换、工具调用和结果会实时显示在这里。</p><button className="primary" onClick={()=>setShowCreate(true)}>发起任务</button></div>:<><div className="task-heading"><div><span className={`task-dot ${selected.status}`}/><div><h2>{workflows.find(w=>w.id===selected.workflow_id)?.name||'临时编排任务'}</h2><p>{String(selected.input?.input||'结构化任务')}</p></div></div><button onClick={()=>setExpanded(v=>!v)}>{expanded?'收起过程':'展开完整过程'} · {events.length}</button></div>
  {todos.length>0&&<TodoStrip todos={todos}/>}
  <div className={`process-stream ${expanded?'':'collapsed'}`}>{events.map((e:any,i)=><EventBlock api={api} notify={notify} runId={selected.id} reload={async()=>{const done=await api.get<Run>(`/api/runs/${selected.id}`);setSelected(done);setEvents(done.events||[]);load()}} event={e} key={e.sequence||i}/>)}</div>
  {terminal.has(selected.status)&&<div className="final-answer"><div className="final-label">最终总结</div><h2>{summary?.title||'运行完成'}</h2><p className="overview-text">{summary?.overview||`本次任务共产生 ${events.length} 条执行事件。`}</p>{summary?.steps?.map((s:any)=><div className="summary-step" key={s.order}><span>{s.order}</span><div><b>{s.agent}</b><p>{s.output||'该步骤没有文本输出'}</p><small>{s.executor||'未知执行器'} · {s.model||'默认模型'}</small></div></div>)}<div className="final-output"><h3>最终输出</h3><pre>{summary?.final_output||JSON.stringify(selected.state,null,2)}</pre></div><div className="completion-meta">完成于 {fmt(selected.finished_at)} · 总用时 {duration(elapsed)} · {events.length} 条运行事件</div></div>}
  {!terminal.has(selected.status)&&<div className="working-indicator"><i/><span>{(selected.metadata as any)?.active_agent?`${(selected.metadata as any).active_agent} 正在工作`:'正在准备下一步'} · 已运行 {duration(elapsed)}</span></div>}
 </>}</section>
 {showCreate&&<div className="overlay"><div className="modal"><div className="modal-head"><h2>发起智能体任务</h2><button onClick={()=>setShowCreate(false)}>×</button></div><form className="form-grid" onSubmit={create}><label className="span"><span>工作流</span><select name="workflow_id" required><option value="">请选择已保存工作流</option>{workflows.map(w=><option value={w.id}>{w.name} · v{w.version}</option>)}</select></label><label className="span"><span>任务输入 JSON</span><textarea name="input" className="code" rows={9} defaultValue={'{\n  "input": "请描述你希望智能体完成的任务"\n}'}/></label><div className="form-actions span"><button type="button" onClick={()=>setShowCreate(false)}>取消</button><button className="primary">开始运行</button></div></form></div></div>}</div>
}
function TodoStrip({todos}:{todos:any[]}){return <div className="todo-strip">{todos.map((t:any)=><div className={`todo-pill ${t.status}`} key={t.id}><span>{t.status==='completed'?'✓':t.status==='in_progress'?'…':'○'}</span><p>{t.content}</p></div>)}</div>}
function EventBlock({event:e,api,notify,runId,reload}:{event:any;api:ApiClient;notify:(s:string,b?:boolean)=>void;runId:string;reload:()=>Promise<void>}){
 if(e.type==='plan_created')return <div className="event plan-event"><span className="event-icon">TODO</span><div><b>已生成执行计划</b><ol>{(e.plan||[]).map((p:string,i:number)=><li key={i}>{p}</li>)}</ol><small>{fmt(e.timestamp)}</small></div></div>;
 if(e.type==='todo_updated')return <div className="event todo-event"><span>✓</span><div><b>TODO 已更新</b><p>{e.message}</p><small>{fmt(e.timestamp)}</small></div></div>;
 if(e.type==='node_start')return <div className="event agent-start"><span className="event-icon">AI</span><div><b>正在调用 {e.node}</b><p>{e.message||'开始处理当前步骤'}</p><small>{fmt(e.timestamp)}</small></div></div>;
 if(e.type==='node_end')return <div className="event agent-output"><span className="event-line"/><div><b>{e.node} 完成</b>{(e.tool_calls||[]).map((t:any,i:number)=><ToolLine call={t} key={i}/>) }<p>{e.output||extractOutput(e.update)||'步骤已完成，未产生可见文本。'}</p><small>{e.executor||'执行器未记录'} {e.model?`· ${e.model}`:''}</small></div></div>;
 if(e.type==='tool_result')return <div className="event tool-event"><span>⌁</span><div><b>{e.tool_call?.display_name||e.tool_call?.name||'工具'} 调用结果</b><ToolLine call={e.tool_call}/><small>{fmt(e.timestamp)}</small></div></div>;
 if(e.type==='approval_required')return <ApprovalEvent event={e} api={api} notify={notify} runId={runId} reload={reload}/>;
 if(e.type==='approval_decision')return <div className={`event approval-event ${e.approved?'approved':'rejected'}`}><span>{e.approved?'✓':'×'}</span><div><b>{e.approved?'已批准':'已拒绝'}：{e.tool_call?.display_name||e.tool_call?.name||'工具'}</b><p>{e.reason||e.message}</p><small>{fmt(e.timestamp)}</small></div></div>;
 if(e.type==='route')return <div className="event route-event"><span>↳</span><p>{e.message||`下一步：${(e.targets||[]).join('、')||'结束'}`}</p></div>;
 if(e.type==='capsule_created')return <div className="event system-event"><span>◇</span><div><b>结构化消息已生成</b><p>{e.capsule?.sender||'Agent'}：{e.capsule?.claim||'状态/约束增量'}</p></div></div>;
 if(e.type==='capsule_delivered')return <div className="event route-event"><span>⇢</span><div><b>低熵消息 → {e.recipient}</b><p>{e.capsule?.claim||JSON.stringify(e.capsule?.constraint_delta||{})}</p><small>贡献度 {Number(e.decision?.score||0).toFixed(3)}</small></div></div>;
 if(e.type==='capsule_pruned')return <div className="event system-event"><span>×</span><div><b>冗余消息已裁剪</b><p>{(e.decision?.reasons||[]).join('、')}</p></div></div>;
 if(e.type==='capsule_compressed')return <div className="event system-event"><span>⇣</span><p>消息压缩 {e.original_tokens} → {e.compressed_tokens} tokens</p></div>;
 if(e.type==='state_delta')return <div className="event system-event"><span>Δ</span><p>状态差分 r{e.delta?.base_revision} → r{e.delta?.revision}</p></div>;
 if(e.type==='temporal_facts_updated')return <div className="event system-event"><span>◷</span><p>时态证据记忆更新 {e.facts?.length||0} 条事实</p></div>;
 if(e.type==='plan_verified')return <div className="event system-event"><span>⊨</span><div><b>符号计划验证通过</b><p>revision {e.outcome?.plan?.revision||0} · {e.outcome?.validation?.backend||'deterministic'} · {e.outcome?.plan?.subtasks?.length||0} 个子任务</p></div></div>;
 if(e.type==='plan_rejected')return <div className="event approval-event rejected"><span>⊥</span><div><b>计划约束不可满足</b><p>{(e.outcome?.validation?.violations||[]).map((v:any)=>v.message).join('；')}</p></div></div>;
 if(e.type==='symbolic_counterexample')return <div className="event system-event"><span>CE</span><div><b>反例已反馈给 Planner</b><p>{e.capsule?.claim}：{JSON.stringify(e.capsule?.constraint_delta||{})}</p></div></div>;
 if(e.type==='failure_detected')return <div className="event approval-event rejected"><span>!</span><div><b>检测到 {e.failure?.kind||'未知'} 故障</b><p>{e.failure?.node} · {e.failure?.message}</p><small>attempt {e.failure?.attempt||1} · {e.failure?.side_effect_class||'idempotent'}</small></div></div>;
 if(e.type==='recovery_planned')return <div className="event system-event"><span>↻</span><div><b>恢复策略：{e.episode?.action?.action}</b><p>{e.episode?.action?.reason}</p><small>{(e.episode?.action?.targets||[]).join('、')}</small></div></div>;
 if(e.type==='fallback_selected')return <div className="event route-event"><span>⇄</span><div><b>已选择 {e.fallback_type} fallback</b><p>{JSON.stringify(e.binding||e.metadata||e.targets||{})}</p></div></div>;
 if(e.type==='degrade_entered')return <div className="event system-event"><span>▽</span><div><b>进入显式降级模式</b><p>{JSON.stringify(e.contract||{})}</p></div></div>;
 if(e.type==='takeover_assigned')return <div className="event route-event"><span>⇢</span><p>{e.source} 已由 {(e.targets||[]).join('、')} 接管</p></div>;
 if(e.type==='plan_revised')return <div className="event system-event"><span>Δ</span><div><b>触发局部重规划</b><p>{e.reason} · checkpoint {e.checkpoint_id||'latest'}</p></div></div>;
 if(e.type==='recovery_succeeded'||e.type==='recovery_failed')return <div className={`event ${e.type==='recovery_succeeded'?'system-event':'approval-event rejected'}`}><span>{e.type==='recovery_succeeded'?'✓':'×'}</span><p>{e.type==='recovery_succeeded'?'恢复成功':'恢复失败'}：{e.reason||e.episode?.action?.reason||e.episode_id}</p></div>;
 if(e.type==='final')return <div className="event final-event"><span>✓</span><p>所有工作流节点执行完成，正在整理最终总结。</p></div>;
 return <div className="event system-event"><span>·</span><p>{e.message||e.type}</p></div>
}
function ApprovalEvent({event:e,api,notify,runId,reload}:{event:any;api:ApiClient;notify:(s:string,b?:boolean)=>void;runId:string;reload:()=>Promise<void>}){
 const decide=async(approved:boolean)=>{try{await api.post<Run>(`/api/runs/${runId}/approvals/${e.sequence}/${approved?'approve':'reject'}`,{reason:approved?'用户批准':'用户拒绝'});await reload();notify(approved?'已批准工具请求':'已拒绝工具请求')}catch(err){notify((err as Error).message,true)}};
 return <div className="event approval-event"><span>!</span><div><b>需要审批：{e.tool_call?.display_name||e.tool_call?.name||'工具'}</b><p>风险级别 {e.tool_call?.risk||'unknown'}。批准会记录审计决策；只有已注册后端适配器的工具才允许真实执行。</p><div className="approval-actions"><button onClick={()=>decide(false)}>拒绝</button><button className="primary" onClick={()=>decide(true)}>批准</button></div><small>{fmt(e.timestamp)}</small></div></div>
}
function ToolLine({call}:{call:any}){return <div className={`tool-call ${call?.status||''}`}>⌁ 调用 {call?.display_name||call?.name||call?.tool||'工具'} <code>{JSON.stringify(call?.arguments||{})}</code>{call?.status&&<em>{call.status}</em>}{call?.result!==undefined&&<pre>{JSON.stringify(call.result,null,2)}</pre>}{call?.error&&<strong>{call.error}</strong>}</div>}
function extractOutput(update:any){const m=update?.messages;return Array.isArray(m)&&m.length?m[m.length-1]?.content:''}
