import { useMemo, useState } from 'react';
import type { ApiClient } from './api';
import type { Tool } from './types';
import './skill-drawer.css';
import './tool-drawer.css';

export function ToolDrawer({api,tools,selected,close,reload,toggle,notify}:{api:ApiClient;tools:Tool[];selected:string[];close:()=>void;reload:()=>Promise<void>;toggle:(id:string)=>void;notify:(message:string,bad?:boolean)=>void}){
  const [tab,setTab]=useState<'installed'|'external'>('installed'),[source,setSource]=useState('all'),[query,setQuery]=useState('');
  const [mode,setMode]=useState<'mcp'|'openapi'>('mcp'),[url,setUrl]=useState(''),[name,setName]=useState(''),[credential,setCredential]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const rows=useMemo(()=>tools.filter(tool=>(source==='all'||toolSource(tool)===source)&&`${tool.display_name}${tool.name}${tool.description}`.toLowerCase().includes(query.toLowerCase())),[tools,source,query]);
  const connect=async()=>{setBusy(true);setError('');try{const result=mode==='mcp'?await api.post<{tools:Tool[]}>('/api/tool-connections/mcp',{url,name:name||'Remote MCP',credential_env:credential}):await api.post<{tools:Tool[]}>('/api/tool-connections/openapi',{url,credential_env:credential});await reload();for(const tool of result.tools||[])if(!selected.includes(tool.id))toggle(tool.id);notify(`已接入并选择 ${result.tools?.length||0} 个工具`);setTab('installed')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  return <div className="skill-drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="skill-drawer tool-drawer"><header><div><h2>添加工具</h2><p>选择已安装工具，或接入 MCP / OpenAPI 服务。</p></div><button aria-label="关闭" onClick={close}>×</button></header><div className="skill-drawer-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索工具"/></label></div><div className="skill-drawer-tabs"><button className={tab==='installed'?'active':''} onClick={()=>setTab('installed')}>已安装 <b>{tools.length}</b></button><button className={tab==='external'?'active':''} onClick={()=>setTab('external')}>外部接入</button></div>{error&&<div className="skill-drawer-error">{error}</div>}{tab==='installed'?<><div className="skill-categories">{[['all','全部'],['builtin','内置'],['mcp','MCP'],['openapi','OpenAPI']].map(([key,label])=><button className={source===key?'active':''} onClick={()=>setSource(key)} key={key}>{label}</button>)}</div><div className="tool-installed-list">{rows.map(tool=><label className={!tool.enabled?'disabled':''} key={tool.id}><input type="checkbox" disabled={!tool.enabled} checked={selected.includes(tool.id)} onChange={()=>toggle(tool.id)}/><span><b>{tool.display_name||tool.name}</b><small>{tool.description||'暂无描述'}</small></span><em>{toolSource(tool).toUpperCase()}</em></label>)}{!rows.length&&<div className="skill-drawer-empty">没有匹配的工具</div>}</div></>:<div className="skill-custom-import"><div className="skill-import-modes"><button className={mode==='mcp'?'active':''} onClick={()=>setMode('mcp')}>MCP 服务</button><button className={mode==='openapi'?'active':''} onClick={()=>setMode('openapi')}>OpenAPI</button></div><label>HTTPS 地址<input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/mcp"/></label>{mode==='mcp'&&<label>连接名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="企业工具服务"/></label>}<label>凭据环境变量<input value={credential} onChange={e=>setCredential(e.target.value)} placeholder="EXTERNAL_TOOL_API_KEY"/><small>仅保存服务器端环境变量名称，不保存密钥。</small></label><button className="primary" disabled={busy||!url.trim()} onClick={connect}>{busy?'发现并接入中…':'接入、发现并选择'}</button></div>}</aside></div>
}

function toolSource(tool:Tool){const source=String((tool.metadata as any)?.source||'');if(source==='mcp'||tool.category==='mcp')return'mcp';if(source==='openapi'||tool.category==='openapi')return'openapi';return'builtin'}
