import { useEffect, useMemo, useState } from 'react';
import type { ApiClient } from './api';
import type { ConnectionSchema, McpMarketItem, Tool, ToolConnection } from './types';
import './skill-drawer.css';
import './tool-drawer.css';

type Tab='market'|'installed'|'custom';
type Props={api:ApiClient;tools:Tool[];selected:string[];close:()=>void;reload:()=>Promise<void>;toggle:(id:string)=>void;changeMany:(ids:string[],add:boolean)=>void;notify:(message:string,bad?:boolean)=>void;availableToolIds?:string[]};

export function ToolDrawer({api,tools,selected,close,reload,toggle,changeMany,notify,availableToolIds}:Props){
  const [tab,setTab]=useState<Tab>('market');
  const [source,setSource]=useState<'all'|'builtin'|'mcp'>('all'),[query,setQuery]=useState('');
  const [connections,setConnections]=useState<ToolConnection[]>([]),[market,setMarket]=useState<McpMarketItem[]>([]),[expanded,setExpanded]=useState<string[]>([]);
  const [mode,setMode]=useState<'mcp'|'openapi'>('mcp'),[url,setUrl]=useState(''),[name,setName]=useState(''),[credential,setCredential]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const [schema,setSchema]=useState<ConnectionSchema|null>(null),[configuration,setConfiguration]=useState<Record<string,string>>({}),[marketSlug,setMarketSlug]=useState('');
  const load=async()=>{const [c,m]=await Promise.allSettled([api.get<ToolConnection[]>('/api/tool-connections'),api.get<McpMarketItem[]>('/api/marketplace/mcp')]);if(c.status==='fulfilled')setConnections(c.value);else setError(`已安装连接读取失败：${c.reason?.message||'接口不可用'}`);if(m.status==='fulfilled')setMarket(m.value);else throw m.reason};
  useEffect(()=>{void load().catch(e=>setError(e.message))},[]);
  useEffect(()=>{const done=()=>{void reload().then(load).catch(e=>setError(e.message))};window.addEventListener('message',done);return()=>window.removeEventListener('message',done)},[reload]);
  const builtins=useMemo(()=>tools.filter(t=>toolSource(t)==='builtin'&&matches(t,query)),[tools,query]);
  const availableSet=useMemo(()=>availableToolIds?new Set(availableToolIds):null,[availableToolIds]);
  const marketRows=useMemo(()=>market.filter(x=>(source==='all'||source==='mcp')&&`${x.name}${x.provider}${x.category}${x.description}`.toLowerCase().includes(query.toLowerCase())),[market,source,query]);
  const installedRows=useMemo(()=>connections.filter(x=>`${x.name}${x.type}${x.tools.map(t=>t.display_name).join('')}`.toLowerCase().includes(query.toLowerCase())),[connections,query]);
  const changeAll=(items:Tool[],add:boolean)=>changeMany(items.filter(t=>t.enabled).map(t=>t.id),add);
  const resetMcpDetection=()=>{setSchema(null);setConfiguration({});setMarketSlug('')};
  const setConfig=(key:string,value:string)=>setConfiguration(current=>({...current,[key]:value}));
  const install=async(item:McpMarketItem)=>{if(item.requires_configuration){setTab('custom');setMode('mcp');setName(item.name);setUrl(item.mcp_url||'');setSchema(null);setMarketSlug(item.slug);setConfiguration({});return}setBusy(item.slug);setError('');try{const r=await api.post<{connection:ToolConnection;message:string}>(`/api/marketplace/mcp/${item.slug}/install`);await Promise.all([reload(),load()]);setTab('installed');setExpanded([r.connection.id]);notify(r.message)}catch(e){setError((e as Error).message)}finally{setBusy('')}};
  const sync=async(connection:ToolConnection)=>{setBusy(connection.id);setError('');try{const r=await api.post<{connection:ToolConnection;tools:Tool[]}>(`/api/tool-connections/${connection.id}/sync`);await Promise.all([reload(),load()]);setExpanded([r.connection.id]);notify(`已同步 ${r.tools.length} 个 MCP 工具`)}catch(e){setError((e as Error).message)}finally{setBusy('')}};
  const openOAuthWindow=()=>{const popup=window.open('about:blank','mcp-oauth','popup,width=640,height=760');if(popup){popup.document.title='正在连接服务';popup.document.body.innerHTML='<main style="font-family:system-ui,sans-serif;max-width:420px;margin:96px auto;padding:24px;color:#27304b"><h2>正在安全连接服务商…</h2><p>正在准备授权链接。此窗口会自动跳转，请不要关闭。</p></main>'}return popup};
  const authorize=async(connection:ToolConnection)=>{const popup=openOAuthWindow();setBusy(connection.id);setError('');try{const r=await api.post<{authorization:{authorization_url:string}}>(`/api/tool-connections/${connection.id}/authorize`);if(popup)popup.location.href=r.authorization.authorization_url;else window.location.assign(r.authorization.authorization_url);notify('正在跳转到服务商登录页，完成后会自动刷新。')}catch(e){popup?.close();setError((e as Error).message)}finally{setBusy('')}};
  const connect=async()=>{if(mode==='mcp'&&!schema){setBusy('connect');setError('');try{const found=await api.post<{name:string;schema:ConnectionSchema;oauth_callback_url:string}>('/api/tool-connections/mcp/probe',{url,market_slug:marketSlug});const detected={...found.schema,oauth_callback_url:found.oauth_callback_url};setSchema(detected);setConfiguration(Object.fromEntries(detected.fields.map(field=>[field.name,field.default||''])));if(!name&&found.name)setName(found.name);notify(detected.fields.length?'已识别连接配置，请填写下方字段后连接。':'已识别为免配置连接，请再次点击连接。')}catch(e){setError((e as Error).message)}finally{setBusy('')}return}const missing=(schema?.fields||[]).filter(field=>field.required&&!configuration[field.name]?.trim());if(mode==='mcp'&&missing.length){setError(`请填写：${missing.map(field=>field.label).join('、')}`);return}const popup=mode==='mcp'&&schema?.auth_type.startsWith('oauth')?openOAuthWindow():null;setBusy('connect');setError('');try{const r=mode==='mcp'?await api.post<{connection:ToolConnection;authorization?:{authorization_url:string}}>('/api/tool-connections/mcp',{url,name:name||'自定义 MCP',credential_env:credential,configuration,market_slug:marketSlug}):await api.post<{connection:ToolConnection}>('/api/tool-connections/openapi',{url,name:name||'OpenAPI 服务',credential_env:credential});const authorization=(r as {authorization?:{authorization_url:string}}).authorization;await Promise.all([reload(),load()]);setTab('installed');setExpanded([r.connection.id]);if(authorization?.authorization_url){if(popup)popup.location.href=authorization.authorization_url;else window.location.assign(authorization.authorization_url);notify('正在跳转到服务商登录页，完成授权后工具会自动同步。')}else{popup?.close();notify(`连接测试成功，发现 ${r.connection.tool_count} 个工具，请按需添加`)}setUrl('');setName('');setCredential('');setSchema(null);setConfiguration({});setMarketSlug('')}catch(e){popup?.close();setError((e as Error).message)}finally{setBusy('')}};
  return <div className="skill-drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="skill-drawer tool-drawer"><header><div><h2>添加工具</h2><p>从市场安装到工作区，再按需添加到当前智能体。</p></div><button aria-label="关闭" onClick={close}>×</button></header><div className="skill-drawer-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索工具或 MCP 服务"/></label></div><div className="skill-drawer-tabs tool-main-tabs"><button className={tab==='market'?'active':''} onClick={()=>setTab('market')}>市场</button><button className={tab==='installed'?'active':''} onClick={()=>setTab('installed')}>已安装 <b>{connections.length}</b></button><button className={tab==='custom'?'active':''} onClick={()=>setTab('custom')}>自定义</button></div>{error&&<div className="skill-drawer-error">{error}</div>}
    {tab==='market'&&<><div className="skill-categories">{([['all','全部'],['builtin','内置工具'],['mcp','MCP']] as const).map(([k,l])=><button className={source===k?'active':''} onClick={()=>setSource(k)} key={k}>{l}</button>)}</div><div className="tool-market-list">{(source==='all'||source==='builtin')&&builtins.map(t=><ToolRow key={t.id} tool={t} checked={selected.includes(t.id)} toggle={()=>toggle(t.id)}/>)}{marketRows.map(item=><article className="tool-service-card" key={item.slug}><div className="tool-service-head"><span className="tool-service-icon">⌁</span><div><h3>{item.name}</h3><p>{item.description}</p><small>{item.provider} · {item.category} · {item.tool_count?`${item.tool_count} 个工具`:'安装后配置服务'}</small></div><button disabled={busy===item.slug||item.installed} onClick={()=>install(item)}>{item.installed?'已安装':item.requires_configuration?'去配置':busy===item.slug?'安装中…':'安装'}</button></div><div className="tool-service-tags"><em className={item.availability}>{item.availability==='ready'?'已验证可用':'需要服务配置'}</em></div></article>)}{!builtins.length&&!marketRows.length&&<div className="skill-drawer-empty">没有匹配的市场工具</div>}</div></>}
    {tab==='installed'&&<div className="tool-installed-groups"><ServiceCard name="平台内置工具" type="BUILTIN" tools={builtins} selected={selected} expanded={expanded.includes('builtin')} open={()=>flip('builtin',expanded,setExpanded)} toggle={toggle} changeAll={changeAll}/>{installedRows.map(c=><ServiceCard key={c.id} name={c.name} type={c.type.toUpperCase()} status={c.status} tools={availableSet?c.tools.filter(t=>availableSet.has(t.id)):c.tools} selected={selected} expanded={expanded.includes(c.id)} open={()=>flip(c.id,expanded,setExpanded)} toggle={toggle} changeAll={changeAll} sync={c.type==='mcp'?()=>sync(c):undefined} authorize={c.type==='mcp'?()=>authorize(c):undefined} syncing={busy===c.id}/>)}</div>}
    {tab==='custom'&&<div className="skill-custom-import tool-custom"><div className="skill-import-modes"><button className={mode==='mcp'?'active':''} onClick={()=>{setMode('mcp');resetMcpDetection()}}>MCP 服务</button><button className={mode==='openapi'?'active':''} onClick={()=>{setMode('openapi');resetMcpDetection()}}>OpenAPI</button></div><label>连接名称<input value={name} onChange={e=>setName(e.target.value)} placeholder={mode==='mcp'?'企业 MCP 服务':'业务 OpenAPI'}/></label><label>{mode==='mcp'?'MCP HTTPS 地址':'OpenAPI 文档地址'}<input value={url} onChange={e=>{setUrl(e.target.value);if(mode==='mcp')resetMcpDetection()}} placeholder={mode==='mcp'?'https://example.com/mcp':'https://example.com/openapi.json'}/></label>{mode==='mcp'&&schema&&<div className="tool-schema"><b>{schema.auth_type==='none'?'无需认证':schema.auth_type==='oauth_dcr'?'将使用浏览器 OAuth 登录':schema.auth_type==='oauth_static'?'需要 OAuth 应用配置':'需要 API Key / Bearer Token'}</b><small>{schema.help_text}</small>{schema.oauth_callback_url&&<small>Google Cloud 的“已获授权的重定向 URI”填写：<code>{schema.oauth_callback_url}</code></small>}{schema.fields.map(field=><label key={field.name}>{field.label}{field.required?' *':''}<input type={field.type==='secret'?'password':'text'} value={configuration[field.name]||''} onChange={e=>setConfig(field.name,e.target.value)} placeholder={field.description||field.label}/><small>{field.description}{field.scope==='workspace'?'（工作区管理员配置一次即可）':''}</small></label>)}</div>}{mode==='openapi'&&<label>Bearer 凭据环境变量（可选）<input value={credential} onChange={e=>setCredential(e.target.value)} placeholder="EXTERNAL_TOOL_API_KEY"/><small>只保存后端环境变量名称，不保存密钥。</small></label>}{mode==='mcp'&&schema?.auth_type==='manual_bearer'&&<small>此处填写的是密钥本身，后端将加密保存；不会传给模型或回显。</small>}<button className="primary" disabled={busy==='connect'||!url.trim()} onClick={connect}>{busy==='connect'?'正在检测、授权或发现…':mode==='mcp'&&!schema?'检测 MCP 配置':schema?.fields.length?'保存并连接':'连接并安装'}</button></div>}</aside></div>;
}

function ToolRow({tool,checked,toggle}:{tool:Tool;checked:boolean;toggle:()=>void}){return <div className={`tool-market-row ${!tool.enabled?'disabled':''}`}><span className="tool-row-icon">⌕</span><span className="tool-row-copy"><b>{tool.display_name||tool.name}</b><small>{tool.description||'暂无描述'}</small></span><em>{toolSource(tool)==='builtin'?'内置':tool.category.toUpperCase()}</em><button disabled={!tool.enabled} className={checked?'selected':''} onClick={toggle}>{checked?'已添加':'添加'}</button></div>}
function ServiceCard({name,type,status,tools,selected,expanded,open,toggle,changeAll,sync,authorize,syncing}:{name:string;type:string;status?:string;tools:Tool[];selected:string[];expanded:boolean;open:()=>void;toggle:(id:string)=>void;changeAll:(tools:Tool[],add:boolean)=>void;sync?:()=>void;authorize?:()=>void;syncing?:boolean}){const usable=tools.filter(t=>t.enabled),count=usable.filter(t=>selected.includes(t.id)).length,all=usable.length>0&&count===usable.length;const state=status==='authorization_required'?'等待登录':status==='configuration_required'?'待配置':`${tools.length} 个工具`;return <article className="tool-service-card installed"><div className="tool-service-head"><button className="tool-expand" onClick={open}>{expanded?'⌄':'›'}</button><span className="tool-service-icon">⌁</span><div><h3>{name}</h3><small>{type} · {state} · 已添加 {count}/{usable.length}</small></div>{status==='authorization_required'&&authorize?<button onClick={authorize} disabled={syncing}>{syncing?'处理中…':'登录授权'}</button>:<button disabled={!usable.length} onClick={()=>changeAll(usable,!all)}>{all?'移除全部':'添加全部'}</button>}</div>{expanded&&<div className="tool-service-tools">{status==='authorization_required'&&sync&&<button className="tool-sync" onClick={sync} disabled={syncing}>授权完成后同步工具</button>}{tools.map(t=><ToolRow key={t.id} tool={t} checked={selected.includes(t.id)} toggle={()=>toggle(t.id)}/>)}{!tools.length&&<div className="skill-drawer-empty">{status==='authorization_required'?'请先点击“登录授权”，完成浏览器登录后工具会自动同步；未自动刷新时可点击“授权完成后同步工具”。':'该服务尚未发现工具，请先完成配置或同步'}</div>}</div>}</article>}
function flip(id:string,values:string[],set:(next:string[])=>void){set(values.includes(id)?values.filter(x=>x!==id):[...values,id])}
function matches(t:Tool,q:string){return `${t.display_name}${t.name}${t.description}`.toLowerCase().includes(q.toLowerCase())}
function toolSource(t:Tool){const s=String((t.metadata as any)?.source||'');if(s==='mcp'||t.category==='mcp')return'mcp';if(s==='openapi'||t.category==='openapi')return'openapi';return'builtin'}
