import { useEffect, useMemo, useState } from 'react';
import type { ApiClient } from './api';
import type { McpMarketItem, Tool, ToolConnection } from './types';
import './skill-drawer.css';
import './tool-drawer.css';

type Tab='market'|'installed'|'custom';
export function ToolDrawer({api,tools,selected,close,reload,toggle,changeMany,notify}:{api:ApiClient;tools:Tool[];selected:string[];close:()=>void;reload:()=>Promise<void>;toggle:(id:string)=>void;changeMany:(ids:string[],add:boolean)=>void;notify:(message:string,bad?:boolean)=>void}){
  const [tab,setTab]=useState<Tab>('market'),[source,setSource]=useState<'all'|'builtin'|'mcp'>('all'),[query,setQuery]=useState('');
  const [connections,setConnections]=useState<ToolConnection[]>([]),[market,setMarket]=useState<McpMarketItem[]>([]),[expanded,setExpanded]=useState<string[]>([]);
  const [mode,setMode]=useState<'mcp'|'openapi'>('mcp'),[url,setUrl]=useState(''),[name,setName]=useState(''),[credential,setCredential]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState('');
  const load=async()=>{const [a,b]=await Promise.all([api.get<ToolConnection[]>('/api/tool-connections'),api.get<McpMarketItem[]>('/api/marketplace/mcp')]);setConnections(a);setMarket(b)};
  useEffect(()=>{load().catch(e=>setError(e.message))},[]);
  const builtins=useMemo(()=>tools.filter(t=>toolSource(t)==='builtin'&&matches(t,query)),[tools,query]);
  const marketRows=useMemo(()=>market.filter(x=>(source==='all'||source==='mcp')&&`${x.name}${x.provider}${x.category}${x.description}`.toLowerCase().includes(query.toLowerCase())),[market,source,query]);
  const installedRows=useMemo(()=>connections.filter(x=>`${x.name}${x.type}${x.tools.map(t=>t.display_name).join('')}`.toLowerCase().includes(query.toLowerCase())),[connections,query]);
  const changeAll=(items:Tool[],add:boolean)=>changeMany(items.filter(t=>t.enabled).map(t=>t.id),add);
  const install=async(item:McpMarketItem)=>{if(item.requires_configuration){setTab('custom');setMode('mcp');setName(item.name);return}setBusy(item.slug);setError('');try{const r=await api.post<{connection:ToolConnection;message:string}>(`/api/marketplace/mcp/${item.slug}/install`);await Promise.all([reload(),load()]);setTab('installed');setExpanded([r.connection.id]);notify(r.message)}catch(e){setError((e as Error).message)}finally{setBusy('')}};
  const connect=async()=>{setBusy('connect');setError('');try{const r=mode==='mcp'?await api.post<{connection:ToolConnection}>('/api/tool-connections/mcp',{url,name:name||'自定义 MCP',credential_env:credential}):await api.post<{connection:ToolConnection}>('/api/tool-connections/openapi',{url,name:name||'OpenAPI 服务',credential_env:credential});await Promise.all([reload(),load()]);setTab('installed');setExpanded([r.connection.id]);notify(`连接测试成功，发现 ${r.connection.tool_count} 个工具，请按需添加`);setUrl('');setName('');setCredential('')}catch(e){setError((e as Error).message)}finally{setBusy('')}};
  return <div className="skill-drawer-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="skill-drawer tool-drawer"><header><div><h2>添加工具</h2><p>从市场安装到工作区，再按需添加到当前智能体。</p></div><button aria-label="关闭" onClick={close}>×</button></header><div className="skill-drawer-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索工具或 MCP 服务"/></label></div><div className="skill-drawer-tabs tool-main-tabs"><button className={tab==='market'?'active':''} onClick={()=>setTab('market')}>市场</button><button className={tab==='installed'?'active':''} onClick={()=>setTab('installed')}>已安装 <b>{connections.length}</b></button><button className={tab==='custom'?'active':''} onClick={()=>setTab('custom')}>自定义</button></div>{error&&<div className="skill-drawer-error">{error}</div>}
    {tab==='market'&&<><div className="skill-categories">{([['all','全部'],['builtin','内置工具'],['mcp','MCP']] as const).map(([k,l])=><button className={source===k?'active':''} onClick={()=>setSource(k)} key={k}>{l}</button>)}</div><div className="tool-market-list">{(source==='all'||source==='builtin')&&builtins.map(t=><ToolRow key={t.id} tool={t} checked={selected.includes(t.id)} toggle={()=>toggle(t.id)}/>)}{marketRows.map(item=><article className="tool-service-card" key={item.slug}><div className="tool-service-head"><span className="tool-service-icon">⌁</span><div><h3>{item.name}</h3><p>{item.description}</p><small>{item.provider} · {item.category} · {item.tool_count?`${item.tool_count} 个工具`:'安装后配置服务'}</small></div><button disabled={busy===item.slug||item.installed} onClick={()=>install(item)}>{item.installed?'已安装':item.requires_configuration?'去配置':busy===item.slug?'安装中…':'安装'}</button></div><div className="tool-service-tags"><em className={item.availability}>{item.availability==='ready'?'已验证可用':'需要服务配置'}</em></div></article>)}{!builtins.length&&!marketRows.length&&<div className="skill-drawer-empty">没有匹配的市场工具</div>}</div></>}
    {tab==='installed'&&<div className="tool-installed-groups"><ServiceCard name="平台内置工具" type="BUILTIN" tools={builtins} selected={selected} expanded={expanded.includes('builtin')} open={()=>flip('builtin',expanded,setExpanded)} toggle={toggle} changeAll={changeAll}/>{installedRows.map(c=><ServiceCard key={c.id} name={c.name} type={c.type.toUpperCase()} status={c.status} tools={c.tools} selected={selected} expanded={expanded.includes(c.id)} open={()=>flip(c.id,expanded,setExpanded)} toggle={toggle} changeAll={changeAll}/>)}</div>}
    {tab==='custom'&&<div className="skill-custom-import tool-custom"><div className="skill-import-modes"><button className={mode==='mcp'?'active':''} onClick={()=>setMode('mcp')}>MCP 服务</button><button className={mode==='openapi'?'active':''} onClick={()=>setMode('openapi')}>OpenAPI</button></div><label>连接名称<input value={name} onChange={e=>setName(e.target.value)} placeholder={mode==='mcp'?'企业 MCP 服务':'业务 OpenAPI'}/></label><label>{mode==='mcp'?'MCP HTTPS 地址':'OpenAPI 文档地址'}<input value={url} onChange={e=>setUrl(e.target.value)} placeholder={mode==='mcp'?'https://example.com/mcp':'https://example.com/openapi.json'}/></label><label>凭据环境变量<input value={credential} onChange={e=>setCredential(e.target.value)} placeholder="EXTERNAL_TOOL_API_KEY"/><small>只保存后端环境变量名称，不保存密钥。</small></label><button className="primary" disabled={busy==='connect'||!url.trim()} onClick={connect}>{busy==='connect'?'连接测试与发现中…':'测试连接并安装'}</button></div>}</aside></div>
}
function ToolRow({tool,checked,toggle}:{tool:Tool;checked:boolean;toggle:()=>void}){return <div className={`tool-market-row ${!tool.enabled?'disabled':''}`}><span><b>{tool.display_name||tool.name}</b><small>{tool.description||'暂无描述'}</small></span><em>{toolSource(tool)==='builtin'?'内置':tool.category.toUpperCase()}</em><button disabled={!tool.enabled} className={checked?'selected':''} onClick={toggle}>{checked?'已添加':'添加'}</button></div>}
function ServiceCard({name,type,status,tools,selected,expanded,open,toggle,changeAll}:{name:string;type:string;status?:string;tools:Tool[];selected:string[];expanded:boolean;open:()=>void;toggle:(id:string)=>void;changeAll:(tools:Tool[],add:boolean)=>void}){const usable=tools.filter(t=>t.enabled),count=usable.filter(t=>selected.includes(t.id)).length,all=usable.length>0&&count===usable.length;return <article className="tool-service-card installed"><div className="tool-service-head"><button className="tool-expand" onClick={open}>{expanded?'⌄':'›'}</button><span className="tool-service-icon">⌁</span><div><h3>{name}</h3><small>{type} · {status==='configuration_required'?'待配置':`${tools.length} 个工具`} · 已添加 {count}/{usable.length}</small></div><button disabled={!usable.length} onClick={()=>changeAll(usable,!all)}>{all?'移除全部':'添加全部'}</button></div>{expanded&&<div className="tool-service-tools">{tools.map(t=><ToolRow key={t.id} tool={t} checked={selected.includes(t.id)} toggle={()=>toggle(t.id)}/>)}{!tools.length&&<div className="skill-drawer-empty">该服务尚未发现工具，请先完成配置或同步</div>}</div>}</article>}
function flip(id:string,values:string[],set:(next:string[])=>void){set(values.includes(id)?values.filter(x=>x!==id):[...values,id])}
function matches(t:Tool,q:string){return `${t.display_name}${t.name}${t.description}`.toLowerCase().includes(q.toLowerCase())}
function toolSource(t:Tool){const s=String((t.metadata as any)?.source||'');if(s==='mcp'||t.category==='mcp')return'mcp';if(s==='openapi'||t.category==='openapi')return'openapi';return'builtin'}
