import { useEffect, useMemo, useRef, useState } from 'react';
import type { ApiClient } from './api';
import type { Agent, GraphData, Tool } from './types';

type Props={api:ApiClient;notify:(s:string,b?:boolean)=>void};
type Point={x:number;y:number};
const W=236,H=126;

export function VisualBuilder({api,notify}:Props){
 const [graph,setGraph]=useState<GraphData>({agents:[],connections:[]}); const [loading,setLoading]=useState(true);
 const [tools,setTools]=useState<Tool[]>([]); const [savingTools,setSavingTools]=useState(false);
 const [positions,setPositions]=useState<Record<string,Point>>(()=>JSON.parse(localStorage.getItem('graphPositions')||'{}'));
 const [selected,setSelected]=useState<Agent|null>(null),[linkFrom,setLinkFrom]=useState<string|null>(null),[creating,setCreating]=useState(false);
 const canvas=useRef<HTMLDivElement>(null); const drag=useRef<{id:string;dx:number;dy:number}|null>(null);
 const load=()=>Promise.all([api.get<GraphData>('/api/export'),api.get<Tool[]>('/api/tools')]).then(([g,t])=>{setGraph(g);setTools(t);setSelected(current=>current?g.agents.find(a=>a.id===current.id)||null:null);setLoading(false)}).catch(e=>{notify(e.message,true);setLoading(false)});
 useEffect(()=>{void load()},[api]);
 useEffect(()=>{const next={...positions};graph.agents.forEach((a,i)=>{if(!next[a.id])next[a.id]={x:70+(i%3)*310,y:95+Math.floor(i/3)*190}});if(JSON.stringify(next)!==JSON.stringify(positions))setPositions(next)},[graph.agents]);
 useEffect(()=>localStorage.setItem('graphPositions',JSON.stringify(positions)),[positions]);
 useEffect(()=>{const move=(e:PointerEvent)=>{if(!drag.current||!canvas.current)return;const r=canvas.current.getBoundingClientRect();setPositions(p=>({...p,[drag.current!.id]:{x:Math.max(20,e.clientX-r.left-drag.current!.dx),y:Math.max(68,e.clientY-r.top-drag.current!.dy)}}))};const up=()=>drag.current=null;window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[]);
 const entry=(graph as any).entry as string|undefined;
 const connect=async(target:string)=>{if(!linkFrom||linkFrom===target){setLinkFrom(null);return}try{await api.post('/api/connections',{source_id:linkFrom,target_id:target,conditional:false});notify('连线已创建');setLinkFrom(null);load()}catch(e){notify((e as Error).message,true)}};
 const removeEdge=async(source:string,target:string)=>{try{await api.delete('/api/connections',{source_id:source,target_id:target});notify('连线已删除');load()}catch(e){notify((e as Error).message,true)}};
 const create=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/api/agents',{name:f.get('name'),model:f.get('model'),description:f.get('description'),sys_prompt:f.get('sys_prompt'),config:{}});setCreating(false);notify('Agent 已创建');load()}catch(e){notify((e as Error).message,true)}};
 const selectedToolIds=useMemo(()=>Array.isArray(selected?.config?.tool_ids)?selected.config.tool_ids.filter((id):id is string=>typeof id==='string'):[],[selected]);
 const toggleTool=async(toolId:string)=>{if(!selected||savingTools)return;const next=selectedToolIds.includes(toolId)?selectedToolIds.filter(id=>id!==toolId):[...selectedToolIds,toolId];setSavingTools(true);try{const updated=await api.put<Agent>(`/api/agents/${selected.id}`,{config:{...selected.config,tool_ids:next}});setSelected(updated);setGraph(g=>({...g,agents:g.agents.map(a=>a.id===updated.id?updated:a)}));notify('工具授权已保存')}catch(e){notify((e as Error).message,true)}finally{setSavingTools(false)}};
 return <div className="visual-builder">
  <div className="builder-toolbar"><div><b>工作流草稿</b><span>{graph.agents.length} 个 Agent · {graph.connections.length} 条路径</span></div>{linkFrom&&<div className="link-hint">选择目标节点完成连线 · Esc 取消</div>}<button onClick={()=>setCreating(true)} className="primary">＋ 添加 Agent</button></div>
  <div className="visual-body"><div className="flow-canvas" ref={canvas} onClick={()=>linkFrom&&setLinkFrom(null)}>
   <div className="canvas-grid"/><svg className="edge-layer"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{graph.connections.filter(c=>!c.conditional&&positions[c.source]&&(c.target==='END'||positions[c.target])).map((c,i)=>{const a=positions[c.source],b=c.target==='END'?{x:a.x+W+90,y:a.y}:positions[c.target];const x1=a.x+W,y1=a.y+H/2,x2=b.x,y2=b.y+H/2,curve=Math.max(60,Math.abs(x2-x1)*.45);return <g key={`${c.source}-${c.target}-${i}`} onDoubleClick={()=>removeEdge(c.source,c.target)}><path className="edge-hit" d={`M${x1},${y1} C${x1+curve},${y1} ${x2-curve},${y2} ${x2},${y2}`}/><path className="edge" markerEnd="url(#arrow)" d={`M${x1},${y1} C${x1+curve},${y1} ${x2-curve},${y2} ${x2},${y2}`}/></g>})}</svg>
   {graph.agents.map(a=>{const p=positions[a.id]||{x:40,y:80};return <div className={`flow-node ${entry===a.id?'entry':''} ${selected?.id===a.id?'selected':''}`} style={{transform:`translate(${p.x}px,${p.y}px)`}} key={a.id} onClick={e=>{e.stopPropagation();setSelected(a)}} onPointerDown={e=>{const target=e.target as HTMLElement;if(target.classList.contains('port'))return;const rect=e.currentTarget.getBoundingClientRect();drag.current={id:a.id,dx:e.clientX-rect.left,dy:e.clientY-rect.top}}}><button title="连接到此节点" className="port input" onClick={e=>{e.stopPropagation();connect(a.id)}}/><div className="node-title"><span>AI</span><div><b>{a.name}</b><small>{a.model||'自动选择模型'}</small></div></div><p>{a.description||'未设置职责说明'}</p><footer><em>{a.children?.length||0} 子 Agent</em><button title="从此节点拉出连接" className={`port output ${linkFrom===a.id?'active':''}`} onClick={e=>{e.stopPropagation();setLinkFrom(a.id)}}/></footer></div>})}
   {!loading&&!graph.agents.length&&<div className="flow-empty"><b>从一个 Agent 开始</b><span>创建节点后，从右侧端口点击，再选择目标节点完成连线。</span><button className="primary" onClick={()=>setCreating(true)}>创建 Agent</button></div>}
  </div><div className="flow-inspector">{selected?<><div className="inspector-agent"><span>AI</span><div><h3>{selected.name}</h3><small>{selected.id}</small></div></div><h4>职责</h4><p>{selected.description||'未填写'}</p><h4>系统提示词</h4><pre>{selected.sys_prompt||'未设置'}</pre><h4>运行设置</h4><div className="ins-row"><span>模型</span><b>{selected.model||'自动调度'}</b></div><div className="ins-row"><span>工具授权</span><b>{selectedToolIds.length} 个</b></div><div className="tool-bind-list">{tools.length?tools.map(tool=><label className={!tool.enabled?'disabled':''} key={tool.id}><input type="checkbox" disabled={!tool.enabled||savingTools} checked={selectedToolIds.includes(tool.id)} onChange={()=>toggleTool(tool.id)}/><span><b>{tool.display_name||tool.name}</b><small>{tool.enabled?(tool.description||'无描述'):'已停用'}</small></span></label>):<small>工具目录为空，请先到“工具目录”登记工具。</small>}</div><p className="binding-note">授权只决定该 Agent 可见哪些工具；实际权限由后端执行器的白名单适配器控制，描述文字本身不会打开电脑权限。</p><div className="ins-actions"><button onClick={async()=>{await api.post('/api/graph/entry',{agent_id:selected.id});notify('入口已设置');load()}}>设为入口</button><button className="danger" onClick={async()=>{if(!confirm('删除该 Agent 及相关连线？'))return;await api.delete(`/api/agents/${selected.id}`);setSelected(null);load()}}>删除</button></div></>:<div className="ins-empty">选择节点查看配置<br/><small>双击连线可删除</small></div>}</div></div>
  {creating&&<div className="overlay"><div className="modal"><div className="modal-head"><h2>添加 Agent 节点</h2><button onClick={()=>setCreating(false)}>×</button></div><form className="form-grid" onSubmit={create}><label><span>名称</span><input name="name" required/></label><label><span>模型</span><input name="model" placeholder="留空自动调度"/></label><label className="span"><span>职责描述</span><input name="description"/></label><label className="span"><span>系统提示词</span><textarea name="sys_prompt" rows={7}/></label><div className="form-actions span"><button type="button" onClick={()=>setCreating(false)}>取消</button><button className="primary">创建节点</button></div></form></div></div>}
 </div>
}
