// 可视化工作流画布：Agent 与受控逻辑节点共用同一张可执行图。
import { useEffect, useRef, useState } from 'react';
import type { ApiClient } from './api';
import type { Agent, GraphConnection, GraphData, LogicNodeKind, Tool } from './types';

type Props={api:ApiClient;notify:(s:string,b?:boolean)=>void};
type Point={x:number;y:number};
const W=236,H=126;
const kinds=[
 ['agent','Agent','AI','调用模型、技能和已授权工具'],['script','脚本','</>','安全模板转换'],['condition','条件判断','?','依据状态字段比较分支'],
 ['intent','意图分类','◎','依据关键词分类路由'],['loop','循环','↻','受上限保护的循环'],['batch','批处理','▤','逐项处理输入列表'],
] as const;
const meta=(kind:LogicNodeKind)=>kinds.find(x=>x[0]===kind) || kinds[0];
const kindOf=(a:Agent):LogicNodeKind=>kinds.some(x=>x[0]===a.config?.node_kind)?a.config.node_kind as LogicNodeKind:'agent';
const base=(kind:LogicNodeKind):Record<string,unknown>=>({node_kind:kind,...(kind==='condition'?{field:'input',operator:'contains',value:'',route_key:'route',true_route:'true',false_route:'false'}:{}),...(kind==='intent'?{route_key:'route',intents:[{route:'research',keywords:['研究','调研']}],default_route:'default'}:{}),...(kind==='loop'?{route_key:'route',max_iterations:3,continue_route:'continue',done_route:'done'}:{}),...(kind==='batch'?{route_key:'route',items_path:'input.items',item_key:'batch_item',next_route:'next',done_route:'done'}:{}),...(kind==='script'?{route_key:'route',template:'{{input}}',route:'next',output_key:'script_output'}:{})});
const routes=(a:Agent):string[]=>{const c=a.config||{};if(kindOf(a)==='condition')return [String(c.true_route||'true'),String(c.false_route||'false')];if(kindOf(a)==='intent')return [...(Array.isArray(c.intents)?c.intents:[]).map((x:any)=>String(x?.route||'')).filter(Boolean),String(c.default_route||'default')];if(kindOf(a)==='loop')return [String(c.continue_route||'continue'),String(c.done_route||'done')];if(kindOf(a)==='batch')return [String(c.next_route||'next'),String(c.done_route||'done')];if(kindOf(a)==='script')return [String(c.route||'next'),String(c.error_route||'error')];return []};

export function VisualBuilder({api,notify}:Props){
 const [graph,setGraph]=useState<GraphData>({agents:[],connections:[]}); const [tools,setTools]=useState<Tool[]>([]);const [loading,setLoading]=useState(true);const [positions,setPositions]=useState<Record<string,Point>>(()=>JSON.parse(localStorage.getItem('graphPositions')||'{}'));const [selected,setSelected]=useState<Agent|null>(null);const [linkFrom,setLinkFrom]=useState<string|null>(null);const [creating,setCreating]=useState(false);const [routing,setRouting]=useState<Agent|null>(null);const [saving,setSaving]=useState(false);const canvas=useRef<HTMLDivElement>(null);const drag=useRef<{id:string;dx:number;dy:number}|null>(null);
 const load=()=>Promise.all([api.get<GraphData>('/api/export'),api.get<Tool[]>('/api/tools')]).then(([g,t])=>{setGraph(g);setTools(t);setSelected(current=>current?g.agents.find(a=>a.id===current.id)||null:null);setLoading(false)}).catch(e=>{notify(e.message,true);setLoading(false)});
 useEffect(()=>{void load()},[api]);
 useEffect(()=>{const next={...positions};graph.agents.forEach((a,i)=>{if(!next[a.id])next[a.id]={x:70+(i%3)*310,y:95+Math.floor(i/3)*190}});if(JSON.stringify(next)!==JSON.stringify(positions))setPositions(next)},[graph.agents]);
 useEffect(()=>localStorage.setItem('graphPositions',JSON.stringify(positions)),[positions]);
 useEffect(()=>{const move=(event:PointerEvent)=>{if(!drag.current||!canvas.current)return;const r=canvas.current.getBoundingClientRect(),d=drag.current;setPositions(old=>({...old,[d.id]:{x:Math.max(20,event.clientX-r.left-d.dx),y:Math.max(68,event.clientY-r.top-d.dy)}}))};const up=()=>{drag.current=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[]);
 const saveConfig=async(config:Record<string,unknown>)=>{if(!selected)return;setSaving(true);try{const updated=await api.put<Agent>(`/api/agents/${selected.id}`,{config});setSelected(updated);setGraph(g=>({...g,agents:g.agents.map(a=>a.id===updated.id?updated:a)}));notify('节点配置已保存')}catch(e){notify((e as Error).message,true)}finally{setSaving(false)}};
 const makeDirect=async(target:string)=>{if(!linkFrom||linkFrom===target){setLinkFrom(null);return}try{await api.post('/api/connections',{source_id:linkFrom,target_id:target,conditional:false,edge_type:'direct'});setLinkFrom(null);notify('直连边已创建');load()}catch(e){notify((e as Error).message,true)}};
 const remove=async(c:GraphConnection)=>{try{await api.delete('/api/connections',{source_id:c.source,target_id:c.target,conditional:!!c.conditional});notify('连线已删除');load()}catch(e){notify((e as Error).message,true)}};
 const create=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),kind=String(form.get('node_kind')||'agent') as LogicNodeKind;let config=base(kind);try{const raw=String(form.get('config')||'').trim();if(raw)config={...config,...JSON.parse(raw)}}catch{notify('高级配置必须是合法 JSON',true);return}try{await api.post('/api/agents',{name:form.get('name'),model:form.get('model'),description:form.get('description'),sys_prompt:form.get('sys_prompt'),config});setCreating(false);notify('节点已创建');load()}catch(e){notify((e as Error).message,true)}};
 const shownEdges=graph.connections.flatMap(c=>c.conditional?Object.entries(c.path_map||{}).map(([label,target])=>({connection:c,target,label})):([{connection:c,target:c.target,label:''}]));
  return <div className="visual-builder"><div className="builder-toolbar"><div><b>工作流编排</b><span>{graph.agents.length} 个节点 · {graph.connections.length} 条路径 · 支持分支、循环、批处理</span></div>{linkFrom&&<div className="link-hint">点击另一节点左端口创建直连边</div>}<button className="primary" onClick={()=>setCreating(true)}>＋ 添加节点</button></div><div className="visual-body"><div className="flow-canvas" ref={canvas} onClick={()=>linkFrom&&setLinkFrom(null)}><div className="canvas-grid"/><EdgeLayer items={shownEdges} positions={positions} onRemove={remove}/>{graph.agents.map(agent=><NodeCard key={agent.id} agent={agent} position={positions[agent.id]||{x:40,y:80}} entry={graph.entry===agent.id} selected={selected?.id===agent.id} linking={linkFrom===agent.id} onSelect={()=>setSelected(agent)} onInput={()=>void makeDirect(agent.id)} onOutput={()=>setLinkFrom(agent.id)} onDrag={(event)=>{if((event.target as HTMLElement).classList.contains('port'))return;const r=event.currentTarget.getBoundingClientRect();drag.current={id:agent.id,dx:event.clientX-r.left,dy:event.clientY-r.top}}}/>) }{!loading&&!graph.agents.length&&<div className="flow-empty"><b>从一个节点开始</b><span>可选择 Agent、条件判断、意图分类、循环或批处理。</span><button className="primary" onClick={()=>setCreating(true)}>创建节点</button></div>}</div><Inspector agent={selected} tools={tools} saving={saving} onSave={saveConfig} onRouting={()=>selected&&setRouting(selected)} onEntry={async()=>{if(selected){await api.post('/api/graph/entry',{agent_id:selected.id});notify('入口已设置');load()}}} onDelete={async()=>{if(selected&&confirm('删除该节点及相关连线？')){await api.delete(`/api/agents/${selected.id}`);setSelected(null);load()}}}/></div>{creating&&<CreateModal close={()=>setCreating(false)} submit={create}/>} {routing&&<RouteModal agent={routing} agents={graph.agents} existing={graph.connections.find(c=>c.conditional&&c.source===routing.id)} api={api} notify={notify} done={()=>{setRouting(null);load()}}/>}</div>;
}

function EdgeLayer({items,positions,onRemove}:{items:Array<{connection:GraphConnection;target:string;label:string}>;positions:Record<string,Point>;onRemove:(c:GraphConnection)=>void}){return <svg className="edge-layer"><defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>{items.map(({connection,target,label},i)=>{if(!positions[connection.source]||(target!=='END'&&!positions[target]))return null;const a=positions[connection.source],b=target==='END'?{x:a.x+W+90,y:a.y+H/2}:positions[target],x1=a.x+W,y1=a.y+H/2,x2=b.x,y2=b.y+H/2,q=Math.max(60,Math.abs(x2-x1)*.45),d=`M${x1},${y1} C${x1+q},${y1} ${x2-q},${y2} ${x2},${y2}`;return <g key={i} onDoubleClick={()=>onRemove(connection)}><path className="edge-hit" d={d}/><path className={`edge ${connection.conditional?'conditional-edge':''} ${connection.edge_type||''}`} markerEnd="url(#arrow)" d={d}/>{label&&<text className="edge-label" x={(x1+x2)/2} y={(y1+y2)/2-7}>{label}</text>}</g>})}</svg>}
function NodeCard({agent,position,entry,selected,linking,onSelect,onInput,onOutput,onDrag}:{agent:Agent;position:Point;entry:boolean;selected:boolean;linking:boolean;onSelect:()=>void;onInput:()=>void;onOutput:()=>void;onDrag:(e:React.PointerEvent<HTMLDivElement>)=>void}){const kind=kindOf(agent),info=meta(kind);return <div className={`flow-node ${kind!=='agent'?'logic-node '+kind:''} ${entry?'entry':''} ${selected?'selected':''}`} style={{transform:`translate(${position.x}px,${position.y}px)`}} onClick={e=>{e.stopPropagation();onSelect()}} onPointerDown={onDrag}><button className="port input" onClick={e=>{e.stopPropagation();onInput()}}/><div className="node-title"><span>{info[2]}</span><div><b>{agent.name}</b><small>{info[1]}{kind==='agent'&&` · ${agent.model||'自动模型'}`}</small></div></div><p>{agent.description||info[3]}</p><footer><em>{kind==='agent'?`${agent.children?.length||0} 子 Agent`:`${routes(agent).length} 个出口`}</em><button className={`port output ${linking?'active':''}`} onClick={e=>{e.stopPropagation();onOutput()}}/></footer></div>}
function Inspector({agent,tools,saving,onSave,onRouting,onEntry,onDelete}:{agent:Agent|null;tools:Tool[];saving:boolean;onSave:(v:Record<string,unknown>)=>void;onRouting:()=>void;onEntry:()=>void;onDelete:()=>void}){const [text,setText]=useState('');useEffect(()=>setText(agent?JSON.stringify(agent.config,null,2):''),[agent?.id]);if(!agent)return <div className="flow-inspector"><div className="ins-empty">选择节点查看配置<br/><small>拖动节点布局；双击边删除</small></div></div>;const kind=kindOf(agent),info=meta(kind),toolIds=Array.isArray(agent.config.tool_ids)?agent.config.tool_ids.filter((x):x is string=>typeof x==='string'):[];return <div className="flow-inspector"><div className="inspector-agent"><span>{info[2]}</span><div><h3>{agent.name}</h3><small>{info[1]} · {agent.id}</small></div></div><h4>节点说明</h4><p>{agent.description||'未填写'}</p>{kind==='agent'?<><h4>系统提示词</h4><pre>{agent.sys_prompt||'未设置'}</pre><h4>工具授权</h4><div className="tool-bind-list">{tools.map(t=><label key={t.id} className={!t.enabled?'disabled':''}><input type="checkbox" disabled={!t.enabled||saving} checked={toolIds.includes(t.id)} onChange={()=>onSave({...agent.config,tool_ids:toolIds.includes(t.id)?toolIds.filter(x=>x!==t.id):[...toolIds,t.id]})}/><span><b>{t.display_name||t.name}</b><small>{t.description||'无描述'}</small></span></label>)}</div></>:<><h4>逻辑配置</h4><textarea className="logic-json" rows={10} value={text} onChange={e=>setText(e.target.value)}/><button disabled={saving} onClick={()=>{try{onSave({...JSON.parse(text),node_kind:kind})}catch{alert('请输入合法 JSON 配置')}}}>保存逻辑配置</button><h4>逻辑路由</h4><p className="binding-note">按路由值选目标；循环和批处理有运行时上限保护。</p><button onClick={onRouting}>配置条件边</button></>}<div className="ins-actions"><button onClick={onEntry}>设为入口</button><button className="danger" onClick={onDelete}>删除</button></div></div>}
function CreateModal({close,submit}:{close:()=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){const [kind,setKind]=useState<LogicNodeKind>('agent');return <div className="overlay"><div className="modal"><div className="modal-head"><h2>添加工作流节点</h2><button onClick={close}>×</button></div><form className="form-grid" onSubmit={submit}><label><span>节点类型</span><select name="node_kind" value={kind} onChange={e=>setKind(e.target.value as LogicNodeKind)}>{kinds.map(k=><option key={k[0]} value={k[0]}>{k[2]} {k[1]}</option>)}</select></label><label><span>名称</span><input name="name" required/></label><label><span>模型</span><input name="model" disabled={kind!=='agent'} placeholder="仅 Agent 使用"/></label><label className="span"><span>职责描述</span><input name="description" placeholder={meta(kind)[3]}/></label>{kind==='agent'&&<label className="span"><span>系统提示词</span><textarea name="sys_prompt" rows={5}/></label>}<label className="span"><span>高级配置（JSON，可选）</span><textarea name="config" rows={6} placeholder={JSON.stringify(base(kind),null,2)}/></label><div className="form-actions span"><button type="button" onClick={close}>取消</button><button className="primary">创建节点</button></div></form></div></div>}
function RouteModal({agent,agents,existing,api,notify,done}:{agent:Agent;agents:Agent[];existing?:GraphConnection;api:ApiClient;notify:(s:string,b?:boolean)=>void;done:()=>void}){const values=routes(agent),[map,setMap]=useState<Record<string,string>>(()=>existing?.path_map||Object.fromEntries(values.map(x=>[x,'END'])));const save=async()=>{try{if(existing)await api.delete('/api/connections',{source_id:agent.id,target_id:'<conditional>',conditional:true});const kind=kindOf(agent);await api.post('/api/connections',{source_id:agent.id,target_id:'<conditional>',conditional:true,condition_key:String(agent.config.route_key||'route'),path_map:map,edge_type:kind==='intent'?'intent':kind==='loop'?'loop':kind==='batch'?'batch':'condition'});notify('条件路由已保存');done()}catch(e){notify((e as Error).message,true)}};return <div className="overlay"><div className="modal route-modal"><div className="modal-head"><h2>配置 {agent.name} 的路由</h2><button onClick={done}>×</button></div><p>运行时读取 <code>{String(agent.config.route_key||'route')}</code> 决定下一节点。</p>{values.map(value=><label className="route-row" key={value}><span>{value}</span><select value={map[value]||'END'} onChange={e=>setMap(v=>({...v,[value]:e.target.value}))}><option value="END">END（结束）</option>{agents.filter(a=>a.id!==agent.id).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}<div className="form-actions"><button onClick={done}>取消</button><button className="primary" onClick={()=>void save()}>保存路由</button></div></div></div>}
