import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, ReactFlowProvider, addEdge, applyEdgeChanges, applyNodeChanges, type Connection, type Edge, type EdgeChange, type Node, type NodeChange, type ReactFlowInstance, type Viewport } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import type { ApiClient } from './api';
import type { Application, Json, Run, Skill, Tool, Workflow } from './types';
import './workflow-editor.css';
import './workflow-editor-isolated.css';

type Resource={id:string;name:string;description:string;status:string};
type FlowData={label:string;kind:string;description:string;config:Record<string,any>;model?:string;sys_prompt?:string};
type FlowNode=Node<FlowData>;
type Snapshot={nodes:FlowNode[];edges:Edge[]};
type Props={appId:string;api:ApiClient;notify:(s:string,b?:boolean)=>void;back:()=>void};
const catalog=[
 {group:'基础',items:[['llm','大模型','✦'],['knowledge','知识库','▤']]},
 {group:'工具',items:[['tool','工具','⌁']]},
 {group:'智能体',items:[['agent','智能体','AI']]},
 {group:'逻辑',items:[['condition','条件判断','◇'],['intent','意图分类','◎'],['script','脚本','</>'],['loop','循环','↻'],['batch','批处理','▦']]},
] as const;
const colors:Record<string,string>={start:'#7568ee',end:'#44516d',llm:'#7164ef',knowledge:'#7267ee',tool:'#45a5e6',agent:'#936af0',condition:'#ed9843',intent:'#ef8f45',script:'#e58c3f',loop:'#e17d3d',batch:'#d87942'};

export function WorkflowEditor(props:Props){return <ReactFlowProvider><WorkflowEditorInner {...props}/></ReactFlowProvider>}
function WorkflowEditorInner({appId,api,notify,back}:Props){
 const [app,setApp]=useState<Application|null>(null),[workflow,setWorkflow]=useState<Workflow|null>(null),[nodes,setNodes]=useState<FlowNode[]>([]),[edges,setEdges]=useState<Edge[]>([]),[saved,setSaved]=useState(''),[selected,setSelected]=useState<string>('');
 const [tools,setTools]=useState<Tool[]>([]),[skills,setSkills]=useState<Skill[]>([]),[knowledge,setKnowledge]=useState<Resource[]>([]),[memories,setMemories]=useState<Resource[]>([]),[search,setSearch]=useState('');
 const [instance,setInstance]=useState<ReactFlowInstance<FlowNode,Edge>|null>(null),[saving,setSaving]=useState(false),[publishing,setPublishing]=useState(false),[testing,setTesting]=useState(false),[testOpen,setTestOpen]=useState(false),[testInput,setTestInput]=useState('{"input":"请开始执行工作流"}'),[testRun,setTestRun]=useState<Run|null>(null);
 const history=useRef<Snapshot[]>([]),future=useRef<Snapshot[]>([]),viewport=useRef<Viewport>({x:0,y:0,zoom:1}),stream=useRef<EventSource|null>(null);
 const selectedNode=nodes.find(n=>n.id===selected)||null;
 const serialized=useMemo(()=>JSON.stringify({nodes:nodes.map(n=>({id:n.id,position:n.position,data:n.data})),edges:edges.map(e=>({source:e.source,target:e.target,route:e.data?.route||''}))}),[nodes,edges]);
 const dirty=Boolean(saved&&serialized!==saved);
 useEffect(()=>{let active=true;Promise.all([api.get<Application&{workflow:Workflow}>(`/api/apps/${appId}`),api.get<Tool[]>('/api/tools'),api.get<Skill[]>('/api/skills'),api.get<Resource[]>('/api/resources/knowledge-bases'),api.get<Resource[]>('/api/memory-banks')]).then(([value,t,s,k,m])=>{if(!active)return;const wf=value.workflow;const converted=fromWorkflow(wf);setApp(value);setWorkflow(wf);setNodes(converted.nodes);setEdges(converted.edges);setSaved(JSON.stringify({nodes:converted.nodes.map(n=>({id:n.id,position:n.position,data:n.data})),edges:converted.edges.map(e=>({source:e.source,target:e.target,route:e.data?.route||''}))}));setTools(t);setSkills(s);setKnowledge(k);setMemories(m);viewport.current=((wf.metadata as any)?.editor?.viewport)||viewport.current}).catch(e=>notify((e as Error).message,true));return()=>{active=false;stream.current?.close()}},[appId,api]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',guard);return()=>removeEventListener('beforeunload',guard)},[dirty]);
 const remember=()=>{history.current.push({nodes:structuredClone(nodes),edges:structuredClone(edges)});if(history.current.length>50)history.current.shift();future.current=[]};
 const undo=()=>{const previous=history.current.pop();if(!previous)return;future.current.push({nodes,edges});setNodes(previous.nodes);setEdges(previous.edges)};
 const redo=()=>{const next=future.current.pop();if(!next)return;history.current.push({nodes,edges});setNodes(next.nodes);setEdges(next.edges)};
 const onNodesChange=useCallback((changes:NodeChange<FlowNode>[])=>setNodes(current=>applyNodeChanges(changes,current)),[]);
 const onEdgesChange=useCallback((changes:EdgeChange<Edge>[])=>setEdges(current=>applyEdgeChanges(changes,current)),[]);
 const onConnect=useCallback((connection:Connection)=>{if(!connection.source||!connection.target||connection.source===connection.target)return;const source=nodes.find(n=>n.id===connection.source),target=nodes.find(n=>n.id===connection.target);if(source?.data.kind==='end'||target?.data.kind==='start'||edges.some(e=>e.source===connection.source&&e.target===connection.target)){notify('该连线不符合端口规则或已经存在',true);return}remember();const routes=nodeRoutes(source);const used=edges.filter(e=>e.source===connection.source).map(e=>String(e.data?.route||''));const route=routes.find(r=>!used.includes(r))||'';setEdges(current=>addEdge({...connection,id:`edge-${crypto.randomUUID()}`,type:'smoothstep',label:route,data:{route}},current))},[nodes,edges]);
 const drop=(event:React.DragEvent)=>{event.preventDefault();const kind=event.dataTransfer.getData('application/workflow-node');if(!kind||!instance)return;remember();const position=instance.screenToFlowPosition({x:event.clientX,y:event.clientY});const index=nodes.filter(n=>n.data.kind===kind).length+1;const label=`${kindLabel(kind)}${index}`;setNodes(current=>[...current,{id:`node-${crypto.randomUUID()}`,type:'workflow',position,data:{label,kind,description:kindHint(kind),config:defaults(kind)},draggable:true}])};
 const updateNode=(patch:Partial<FlowData>)=>{if(!selectedNode)return;remember();setNodes(current=>current.map(n=>n.id===selectedNode.id?{...n,data:{...n.data,...patch}}:n))};
 const removeSelected=()=>{if(!selectedNode||['start','end'].includes(selectedNode.data.kind))return;remember();setNodes(current=>current.filter(n=>n.id!==selectedNode.id));setEdges(current=>current.filter(e=>e.source!==selectedNode.id&&e.target!==selectedNode.id));setSelected('')};
 const errors=()=>validate(nodes,edges);
 const save=async()=>{if(!workflow||!app)return;const problem=errors();if(problem.length){notify(problem[0],true);return}setSaving(true);try{const payload=toWorkflow(nodes,edges);const metadata={...(workflow.metadata||{}),editor:{positions:Object.fromEntries(nodes.map(n=>[n.id,n.position])),viewport:viewport.current}};const updated=await api.put<Workflow>(`/api/workflows/${workflow.id}`,{name:app.name,description:app.description,tags:['workflow','application'],metadata,graph:payload});setWorkflow(updated);setSaved(serialized);notify('工作流草稿已保存')}catch(e){notify((e as Error).message,true)}finally{setSaving(false)}};
 const publish=async()=>{if(dirty)return;setPublishing(true);try{const value=await api.post<Application>(`/api/apps/${appId}/publish`);setApp(value);notify('工作流应用已发布')}catch(e){notify((e as Error).message,true)}finally{setPublishing(false)}};
 const test=async()=>{if(dirty){notify('请先保存工作流',true);return}try{const input=JSON.parse(testInput);setTesting(true);const run=await api.post<Run>(`/api/apps/${appId}/runs`,{input,recursion_limit:50});setTestRun(run);const source=new EventSource(`${api.baseUrl.replace(/\/$/,'')}/api/runs/${run.id}/events?after=${run.events?.length||0}&access_token=${encodeURIComponent(api.getAuthToken())}`);stream.current=source;source.addEventListener('run_event',e=>{const event=JSON.parse((e as MessageEvent).data);setTestRun(current=>current?{...current,status:'running',events:[...(current.events||[]),event]}:current)});source.addEventListener('run_completed',async()=>{source.close();setTestRun(await api.get<Run>(`/api/runs/${run.id}`));setTesting(false)});source.onerror=()=>{source.close();setTesting(false);notify('测试连接已中断',true)}}catch(e){setTesting(false);notify((e as Error).message,true)}};
 const approve=async(sequence:number,approved:boolean)=>{if(!testRun)return;try{await api.post(`/api/runs/${testRun.id}/approvals/${sequence}/${approved?'approve':'reject'}`,{reason:approved?'用户批准':'用户拒绝'});setTestRun(await api.get<Run>(`/api/runs/${testRun.id}`));notify(approved?'已批准工具调用':'已拒绝工具调用')}catch(e){notify((e as Error).message,true)}};
 const leave=()=>{if(dirty&&!confirm('工作流尚未保存，确定离开吗？'))return;back()};
 if(!app||!workflow)return <div className="workflow-loading"><span className="spinner"/>正在加载工作流…</div>;
 return <div className="workflow-editor"><header className="workflow-top"><div><button onClick={leave}>←</button><span className="workflow-logo">⌘</span><b>{app.name}</b><em>{app.status==='published'?'已发布':'草稿'}</em>{dirty&&<i>未保存</i>}</div><nav><strong>画布配置</strong><span>发布渠道</span></nav><div><button disabled>观测</button><button disabled>版本管理</button><button onClick={()=>setTestOpen(true)} disabled={dirty}>▷ 测试</button><button onClick={save} disabled={!dirty||saving}>{saving?'保存中…':'保存'}</button><button className="primary" onClick={publish} disabled={dirty||publishing}>{publishing?'发布中…':'发布'}</button></div></header>
  <main className="workflow-body"><aside className="node-library"><h2>节点管理</h2><div className="node-tabs"><b>节点库</b><span>当前</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索节点名称"/>{catalog.map(group=><section key={group.group}><small>{group.group}</small>{group.items.filter(item=>item[1].includes(search)).map(item=><div draggable onDragStart={e=>{e.dataTransfer.setData('application/workflow-node',item[0]);e.dataTransfer.effectAllowed='move'}} className="library-node" key={item[0]}><i style={{background:colors[item[0]]}}>{item[2]}</i><span><b>{item[1]}</b><small>{kindHint(item[0])}</small></span></div>)}</section>)}</aside>
   <section className="workflow-canvas" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={drop}><div className="canvas-actions"><button onClick={undo} disabled={!history.current.length}>↶</button><button onClick={redo} disabled={!future.current.length}>↷</button></div><ReactFlow<FlowNode,Edge> nodes={nodes} edges={edges} nodeTypes={{workflow:WorkflowNode}} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeDragStart={remember} onConnect={onConnect} onNodeClick={(_,node)=>setSelected(node.id)} onPaneClick={()=>setSelected('')} onInit={setInstance} onMoveEnd={(_,v)=>viewport.current=v} defaultViewport={viewport.current} fitView><Background gap={18} size={1}/><Controls/><MiniMap nodeColor={n=>colors[(n.data as FlowData).kind]||'#777'}/></ReactFlow></section>
   {selectedNode&&<aside className="workflow-inspector open"><button className="workflow-inspector-close" onClick={()=>setSelected('')} aria-label="关闭节点配置">×</button><NodeInspector node={selectedNode} tools={tools} skills={skills} knowledge={knowledge} memories={memories} update={updateNode} remove={removeSelected}/></aside>}
  </main>{testOpen&&<TestDrawer close={()=>!testing&&setTestOpen(false)} input={testInput} setInput={setTestInput} run={testRun} testing={testing} test={test} approve={approve}/>}</div>
}

function WorkflowNode({data,selected}:{data:FlowData;selected?:boolean}){return <div className={`workflow-node-card ${selected?'selected':''}`}><Handle type="target" position={Position.Left} isConnectable={data.kind!=='start'}/><div><i style={{background:colors[data.kind]}}>{kindIcon(data.kind)}</i><b>{data.label}</b></div><p>{data.description}</p><Handle type="source" position={Position.Right} isConnectable={data.kind!=='end'}/></div>}
function NodeInspector({node,tools,skills,knowledge,memories,update,remove}:{node:FlowNode;tools:Tool[];skills:Skill[];knowledge:Resource[];memories:Resource[];update:(p:Partial<FlowData>)=>void;remove:()=>void}){const d=node.data,c=d.config,set=(key:string,value:any)=>update({config:{...c,[key]:value}});return <><header><div><i style={{background:colors[d.kind]}}>{kindIcon(d.kind)}</i><b>{d.label}</b></div><span>{kindLabel(d.kind)}</span></header><div className="inspector-form"><label>节点名称<input maxLength={50} value={d.label} onChange={e=>update({label:e.target.value})}/></label><label>节点描述<input value={d.description} onChange={e=>update({description:e.target.value})}/></label>{['llm','agent'].includes(d.kind)&&<><label>模型选择<select value={d.model||''} onChange={e=>update({model:e.target.value})}><option value="">AUTO · 自动调度</option><option value="device">端侧</option><option value="edge">边缘</option><option value="cloud">云端</option></select></label><label>系统提示词<textarea rows={7} value={d.sys_prompt||''} onChange={e=>update({sys_prompt:e.target.value})}/></label></>}{d.kind==='tool'&&<><label>选择工具<select value={c.tool_id||''} onChange={e=>set('tool_id',e.target.value)}><option value="">请选择</option>{tools.filter(t=>t.enabled).map(t=><option value={t.id} key={t.id}>{t.display_name}</option>)}</select></label><FieldInput name="输入字段" value={c.input_field} set={v=>set('input_field',v)}/><FieldInput name="输出字段" value={c.output_field} set={v=>set('output_field',v)}/></>}{d.kind==='knowledge'&&<><label>知识库<select value={c.knowledge_base_id||''} onChange={e=>set('knowledge_base_id',e.target.value)}><option value="">请选择</option>{knowledge.map(k=><option value={k.id} key={k.id}>{k.name}</option>)}</select></label><div className="runtime-warning">已绑定，知识检索运行接入后续完善。</div></>}{d.kind==='condition'&&<><FieldInput name="判断字段" value={c.field} set={v=>set('field',v)}/><label>运算符<select value={c.operator} onChange={e=>set('operator',e.target.value)}><option value="contains">包含</option><option value="equals">等于</option><option value="not_equals">不等于</option><option value="greater_than">大于</option><option value="exists">存在</option></select></label><FieldInput name="比较值" value={c.value} set={v=>set('value',v)}/></>}{d.kind==='intent'&&<label>意图规则 JSON<textarea rows={8} value={JSON.stringify(c.intents||[],null,2)} onChange={e=>{try{set('intents',JSON.parse(e.target.value))}catch{}}}/></label>}{d.kind==='script'&&<label>输出模板<textarea rows={7} value={c.template||''} onChange={e=>set('template',e.target.value)}/></label>}{d.kind==='loop'&&<label>最大循环次数<input type="number" min={1} max={100} value={c.max_iterations||3} onChange={e=>set('max_iterations',Number(e.target.value))}/></label>}{d.kind==='batch'&&<FieldInput name="数组字段" value={c.items_path} set={v=>set('items_path',v)}/>}<details><summary>高级配置（只读）</summary><pre>{JSON.stringify(c,null,2)}</pre></details>{!['start','end'].includes(d.kind)&&<button className="danger" onClick={remove}>删除节点</button>}</div></>}
function FieldInput({name,value,set}:{name:string;value:any;set:(v:string)=>void}){return <label>{name}<input value={String(value||'')} onChange={e=>set(e.target.value)}/></label>}
function TestDrawer({close,input,setInput,run,testing,test,approve}:{close:()=>void;input:string;setInput:(v:string)=>void;run:Run|null;testing:boolean;test:()=>void;approve:(sequence:number,approved:boolean)=>void}){return <div className="test-drawer"><header><b>工作流测试</b><button onClick={close}>×</button></header><label>输入参数 JSON<textarea rows={6} value={input} onChange={e=>setInput(e.target.value)}/></label><button className="primary" disabled={testing} onClick={test}>{testing?'运行中…':'开始测试'}</button><section>{run?.events?.map((e:any,i)=><div className="test-event" key={e.sequence||i}><b>{eventName(e.type)}</b><span>{e.message||e.node||''}</span>{e.type==='approval_required'&&<div><button onClick={()=>approve(e.sequence,false)}>拒绝</button><button className="primary" onClick={()=>approve(e.sequence,true)}>批准</button></div>}</div>)}{run&&<pre>{run.status==='failed'?run.error:JSON.stringify((run.state as any)?.workflow_output??(run.state as any)?.input,null,2)}</pre>}</section></div>}

function defaults(kind:string):Record<string,any>{if(kind==='tool')return{node_kind:kind,input_field:'input',output_field:'tool_output',tool_id:''};if(kind==='knowledge')return{node_kind:kind,knowledge_base_id:'',output_field:'documents'};if(kind==='condition')return{node_kind:kind,field:'input',operator:'contains',value:'',route_key:`route`,true_route:'true',false_route:'false'};if(kind==='intent')return{node_kind:kind,field:'input',route_key:'route',intents:[{route:'matched',keywords:['示例']}],default_route:'default'};if(kind==='script')return{node_kind:kind,template:'{{input}}',output_field:'script_output',route_key:'route',route:'next'};if(kind==='loop')return{node_kind:kind,max_iterations:3,route_key:'route',continue_route:'continue',done_route:'done'};if(kind==='batch')return{node_kind:kind,items_path:'input.items',output_field:'batch_output',route_key:'route',done_route:'done'};return{node_kind:kind,output_field:'input',tool_ids:[],skill_ids:[],knowledge_base_ids:[],memory_bank_ids:[]}}
function fromWorkflow(wf:Workflow):Snapshot{const positions=(wf.metadata as any)?.editor?.positions||{};const nodes:FlowNode[]=(wf.graph.agents||[]).map((a:any,i)=>({id:a.id,type:'workflow',position:positions[a.id]||{x:100+i*280,y:220},data:{label:a.name,kind:a.config?.node_kind||'agent',description:a.description||'',config:a.config||{},model:a.model||'',sys_prompt:a.sys_prompt||''}}));const edges:Edge[]=[];(wf.graph.connections||[]).forEach((c:any)=>{if(c.conditional)Object.entries(c.path_map||{}).forEach(([route,target])=>edges.push({id:`${c.source}-${route}-${target}`,source:c.source,target:String(target),type:'smoothstep',label:route,data:{route}}));else if(c.target!=='END')edges.push({id:`${c.source}-${c.target}`,source:c.source,target:c.target,type:'smoothstep'})});return{nodes,edges}}
function toWorkflow(nodes:FlowNode[],edges:Edge[]){const agents=nodes.map(n=>({id:n.id,name:n.data.label,description:n.data.description,model:n.data.model||'',sys_prompt:n.data.sys_prompt||'',children:[],config:{...n.data.config,node_kind:n.data.kind}}));const connections:any[]=[];const logic=new Set(nodes.filter(n=>['condition','intent','loop'].includes(n.data.kind)).map(n=>n.id));edges.filter(e=>!logic.has(e.source)).forEach(e=>connections.push({source:e.source,target:e.target,conditional:false}));logic.forEach(source=>{const node=nodes.find(n=>n.id===source)!;const outgoing=edges.filter(e=>e.source===source);connections.push({source,target:'<conditional>',conditional:true,condition_key:node.data.config.route_key||'route',path_map:Object.fromEntries(outgoing.map(e=>[String(e.data?.route||e.label||'default'),e.target]))})});return{entry:nodes.find(n=>n.data.kind==='start')?.id||null,agents,connections}}
function validate(nodes:FlowNode[],edges:Edge[]){const errors:string[]=[];if(nodes.filter(n=>n.data.kind==='start').length!==1)errors.push('必须且只能包含一个开始节点');if(nodes.filter(n=>n.data.kind==='end').length!==1)errors.push('必须且只能包含一个结束节点');if(new Set(nodes.map(n=>n.data.label.trim())).size!==nodes.length||nodes.some(n=>!n.data.label.trim()))errors.push('节点名称不能为空且必须唯一');nodes.filter(n=>n.data.kind==='tool'&&!n.data.config.tool_id).forEach(n=>errors.push(`工具节点“${n.data.label}”尚未选择工具`));nodes.filter(n=>['condition','intent','loop'].includes(n.data.kind)&&!edges.some(e=>e.source===n.id)).forEach(n=>errors.push(`逻辑节点“${n.data.label}”尚未连接出口`));return errors}
function nodeRoutes(node?:FlowNode){if(!node)return[];const c=node.data.config;if(node.data.kind==='condition')return[c.true_route||'true',c.false_route||'false'];if(node.data.kind==='intent')return[...(c.intents||[]).map((x:any)=>x.route),c.default_route||'default'];if(node.data.kind==='loop')return[c.continue_route||'continue',c.done_route||'done'];return[]}
function kindLabel(kind:string){return({start:'开始',end:'结束',llm:'大模型',knowledge:'知识库',tool:'工具',agent:'智能体',condition:'条件判断',intent:'意图分类',script:'脚本',loop:'循环',batch:'批处理'} as Record<string,string>)[kind]||kind}
function kindIcon(kind:string){return({start:'▶',end:'■',llm:'✦',knowledge:'▤',tool:'⌁',agent:'AI',condition:'◇',intent:'◎',script:'</>',loop:'↻',batch:'▦'} as Record<string,string>)[kind]||'◇'}
function kindHint(kind:string){return({llm:'调用模型生成内容',knowledge:'检索已绑定知识',tool:'调用内置或 MCP 工具',agent:'自主规划和执行任务',condition:'按条件选择路径',intent:'按关键词识别意图',script:'模板化处理数据',loop:'按上限循环执行',batch:'处理输入数组'} as Record<string,string>)[kind]||''}
function eventName(type:string){return({plan_created:'执行计划',node_start:'节点开始',node_end:'节点完成',tool_result:'工具结果',approval_required:'等待审批',final:'执行完成'} as Record<string,string>)[type]||type}
