import { appConfirm } from "./dialogs";
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, ReactFlowProvider, addEdge, applyEdgeChanges, applyNodeChanges, type Connection, type Edge, type EdgeChange, type Node, type NodeChange, type ReactFlowInstance, type Viewport } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import type { ApiClient } from './api';
import type { Application, Json, MemoryConfig, ModelConnection, Run, Skill, Tool, Workflow } from './types';
import { SkillDrawer } from './SkillDrawer';
import { ToolDrawer } from './ToolDrawer';
import { ApplicationObserveDrawer, ApplicationVersionDrawer } from './ApplicationDrawers';
import { Markdown } from './Markdown';
import './workflow-editor.css';
import './workflow-editor-isolated.css';
import './workflow-editor-features.css';
import './workflow-confirm.css';
import './model-connections.css';

type Resource={id:string;name:string;description:string;status:string};
type FlowData={label:string;kind:string;description:string;config:Record<string,any>;model?:string;sys_prompt?:string};
type FlowNode=Node<FlowData>;
type Snapshot={nodes:FlowNode[];edges:Edge[];repaired?:boolean};
type CheckIssue={nodeId:string;nodeLabel:string;message:string};
type Props={appId:string;api:ApiClient;notify:(s:string,b?:boolean)=>void;back:()=>void;goSystem:()=>void};
const catalog=[
 {group:'基础',items:[['llm','大模型','✦'],['knowledge','知识库','▤']]},
 {group:'工具',items:[['tool','工具','⌁']]},
 {group:'智能体',items:[['agent','智能体','AI']]},
 {group:'逻辑',items:[['condition','条件判断','◇'],['intent','意图分类','◎'],['script','脚本','</>'],['assign','变量赋值','↦'],['loop','循环','↻'],['batch','批处理','▦']]},
] as const;
const colors:Record<string,string>={start:'#7568ee',end:'#44516d',llm:'#7164ef',knowledge:'#7267ee',tool:'#45a5e6',agent:'#936af0',condition:'#ed9843',intent:'#ef8f45',script:'#e58c3f',assign:'#e68b43',loop:'#e17d3d',batch:'#d87942',batch_start:'#7568ee',batch_end:'#44516d'};

export function WorkflowEditor(props:Props){return <ReactFlowProvider><WorkflowEditorInner {...props}/></ReactFlowProvider>}
function WorkflowEditorInner({appId,api,notify,back,goSystem}:Props){
 const [app,setApp]=useState<Application|null>(null),[workflow,setWorkflow]=useState<Workflow|null>(null),[nodes,setNodes]=useState<FlowNode[]>([]),[edges,setEdges]=useState<Edge[]>([]),[saved,setSaved]=useState(''),[selected,setSelected]=useState<string>(''),[selectedEdge,setSelectedEdge]=useState<string>('');
 const [tools,setTools]=useState<Tool[]>([]),[skills,setSkills]=useState<Skill[]>([]),[knowledge,setKnowledge]=useState<Resource[]>([]),[memories,setMemories]=useState<Resource[]>([]),[agentApps,setAgentApps]=useState<Application[]>([]),[models,setModels]=useState<ModelConnection[]>([]),[search,setSearch]=useState('');
 const [instance,setInstance]=useState<ReactFlowInstance<FlowNode,Edge>|null>(null),[saving,setSaving]=useState(false),[publishing,setPublishing]=useState(false),[testing,setTesting]=useState(false),[testOpen,setTestOpen]=useState(false),[testInput,setTestInput]=useState(''),[testRun,setTestRun]=useState<Run|null>(null);
 const [toolDrawer,setToolDrawer]=useState(false),[skillDrawer,setSkillDrawer]=useState(false),[observeOpen,setObserveOpen]=useState(false),[versionOpen,setVersionOpen]=useState(false),[checkOpen,setCheckOpen]=useState(false);
 const [deleteNode,setDeleteNode]=useState<FlowNode|null>(null);
 const [runs,setRuns]=useState<Run[]>([]),[runDetail,setRunDetail]=useState<Run|null>(null),[versions,setVersions]=useState<Workflow[]>([]),[drawerBusy,setDrawerBusy]=useState(false);
 const history=useRef<Snapshot[]>([]),future=useRef<Snapshot[]>([]),viewport=useRef<Viewport>({x:0,y:0,zoom:1}),stream=useRef<EventSource|null>(null);
 const selectedNode=nodes.find(n=>n.id===selected)||null;
 const serialized=useMemo(()=>serializeEditor(nodes,edges,app),[nodes,edges,app]);
 const dirty=Boolean(saved&&serialized!==saved);
 const autoReady=modelAutoReady(models);
 const checkIssues=useMemo(()=>inspectWorkflow(nodes,edges,models,app),[nodes,edges,models,app]);
 useEffect(()=>{let active=true;Promise.all([api.get<Application&{workflow:Workflow}>(`/api/apps/${appId}`),api.get<Tool[]>('/api/tools'),api.get<Skill[]>('/api/skills'),api.get<Resource[]>('/api/resources/knowledge-bases'),api.get<Resource[]>('/api/memory-banks'),api.get<Application[]>('/api/apps'),api.get<ModelConnection[]>('/api/model-connections')]).then(([value,t,s,k,m,applications,mc])=>{if(!active)return;const normalized=normalizeWorkflowApp(value),wf=value.workflow,converted=fromWorkflow(wf);setApp(normalized);setWorkflow(wf);setNodes(converted.nodes);setEdges(converted.edges);setSaved(converted.repaired?'__missing-boundary-nodes__':serializeEditor(converted.nodes,converted.edges,normalized));if(converted.repaired)notify('已为旧工作流补齐开始/结束节点，请检查连线后保存');setTools(t);setSkills(s);setKnowledge(k);setMemories(m);setAgentApps(applications.filter(item=>item.app_type==='agent'));setModels(mc);viewport.current=((wf.metadata as any)?.editor?.viewport)||viewport.current}).catch(e=>notify((e as Error).message,true));return()=>{active=false;stream.current?.close()}},[appId,api]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};addEventListener('beforeunload',guard);return()=>removeEventListener('beforeunload',guard)},[dirty]);
 const remember=()=>{history.current.push({nodes:structuredClone(nodes),edges:structuredClone(edges)});if(history.current.length>50)history.current.shift();future.current=[]};
 const undo=()=>{const previous=history.current.pop();if(!previous)return;future.current.push({nodes,edges});setNodes(previous.nodes);setEdges(previous.edges)};
 const redo=()=>{const next=future.current.pop();if(!next)return;history.current.push({nodes,edges});setNodes(next.nodes);setEdges(next.edges)};
 const onNodesChange=useCallback((changes:NodeChange<FlowNode>[])=>setNodes(current=>applyNodeChanges(changes,current)),[]);
 const onEdgesChange=useCallback((changes:EdgeChange<Edge>[])=>setEdges(current=>applyEdgeChanges(changes,current)),[]);
 const scheduleLoopResize=(parentId:string)=>requestAnimationFrame(()=>requestAnimationFrame(()=>setNodes(current=>resizeLoopContainer(current,parentId))));
 const finishNodeDrag=(_:MouseEvent|TouchEvent,node:FlowNode)=>{if(node.parentId){scheduleLoopResize(node.parentId);return}if(['loop','batch','start','end','loop_start','loop_end','batch_start','batch_end'].includes(node.data.kind))return;const center={x:node.position.x+120,y:node.position.y+45},parent=nodes.find(item=>['loop','batch'].includes(item.data.kind)&&center.x>=item.position.x&&center.x<=item.position.x+Math.max(Number((item.style as any)?.width||0),Number(item.measured?.width||0),360)&&center.y>=item.position.y&&center.y<=item.position.y+Math.max(Number((item.style as any)?.height||0),Number(item.measured?.height||0),180));if(!parent)return;setNodes(current=>{const child=current.find(item=>item.id===node.id);if(!child||['loop','batch'].includes(child.data.kind))return current;const grouped:FlowNode={...child,parentId:parent.id,extent:'parent',expandParent:true,position:{x:Math.max(18,node.position.x-parent.position.x),y:Math.max(58,node.position.y-parent.position.y)}};return[...current.filter(item=>item.id!==node.id),grouped]});scheduleLoopResize(parent.id)};
 const onConnect=useCallback((connection:Connection)=>{if(!connection.source||!connection.target||connection.source===connection.target)return;const source=nodes.find(n=>n.id===connection.source),target=nodes.find(n=>n.id===connection.target);if(source?.data.kind==='end'||target?.data.kind==='start'||edges.some(e=>e.source===connection.source&&e.target===connection.target)){notify('该连线不符合端口规则或已经存在',true);return}remember();const routes=nodeRoutes(source);const used=edges.filter(e=>e.source===connection.source).map(e=>String(e.data?.route||''));const route=routes.find(r=>!used.includes(r))||'';setEdges(current=>addEdge({...connection,id:`edge-${crypto.randomUUID()}`,type:'smoothstep',label:route,data:{route}},current))},[nodes,edges]);
 const drop=(event:React.DragEvent)=>{event.preventDefault();const kind=event.dataTransfer.getData('application/workflow-node');if(!kind||!instance)return;remember();const absolute=instance.screenToFlowPosition({x:event.clientX,y:event.clientY}),index=nodes.filter(n=>n.data.kind===kind).length+1,label=`${kindLabel(kind)}${index}`;if(['loop','batch'].includes(kind)){const id=`node-${crypto.randomUUID()}`,startId=`${id}-start`,endId=`${id}-end`,isLoop=kind==='loop',parent:FlowNode={id,type:'workflow',position:absolute,style:{width:640,height:290},data:{label,kind,description:kindHint(kind),config:{...defaults(kind),container_width:640,container_height:290}},draggable:true},start:FlowNode={id:startId,type:'workflow',parentId:id,extent:'parent',expandParent:true,position:{x:28,y:112},data:{label:isLoop?'循环开始':'批处理开始',kind:isLoop?'loop_start':'batch_start',description:'进入子流程',config:defaults(isLoop?'loop_start':'batch_start')},draggable:true},end:FlowNode={id:endId,type:'workflow',parentId:id,extent:'parent',expandParent:true,position:{x:332,y:112},data:{label:isLoop?'迭代结束':'批处理结束',kind:isLoop?'loop_end':'batch_end',description:'结束当前子流程',config:defaults(isLoop?'loop_end':'batch_end')},draggable:true};setNodes(current=>[...current,parent,start,end]);return}const parent=nodes.filter(node=>['loop','batch'].includes(node.data.kind)).find(node=>{const width=Math.max(Number((node.style as any)?.width||0),Number(node.measured?.width||0),Number(node.data.config.container_width||0),560),height=Math.max(Number((node.style as any)?.height||0),Number(node.measured?.height||0),Number(node.data.config.container_height||0),290);return absolute.x>=node.position.x&&absolute.x<=node.position.x+width&&absolute.y>=node.position.y&&absolute.y<=node.position.y+height}),id=`node-${crypto.randomUUID()}`,node:FlowNode={id,type:'workflow',position:parent?{x:absolute.x-parent.position.x,y:absolute.y-parent.position.y}:absolute,data:{label,kind,description:kindHint(kind),config:defaults(kind)},draggable:true,...(parent?{parentId:parent.id,extent:'parent' as const,expandParent:true}: {})};setNodes(current=>[...current,node])};
 const updateNode=(patch:Partial<FlowData>)=>{if(!selectedNode)return;remember();setNodes(current=>current.map(n=>n.id===selectedNode.id?{...n,data:{...n.data,...patch}}:n))};
 const updateSelectedConfig=(key:string,value:any)=>{if(!selected)return;remember();setNodes(current=>current.map(node=>node.id===selected?{...node,data:{...node.data,config:{...node.data.config,[key]:value}}}:node))};
 const toggleSelectedConfig=(key:'tool_ids'|'skill_ids',id:string)=>{if(!selected)return;remember();setNodes(current=>current.map(node=>{if(node.id!==selected)return node;const values=Array.isArray(node.data.config[key])?node.data.config[key]:[];return {...node,data:{...node.data,config:{...node.data.config,[key]:values.includes(id)?values.filter((value:string)=>value!==id):[...values,id]}}}}))};
 const changeSelectedTools=(ids:string[],add:boolean)=>{const values=Array.isArray(selectedNode?.data.config.tool_ids)?selectedNode!.data.config.tool_ids:[],wanted=new Set(ids);updateSelectedConfig('tool_ids',add?[...values,...ids.filter(id=>!values.includes(id))]:values.filter((id:string)=>!wanted.has(id)))};
 const reloadResources=()=>Promise.all([api.get<Tool[]>('/api/tools'),api.get<Skill[]>('/api/skills')]).then(([t,s])=>{setTools(t);setSkills(s)});
 const requestRemoveSelected=()=>{if(selectedNode&&!['start','end','loop_start','loop_end','batch_start','batch_end'].includes(selectedNode.data.kind))setDeleteNode(selectedNode)};
 const confirmRemoveSelected=()=>{if(!deleteNode)return;remember();const ids=new Set([deleteNode.id,...nodes.filter(node=>node.parentId===deleteNode.id).map(node=>node.id)]);setNodes(current=>current.filter(n=>!ids.has(n.id)));setEdges(current=>current.filter(e=>!ids.has(e.source)&&!ids.has(e.target)));setSelected('');setSelectedEdge('');setDeleteNode(null)};
 const removeSelectedEdge=()=>{if(!selectedEdge)return;remember();setEdges(current=>current.filter(edge=>edge.id!==selectedEdge));setSelectedEdge('')};
 useEffect(()=>{const remove=(event:KeyboardEvent)=>{if(!['Delete','Backspace'].includes(event.key)||(event.target as HTMLElement)?.matches('input,textarea,select'))return;if(selectedEdge){event.preventDefault();removeSelectedEdge();return}if(selectedNode&&!['start','end','loop_start','loop_end','batch_start','batch_end'].includes(selectedNode.data.kind)){event.preventDefault();requestRemoveSelected()}};window.addEventListener('keydown',remove);return()=>window.removeEventListener('keydown',remove)},[selected,selectedEdge,edges,nodes]);
 const errors=()=>checkIssues.map(issue=>issue.nodeLabel?`${issue.nodeLabel}：${issue.message}`:issue.message);
 const save=async(showNotice=true)=>{if(!workflow||!app)return false;const problem=errors();if(problem.length){notify(problem[0],true);return false}setSaving(true);try{const payload=toWorkflow(nodes,edges);const metadata={...(workflow.metadata||{}),editor:{positions:Object.fromEntries(nodes.map(n=>[n.id,n.position])),parents:Object.fromEntries(nodes.filter(n=>n.parentId).map(n=>[n.id,n.parentId])),sizes:Object.fromEntries(nodes.filter(n=>n.data.kind==='loop').map(n=>[n.id,{width:Number((n.style as any)?.width||n.measured?.width||360),height:Number((n.style as any)?.height||n.measured?.height||180)}])),viewport:viewport.current}};const updatedApp=await api.put<Application>(`/api/apps/${appId}`,memoryPayload(app));const updatedWorkflow=await api.put<Workflow>(`/api/workflows/${workflow.id}`,{name:app.name,description:app.description,tags:['workflow','application'],metadata,graph:payload});const normalized=normalizeWorkflowApp(updatedApp);setWorkflow(updatedWorkflow);setApp(normalized);setSaved(serializeEditor(nodes,edges,normalized));if(showNotice)notify('工作流草稿已保存');return true}catch(e){notify((e as Error).message,true);return false}finally{setSaving(false)}};
 const publish=async()=>{if(dirty)return;setPublishing(true);try{const value=await api.post<Application>(`/api/apps/${appId}/publish`);const publishedWorkflow=await api.get<Workflow>(`/api/workflows/${workflow!.id}`);setApp(normalizeWorkflowApp(value));setWorkflow(publishedWorkflow);notify(`工作流应用已发布为 v${publishedWorkflow.version}`)}catch(e){notify((e as Error).message,true)}finally{setPublishing(false)}};
 const test=async()=>{try{const message=testInput.trim();if(!message){notify('请输入测试消息',true);return}setTesting(true);const run=await api.post<Run>(`/api/apps/${appId}/runs`,{input:{input:message},recursion_limit:50});setTestRun(run);setTestInput('');const source=new EventSource(`${api.baseUrl.replace(/\/$/,'')}/api/runs/${run.id}/events?after=${run.events?.length||0}&access_token=${encodeURIComponent(api.getAuthToken())}`);stream.current=source;source.addEventListener('run_event',e=>{const event=JSON.parse((e as MessageEvent).data);setTestRun(current=>current?{...current,status:'running',events:[...(current.events||[]),event]}:current)});source.addEventListener('run_completed',async()=>{source.close();setTestRun(await api.get<Run>(`/api/runs/${run.id}`));setTesting(false)});source.onerror=()=>{source.close();setTesting(false);notify('测试连接已中断',true)}}catch(e){setTesting(false);notify((e as Error).message,true)}};
 const openAndTest=()=>{if(!testing)setTestOpen(true)};
 const runTest=async()=>{if(testing)return;if(checkIssues.length){setCheckOpen(true);notify(`检查发现 ${checkIssues.length} 项未配置完成`,true);return}if(dirty&&!(await save(false)))return;await test()};
 const openObserve=async()=>{setObserveOpen(true);setDrawerBusy(true);setRunDetail(null);try{setRuns(await api.get<Run[]>(`/api/apps/${appId}/runs`))}catch(e){notify((e as Error).message,true)}finally{setDrawerBusy(false)}};
 const selectRun=async(run:Run)=>{setDrawerBusy(true);try{setRunDetail(await api.get<Run>(`/api/runs/${run.id}`))}catch(e){notify((e as Error).message,true)}finally{setDrawerBusy(false)}};
 const openVersions=async()=>{if(!workflow)return;setVersionOpen(true);setDrawerBusy(true);try{setVersions(await api.get<Workflow[]>(`/api/workflows/${workflow.id}/versions`))}catch(e){notify((e as Error).message,true)}finally{setDrawerBusy(false)}};
 const rollback=async(version:number)=>{if(!workflow||!(await appConfirm(`${dirty?'当前未保存修改将被丢弃。\n':''}确认切换到已发布版本 v${version}？`)))return;setDrawerBusy(true);try{const updated=await api.post<Workflow>(`/api/workflows/${workflow.id}/rollback/${version}`);const converted=fromWorkflow(updated);setWorkflow(updated);setNodes(converted.nodes);setEdges(converted.edges);setSaved(converted.repaired?'__missing-boundary-nodes__':serializeEditor(converted.nodes,converted.edges,app));history.current=[];future.current=[];setSelected('');setSelectedEdge('');setVersions(await api.get<Workflow[]>(`/api/workflows/${workflow.id}/versions`));notify(converted.repaired?`已切换到 v${version}，并补齐缺失的结构节点`:`当前版本已切换为 v${version}`)}catch(e){notify((e as Error).message,true)}finally{setDrawerBusy(false)}};
 const approve=async(sequence:number,approved:boolean)=>{if(!testRun)return;try{await api.post(`/api/runs/${testRun.id}/approvals/${sequence}/${approved?'approve':'reject'}`,{reason:approved?'用户批准':'用户拒绝'});setTestRun(await api.get<Run>(`/api/runs/${testRun.id}`));notify(approved?'已批准工具调用':'已拒绝工具调用')}catch(e){notify((e as Error).message,true)}};
 const leave=async ()=>{if(dirty&&!(await appConfirm('工作流尚未保存，确定离开吗？')))return;back()};
 const goToSystem=async ()=>{if(dirty&&!(await appConfirm('工作流尚未保存，确定离开吗？')))return;goSystem()};
 if(!app||!workflow)return <div className="workflow-loading"><span className="spinner"/>正在加载工作流…</div>;
 return <div className="workflow-editor"><header className="workflow-top"><div><button onClick={leave}>←</button><span className="workflow-logo">⌘</span><b>{app.name}</b><em>{app.status==='published'?'已发布':'草稿'}</em>{dirty&&<i>未保存</i>}</div><nav><strong>画布配置</strong><span>发布渠道</span></nav><div><button onClick={openObserve}>观测</button><button onClick={openVersions}>版本管理</button><button onClick={openAndTest} disabled={saving}>{testing?'测试中…':'▷ 测试'}</button><button className="workflow-check-button" onClick={()=>setCheckOpen(value=>!value)} aria-label="检查工作流">☷{checkIssues.length>0&&<b>{checkIssues.length}</b>}</button><button onClick={()=>void save()} disabled={!dirty||saving}>{saving?'保存中…':'保存'}</button><button className="primary" onClick={publish} disabled={dirty||publishing}>{publishing?'发布中…':'发布'}</button></div></header>
  <main className="workflow-body"><aside className="node-library"><h2>节点管理</h2><label className="workflow-default-model"><span>工作流默认模型</span><select value={app.model||'auto'} onChange={e=>setApp(current=>current?{...current,model:e.target.value}:current)}><option value="auto" disabled={!autoReady}>AUTO · 自动调度{autoReady?'':'（未就绪）'}</option>{modelGroups(models)}</select><small>智能体节点可继承或单独覆盖。</small></label><div className="node-tabs"><b>节点库</b><span>当前</span></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索节点名称"/>{catalog.map(group=><section key={group.group}><small>{group.group}</small>{group.items.filter(item=>item[1].includes(search)).map(item=><div draggable onDragStart={e=>{e.dataTransfer.setData('application/workflow-node',item[0]);e.dataTransfer.effectAllowed='move'}} className="library-node" key={item[0]}><i style={{background:colors[item[0]]}}>{item[2]}</i><span><b>{item[1]}</b><small>{kindHint(item[0])}</small></span></div>)}</section>)}</aside>
   <section className="workflow-canvas" onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='move'}} onDrop={drop}><div className="canvas-actions"><button onClick={undo} disabled={!history.current.length}>↶</button><button onClick={redo} disabled={!future.current.length}>↷</button>{selectedEdge&&<button className="danger" onClick={removeSelectedEdge}>删除连线</button>}</div><ReactFlow<FlowNode,Edge> nodes={nodes} edges={edges} nodeTypes={{workflow:WorkflowNode}} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeDragStart={remember} onNodeDragStop={finishNodeDrag} onConnect={onConnect} onNodeClick={(_,node)=>{setSelected(node.id);setSelectedEdge('')}} onEdgeClick={(_,edge)=>{setSelectedEdge(edge.id);setSelected('')}} onPaneClick={()=>{setSelected('');setSelectedEdge('')}} onInit={setInstance} onMoveEnd={(_,v)=>viewport.current=v} deleteKeyCode={null} defaultViewport={viewport.current} fitView><Background gap={18} size={1}/><Controls/><MiniMap nodeColor={n=>colors[(n.data as FlowData).kind]||'#777'}/></ReactFlow></section>
   {selectedNode&&<aside className="workflow-inspector open"><button className="workflow-inspector-close" onClick={()=>setSelected('')} aria-label="关闭节点配置">×</button><NodeInspector node={selectedNode} tools={tools} skills={skills} knowledge={knowledge} memories={memories} agentApps={agentApps} models={models} app={app} setApp={setApp} goSystem={goToSystem} openTools={()=>setToolDrawer(true)} openSkills={()=>setSkillDrawer(true)} update={updateNode} remove={requestRemoveSelected}/></aside>}
  </main>{testOpen&&<TestDrawer close={()=>!testing&&setTestOpen(false)} input={testInput} setInput={setTestInput} run={testRun} testing={testing} test={runTest} approve={approve} nodes={nodes} edges={edges}/>} {checkOpen&&<CheckDrawer issues={checkIssues} nodes={nodes} close={()=>setCheckOpen(false)} select={id=>{setSelected(id);setSelectedEdge('');setCheckOpen(false)}}/>} {observeOpen&&<ApplicationObserveDrawer runs={runs} detail={runDetail} busy={drawerBusy} close={()=>setObserveOpen(false)} select={selectRun}/>} {versionOpen&&workflow&&<ApplicationVersionDrawer currentVersion={workflow.version} versions={versions} busy={drawerBusy} close={()=>setVersionOpen(false)} activate={rollback}/>} {deleteNode&&<DeleteNodeDialog node={deleteNode} cancel={()=>setDeleteNode(null)} confirm={confirmRemoveSelected}/>} {toolDrawer&&selectedNode&&<ToolDrawer api={api} tools={tools} selected={selectedNode.data.config.tool_ids||[]} close={()=>setToolDrawer(false)} reload={reloadResources} toggle={id=>toggleSelectedConfig('tool_ids',id)} changeMany={changeSelectedTools} notify={notify}/>} {skillDrawer&&selectedNode&&<SkillDrawer api={api} skills={skills} selected={selectedNode.data.config.skill_ids||[]} close={()=>setSkillDrawer(false)} reload={reloadResources} toggle={id=>toggleSelectedConfig('skill_ids',id)} notify={notify}/>}</div>
}

function WorkflowNode({data,selected}:{data:FlowData;selected?:boolean}){if(['loop','batch'].includes(data.kind))return <div className={`workflow-node-card workflow-loop-container ${selected?'selected':''}`}><Handle type="target" position={Position.Left}/><header><i style={{background:colors[data.kind]}}>{kindIcon(data.kind)}</i><b>{data.label}</b><span>{data.kind==='batch'?`并发 ${data.config.concurrency||3}`:data.config.loop_type==='array'?'数组循环':`最多 ${data.config.max_iterations||3} 次`}</span></header><div className="workflow-loop-canvas"><small>拖入节点构建子流程；移动容器会带动内部节点</small></div><Handle type="source" position={Position.Right}/></div>;return <div className={`workflow-node-card ${selected?'selected':''}`}>{!['start','loop_start','batch_start'].includes(data.kind)&&<Handle type="target" position={Position.Left}/>}<div><i style={{background:colors[data.kind]}}>{kindIcon(data.kind)}</i><b>{data.label}</b></div><p>{data.description}</p>{!['end','loop_end','batch_end'].includes(data.kind)&&<Handle type="source" position={Position.Right}/>}</div>}
function NodeInspector({node,tools,skills,knowledge,memories,agentApps,models,app,setApp,goSystem,openTools,openSkills,update,remove}:{node:FlowNode;tools:Tool[];skills:Skill[];knowledge:Resource[];memories:Resource[];agentApps:Application[];models:ModelConnection[];app:Application;setApp:React.Dispatch<React.SetStateAction<Application|null>>;goSystem:()=>void;openTools:()=>void;openSkills:()=>void;update:(p:Partial<FlowData>)=>void;remove:()=>void}){
 const [agentAppSearch,setAgentAppSearch]=useState('');
 useEffect(()=>setAgentAppSearch(''),[node.id]);
 const d=node.data,c=d.config,set=(key:string,value:any)=>update({config:{...c,[key]:value}}),selectedSkills=skills.filter(skill=>(c.skill_ids||[]).includes(skill.id));
 const toggleConfig=(key:'knowledge_base_ids',id:string)=>{const values=Array.isArray(c[key])?c[key]:[];set(key,values.includes(id)?values.filter((value:string)=>value!==id):[...values,id])};
 const changeApp=(patch:Partial<Application>)=>setApp(current=>current?{...current,...patch}:current);
 const toggleMemory=(id:string)=>setApp(current=>{if(!current)return current;const selected=current.memory_bank_ids.includes(id),ids=selected?current.memory_bank_ids.filter(value=>value!==id):[...current.memory_bank_ids,id],primary=selected&&current.primary_memory_bank_id===id?(ids[0]||null):(current.primary_memory_bank_id||id);return{...current,memory_bank_ids:ids,primary_memory_bank_id:primary}});
 const memoryChange=<K extends keyof MemoryConfig>(key:K,value:MemoryConfig[K])=>changeApp({memory_config:{...app.memory_config,[key]:value}});
 const useAgentApp=(sourceId:string)=>{if(!sourceId){const {source_app_id:_sourceId,source_app_name:_sourceName,...customConfig}=c;update({config:customConfig});return}const source=agentApps.find(item=>item.id===sourceId);if(!source)return;update({model:['device','edge','cloud'].includes(source.model)?'auto':source.model||'',sys_prompt:source.system_prompt||'',config:{...c,source_app_id:source.id,source_app_name:source.name,tool_ids:source.tool_ids||[],skill_ids:source.skill_ids||[],knowledge_base_ids:source.knowledge_base_ids||[]}})};
 const visibleAgentApps=agentApps.filter(item=>!agentAppSearch.trim()||item.name.toLowerCase().includes(agentAppSearch.trim().toLowerCase())||item.id===c.source_app_id);
 return <><header><div><i style={{background:colors[d.kind]}}>{kindIcon(d.kind)}</i><b>{d.label}</b></div><div className="workflow-node-header-actions"><span>{kindLabel(d.kind)}</span>{!['start','end','loop_start','loop_end','batch_start','batch_end'].includes(d.kind)?<button className="danger" onClick={remove}>删除节点</button>:<em>结构节点不可删除</em>}</div></header><div className="inspector-form">
  <label>节点名称<input maxLength={50} value={d.label} onChange={e=>update({label:e.target.value})}/></label><label>节点描述<input value={d.description} onChange={e=>update({description:e.target.value})}/></label>
  {d.kind==='agent'&&<label className="workflow-agent-template">复用智能体应用<div className="workflow-agent-app-picker"><input type="search" value={agentAppSearch} onChange={e=>setAgentAppSearch(e.target.value)} placeholder="搜索智能体应用名称"/><select value={String(c.source_app_id||'')} onChange={e=>useAgentApp(e.target.value)}><option value="">自定义配置</option>{visibleAgentApps.map(item=><option value={item.id} key={item.id}>{item.name}{item.status==='published'?' · 已发布':' · 草稿'}</option>)}</select>{agentAppSearch&&!visibleAgentApps.length&&<small>没有匹配的智能体应用</small>}</div><small>选择后复制模型、提示词、工具、Skill 和知识库；当前节点仍可独立修改。</small></label>}
  {['llm','agent'].includes(d.kind)&&<><label>模型选择<select value={d.model||''} onChange={e=>update({model:e.target.value})}><option value="">继承工作流默认模型</option><option value="auto" disabled={!modelAutoReady(models)}>AUTO · 端边云自动调度{modelAutoReady(models)?'':'（未就绪）'}</option>{modelGroups(models)}</select></label><button type="button" className="model-manage-button" onClick={goSystem}>去 API Key 界面配置模型</button>{!models.length&&<div className="runtime-warning">尚未配置真实模型连接，请先在首页 API Key 界面创建并完成连接测试。</div>}<label>系统提示词<textarea rows={7} value={d.sys_prompt||''} onChange={e=>update({sys_prompt:e.target.value})}/></label></>}
  {d.kind==='agent'&&<div className="workflow-agent-capabilities"><section><div><b>MCP / 工具</b><button onClick={openTools}>＋ 添加工具</button></div><p>{(c.tool_ids||[]).length?tools.filter(t=>(c.tool_ids||[]).includes(t.id)).map(t=>t.display_name||t.name).join('、'):'尚未挂载工具'}</p></section><section><div><b>Skill</b><button onClick={openSkills}>＋ 添加 Skill</button></div><p>{!(c.skill_ids||[]).length?'尚未挂载 Skill':selectedSkills.length?selectedSkills.map(skill=>skill.name).join('、'):`已挂载 ${(c.skill_ids||[]).length} 个 Skill（正在读取名称）`}</p></section><section><div><b>知识库</b><span>{(c.knowledge_base_ids||[]).length} 个</span></div><div className="workflow-bind-list">{knowledge.length?knowledge.map(item=><label key={item.id}><input type="checkbox" checked={(c.knowledge_base_ids||[]).includes(item.id)} onChange={()=>toggleConfig('knowledge_base_ids',item.id)}/><span>{item.name}</span></label>):<p>暂无知识库</p>}</div><small>仅完成挂载与保存，实际检索运行接入待完善。</small></section><section className="workflow-shared-memory"><div><b>工作流共享长期记忆</b><input type="checkbox" checked={app.memory_config.long_term_enabled} onChange={e=>memoryChange('long_term_enabled',e.target.checked)}/></div><small>该设置对工作流中的所有智能体生效。</small>{app.memory_config.long_term_enabled&&<><div className="workflow-bind-list">{memories.length?memories.map(item=><label key={item.id}><input type="checkbox" checked={app.memory_bank_ids.includes(item.id)} onChange={()=>toggleMemory(item.id)}/><span>{item.name}</span>{app.memory_bank_ids.includes(item.id)&&<button onClick={()=>changeApp({primary_memory_bank_id:item.id})}>{app.primary_memory_bank_id===item.id?'主库':'设为主库'}</button>}</label>):<p>暂无记忆库</p>}</div><label className="memory-auto-write"><input type="checkbox" checked={app.memory_config.auto_write} onChange={e=>memoryChange('auto_write',e.target.checked)}/> 自动写入长期记忆</label></>}</section></div>}
  {d.kind==='tool'&&<><label>选择工具<select value={c.tool_id||''} onChange={e=>set('tool_id',e.target.value)}><option value="">请选择</option>{tools.filter(t=>t.enabled).map(t=><option value={t.id} key={t.id}>{t.display_name}</option>)}</select></label><FieldInput name="输入字段" value={c.input_field} set={v=>set('input_field',v)}/><FieldInput name="输出字段" value={c.output_field} set={v=>set('output_field',v)}/></>}
  {d.kind==='knowledge'&&<><label>知识库<select value={c.knowledge_base_id||''} onChange={e=>set('knowledge_base_id',e.target.value)}><option value="">请选择</option>{knowledge.map(k=><option value={k.id} key={k.id}>{k.name}</option>)}</select></label><div className="runtime-warning">已绑定，知识检索运行接入后续完善。</div></>}
  {d.kind==='condition'&&<ConditionEditor value={c} set={set}/>} {d.kind==='intent'&&<IntentEditor value={c} set={set} models={models}/>} {d.kind==='script'&&<ScriptEditor value={c} set={set}/>} {d.kind==='assign'&&<AssignmentEditor value={c} set={set}/>} {d.kind==='loop'&&<LoopEditor value={c} set={set}/>} {d.kind==='batch'&&<BatchEditor value={c} set={set}/>}<details><summary>高级配置（只读）</summary><pre>{JSON.stringify(c,null,2)}</pre></details>
 </div></>
}
function FieldInput({name,value,set}:{name:string;value:any;set:(v:string)=>void}){return <label>{name}<input value={String(value||'')} onChange={e=>set(e.target.value)}/></label>}
const operators=[['equals','等于'],['not_equals','不等于'],['contains','包含'],['not_contains','不包含'],['greater_than','大于'],['less_than','小于'],['exists','存在'],['is_empty','为空'],['not_empty','不为空']];
function ConditionRow({value,change,remove}:{value:any;change:(v:any)=>void;remove:()=>void}){return <div className="workflow-rule-row"><input value={value.field||''} onChange={e=>change({...value,field:e.target.value})} placeholder="变量路径"/><select value={value.operator||'equals'} onChange={e=>change({...value,operator:e.target.value})}>{operators.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select><input value={String(value.value??'')} disabled={['exists','is_empty','not_empty'].includes(value.operator)} onChange={e=>change({...value,value:e.target.value})} placeholder="比较值"/><button onClick={remove}>×</button></div>}
function ConditionEditor({value,set}:{value:any;set:(k:string,v:any)=>void}){const branches=value.branches||[];const update=(next:any[])=>set('branches',next);return <div className="workflow-logic-editor"><b>判断分支</b>{branches.map((branch:any,bi:number)=><fieldset key={bi}><legend><input value={branch.name||`分支 ${bi+1}`} onChange={e=>update(branches.map((x:any,i:number)=>i===bi?{...x,name:e.target.value}:x))}/><button onClick={()=>update(branches.filter((_:any,i:number)=>i!==bi))}>删除</button></legend>{(branch.groups||[]).map((group:any,gi:number)=><section key={gi}><small>{gi?'或满足以下全部条件':'满足以下全部条件'}</small>{(group.conditions||[]).map((condition:any,ci:number)=><ConditionRow key={ci} value={condition} change={next=>update(branches.map((x:any,i:number)=>i===bi?{...x,groups:x.groups.map((g:any,j:number)=>j===gi?{...g,conditions:g.conditions.map((c:any,k:number)=>k===ci?next:c)}:g)}:x))} remove={()=>update(branches.map((x:any,i:number)=>i===bi?{...x,groups:x.groups.map((g:any,j:number)=>j===gi?{...g,conditions:g.conditions.filter((_:any,k:number)=>k!==ci)}:g)}:x))}/>) }<button onClick={()=>update(branches.map((x:any,i:number)=>i===bi?{...x,groups:x.groups.map((g:any,j:number)=>j===gi?{...g,conditions:[...g.conditions,{field:'input',operator:'equals',value:''}]}:g)}:x))}>＋ 条件</button></section>)}<button onClick={()=>update(branches.map((x:any,i:number)=>i===bi?{...x,groups:[...x.groups,{conditions:[{field:'input',operator:'equals',value:''}]}]}:x))}>＋ 或条件组</button></fieldset>)}<button onClick={()=>update([...branches,{name:`分支 ${branches.length+1}`,route:`branch_${branches.length+1}`,groups:[{conditions:[{field:'input',operator:'equals',value:''}]}]}])}>＋ 添加分支</button><FieldInput name="其他分支标识" value={value.default_route||'default'} set={v=>set('default_route',v)}/></div>}
function IntentEditor({value,set,models}:{value:any;set:(k:string,v:any)=>void;models:ModelConnection[]}){const items=value.categories||[],update=(next:any[])=>set('categories',next);return <div className="workflow-logic-editor"><FieldInput name="输入变量" value={value.input_field||'input'} set={v=>set('input_field',v)}/><label>分类模型<select value={value.model||''} onChange={e=>set('model',e.target.value)}><option value="">请选择已测试模型</option>{modelGroups(models)}</select></label><label>分类模式<select value={value.mode||'single'} onChange={e=>set('mode',e.target.value)}><option value="single">单意图</option><option value="multiple">多意图</option></select></label>{items.map((item:any,index:number)=><fieldset key={index}><legend>意图 {index+1}<button onClick={()=>update(items.filter((_:any,i:number)=>i!==index))}>删除</button></legend><input value={item.name||''} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,name:e.target.value}:x))} placeholder="意图名称"/><textarea rows={2} value={item.description||''} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,description:e.target.value}:x))} placeholder="描述哪些表达属于该意图"/></fieldset>)}<button onClick={()=>update([...items,{name:`意图${items.length+1}`,description:'',route:`intent_${items.length+1}`}])}>＋ 添加意图</button><label>补充提示词<textarea rows={3} value={value.prompt||''} onChange={e=>set('prompt',e.target.value)}/></label></div>}
function ScriptEditor({value,set}:{value:any;set:(k:string,v:any)=>void}){const inputs=value.inputs||[],update=(next:any[])=>set('inputs',next);return <div className="workflow-logic-editor"><label>语言<select value={value.language||'python'} onChange={e=>set('language',e.target.value)}><option value="python">Python</option><option value="javascript">JavaScript</option></select></label><fieldset><legend>输入变量</legend>{inputs.map((item:any,index:number)=><div className="workflow-rule-row" key={index}><input value={item.name||''} onChange={e=>update(inputs.map((x:any,i:number)=>i===index?{...x,name:e.target.value}:x))} placeholder="参数名"/><input value={item.path||''} onChange={e=>update(inputs.map((x:any,i:number)=>i===index?{...x,path:e.target.value}:x))} placeholder="变量路径"/><span/><button onClick={()=>update(inputs.filter((_:any,i:number)=>i!==index))}>×</button></div>)}<button onClick={()=>update([...inputs,{name:`param_${inputs.length+1}`,path:'input'}])}>＋ 添加输入</button></fieldset><label>代码<textarea className="workflow-code-editor" rows={13} spellCheck={false} value={value.code||''} onChange={e=>set('code',e.target.value)}/></label><div className="rule-form-grid"><label>超时（秒）<input type="number" min={1} max={30} value={value.timeout_seconds||5} onChange={e=>set('timeout_seconds',Number(e.target.value))}/></label><label>重试次数<input type="number" min={0} max={4} value={value.retry_count||0} onChange={e=>set('retry_count',Number(e.target.value))}/></label></div><label>异常策略<select value={value.error_strategy||'raise'} onChange={e=>set('error_strategy',e.target.value)}><option value="raise">终止工作流</option><option value="default">返回默认空对象</option></select></label><FieldInput name="输出字段" value={value.output_field||'script_output'} set={v=>set('output_field',v)}/></div>}
function AssignmentEditor({value,set}:{value:any;set:(k:string,v:any)=>void}){const items=value.assignments||[],update=(next:any[])=>set('assignments',next);return <div className="workflow-logic-editor"><b>变量操作</b>{items.map((item:any,index:number)=><div className="workflow-rule-row" key={index}><input value={item.target||''} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,target:e.target.value}:x))} placeholder="目标变量"/><select value={item.operation||'set'} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,operation:e.target.value}:x))}><option value="set">覆盖</option><option value="append">数组追加</option><option value="extend">数组合并</option><option value="add">数字相加</option><option value="merge">对象合并</option></select><input value={item.source||''} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,source:e.target.value}:x))} placeholder="来源变量"/><button onClick={()=>update(items.filter((_:any,i:number)=>i!==index))}>×</button></div>)}<button onClick={()=>update([...items,{target:'',operation:'set',source:'input'}])}>＋ 添加变量操作</button></div>}
function ArrayInputs({value,set,prefix}:{value:any;set:(k:string,v:any)=>void;prefix:string}){const items=value.input_arrays||[],update=(next:any[])=>set('input_arrays',next);return <fieldset><legend>输入数组</legend>{items.map((item:any,index:number)=><div className="workflow-rule-row" key={index}><input value={item.path||''} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,path:e.target.value}:x))} placeholder="数组变量路径"/><input value={item.item_field||''} onChange={e=>update(items.map((x:any,i:number)=>i===index?{...x,item_field:e.target.value}:x))} placeholder="当前元素变量"/><button onClick={()=>update(items.filter((_:any,i:number)=>i!==index))}>×</button></div>)}<button onClick={()=>update([...items,{path:'input.items',item_field:`${prefix}_item_${items.length+1}`}])}>＋ 添加数组</button></fieldset>}
function LoopEditor({value,set}:{value:any;set:(k:string,v:any)=>void}){return <div className="workflow-loop-settings"><label>循环类型<select value={value.loop_type||'count'} onChange={e=>set('loop_type',e.target.value)}><option value="count">固定次数</option><option value="array">数组循环</option></select></label>{value.loop_type==='array'&&<ArrayInputs value={value} set={set} prefix="loop"/>}<label>最大循环次数<input type="number" min={1} max={100} value={value.max_iterations||3} onChange={e=>set('max_iterations',Math.max(1,Math.min(100,Number(e.target.value))))}/></label><fieldset><legend>提前终止条件</legend><ConditionRow value={{field:value.termination_field,operator:value.termination_operator,value:value.termination_value}} change={next=>{set('termination_field',next.field);set('termination_operator',next.operator);set('termination_value',next.value)}} remove={()=>set('termination_field','')}/></fieldset><FieldInput name="索引变量" value={value.index_field||'loop_index'} set={v=>set('index_field',v)}/><FieldInput name="输出变量" value={value.output_field||'loop_output'} set={v=>set('output_field',v)}/></div>}
function BatchEditor({value,set}:{value:any;set:(k:string,v:any)=>void}){return <div className="workflow-loop-settings"><ArrayInputs value={value} set={set} prefix="batch"/><div className="rule-form-grid"><label>最大处理数量<input type="number" min={1} max={100} value={value.max_items||100} onChange={e=>set('max_items',Number(e.target.value))}/></label><label>并发数<input type="number" min={1} max={10} value={value.concurrency||3} onChange={e=>set('concurrency',Math.max(1,Math.min(10,Number(e.target.value))))}/></label></div><FieldInput name="索引变量" value={value.index_field||'batch_index'} set={v=>set('index_field',v)}/><FieldInput name="输出变量" value={value.output_field||'batch_output'} set={v=>set('output_field',v)}/><small>单项失败会记录错误并继续，其余结果按输入顺序聚合。</small></div>}
function TestDrawer({close,input,setInput,run,testing,test,approve,nodes,edges}:{close:()=>void;input:string;setInput:(v:string)=>void;run:Run|null;testing:boolean;test:()=>void;approve:(sequence:number,approved:boolean)=>void;nodes:FlowNode[];edges:Edge[]}){
 const activeNodeRef=useRef<HTMLElement|null>(null),events=(run?.events||[]) as any[],completed=new Set(events.filter(event=>event.type==='node_end').map(event=>String(event.node))),started=events.filter(event=>event.type==='node_start').map(event=>String(event.node)),lastStarted=[...started].reverse().find(node=>!completed.has(node))||'',failedNode=run?.status==='failed'?lastStarted:'',activeNode=testing?nodes.find(node=>[node.id,node.data.label].includes(lastStarted)):undefined;
 useEffect(()=>{if(testing&&activeNodeRef.current)activeNodeRef.current.scrollIntoView({block:'nearest',behavior:'smooth'})},[events.length,testing]);
 const nodeState=(node:FlowNode)=>{const keys=[node.id,node.data.label];if(keys.some(key=>completed.has(key)))return'succeeded';if(keys.includes(failedNode))return'failed';if(testing&&keys.includes(lastStarted))return'running';if(keys.some(key=>started.includes(key)))return run?.status==='failed'?'failed':'pending';return'pending'};
 const duration=(node:FlowNode)=>{const keys=[node.id,node.data.label],start=events.find(event=>event.type==='node_start'&&keys.includes(String(event.node))),end=events.find(event=>event.type==='node_end'&&keys.includes(String(event.node)));if(!start||!end)return'';const value=new Date(end.timestamp).getTime()-new Date(start.timestamp).getTime();return Number.isFinite(value)?`${Math.max(0,value)}ms`:''};
 const topology=workflowNodeOrder(nodes,edges),topologyRank=new Map(topology.map((node,index)=>[node.id,index])),executionRank=new Map<string,number>();events.filter(event=>event.type==='node_start').forEach((event,index)=>{const node=nodes.find(item=>[item.id,item.data.label].includes(String(event.node)));if(node&&!executionRank.has(node.id))executionRank.set(node.id,index)});const displayNodes=[...nodes].sort((a,b)=>{const ar=executionRank.get(a.id),br=executionRank.get(b.id);if(ar!==undefined&&br!==undefined)return ar-br;if(ar!==undefined)return-1;if(br!==undefined)return 1;return(topologyRank.get(a.id)??Number.MAX_SAFE_INTEGER)-(topologyRank.get(b.id)??Number.MAX_SAFE_INTEGER)});
 const rawOutput=(run?.state as any)?.workflow_output??(run?.state as any)?.input,answerText=run?.status==='failed'?run.error:typeof rawOutput==='string'?rawOutput:rawOutput?.content||rawOutput?.output||rawOutput?.answer||(rawOutput?JSON.stringify(rawOutput,null,2):''),answer=answerText?<Markdown content={String(answerText)}/>:null;
 return <div className="test-drawer workflow-chat-test"><header><div><b>测试</b><small>文本对话</small></div><button onClick={close}>×</button></header><div className="workflow-chat-body">{!run&&<div className="workflow-chat-empty"><i>⌘</i><b>输入问题进行测试体验</b><p>系统会按照当前工作流编排依次执行节点。</p></div>}{run&&<><div className="workflow-user-message">{String((run.input as any)?.input||'')}</div><details className={`workflow-execution ${run.status}`} open={run.status==='failed'||testing}><summary><b>{run.status==='succeeded'?'✓ 执行成功':run.status==='failed'?'! 执行失败':'● 正在执行'}</b><span>{activeNode?`正在执行：${activeNode.data.label}`:`${nodes.filter(node=>nodeState(node)==='succeeded').length}/${nodes.length} 个节点`}</span><em>{String((run.metadata as any)?.duration_ms?`${(run.metadata as any).duration_ms}ms`:'')}</em></summary><div className="workflow-test-nodes">{displayNodes.map(node=>{const state=nodeState(node),nodeEvents=events.filter(event=>[node.id,node.data.label].includes(String(event.node)));return <details ref={element=>{if(state==='running')activeNodeRef.current=element}} key={node.id} open={state==='failed'||state==='running'} className={state}><summary><i>{state==='succeeded'?'✓':state==='failed'?'!':state==='running'?'…':'○'}</i><span><b>{node.data.label}</b><small>{kindLabel(node.data.kind)}</small></span><em>{duration(node)||({succeeded:'成功',failed:'失败',running:'运行中',pending:'未执行'} as Record<string,string>)[state]}</em></summary>{nodeEvents.length>0&&<div>{nodeEvents.map((event,index)=><p key={event.sequence||index}>{event.message||eventName(event.type)}</p>)}</div>}{state==='failed'&&run.error&&<code>{run.error}</code>}</details>})}</div></details>{events.filter(event=>event.type==='approval_required').map((event:any)=><div className="test-event" key={event.sequence}><b>工具调用等待审批</b><span>{event.message||event.node||''}</span><div><button onClick={()=>approve(event.sequence,false)}>拒绝</button><button className="primary" onClick={()=>approve(event.sequence,true)}>批准</button></div></div>)}{answer&&!testing&&<div className={`workflow-assistant-message ${run.status}`}>{answer}</div>}</>}</div><div className="workflow-chat-compose"><textarea rows={3} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!testing&&input.trim())test()}}} placeholder="输入问题，Enter 发送，Shift + Enter 换行"/><button className="primary" disabled={testing||!input.trim()} onClick={test}>{testing?'…':'↑'}</button><small>测试仅用于验证当前工作流，结果不会自动发布。</small></div></div>
}

function CheckDrawer({issues,nodes,close,select}:{issues:CheckIssue[];nodes:FlowNode[];close:()=>void;select:(id:string)=>void}){const groups=nodes.map(node=>({node,items:issues.filter(issue=>issue.nodeId===node.id)})).filter(group=>group.items.length),global=issues.filter(issue=>!issue.nodeId);return <div className="workflow-check-drawer"><header><div><b>检查清单 · {issues.length}</b><small>{issues.length?'完成以下配置后即可测试和发布':'当前工作流配置完整'}</small></div><button onClick={close}>×</button></header><div>{!issues.length&&<section className="workflow-check-ok"><i>✓</i><b>检查通过</b><p>没有发现缺失的必填配置。</p></section>}{global.length>0&&<section><header><b>工作流结构</b></header>{global.map((issue,index)=><p key={index}><i>!</i>{issue.message}</p>)}</section>}{groups.map(({node,items})=><section key={node.id} onClick={()=>select(node.id)}><header><span style={{background:colors[node.data.kind]}}>{kindIcon(node.data.kind)}</span><b>{node.data.label}</b><em>{kindLabel(node.data.kind)}</em></header>{items.map((issue,index)=><p key={index}><i>!</i>{issue.message}</p>)}</section>)}</div></div>}

function ObserveDrawer({runs,detail,busy,close,select}:{runs:Run[];detail:Run|null;busy:boolean;close:()=>void;select:(run:Run)=>void}){return <div className="workflow-side-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="workflow-side-drawer"><header><div><b>运行观测</b><small>当前工作流的测试与发布运行</small></div><button onClick={close}>×</button></header>{busy&&!runs.length?<div className="workflow-drawer-empty"><span className="spinner"/>正在加载运行记录…</div>:!runs.length?<div className="workflow-drawer-empty">暂无运行记录，请先测试工作流。</div>:<div className="workflow-observe-body"><div className="workflow-run-list">{runs.map(run=><button className={detail?.id===run.id?'active':''} onClick={()=>select(run)} key={run.id}><span className={`run-state ${run.status}`}/><div><b>{run.status}</b><small>{run.id}</small></div><time>{formatDate(run.created_at)}</time></button>)}</div><section className="workflow-run-detail">{detail?<><div className="workflow-detail-summary"><b>{detail.status}</b><span>耗时：{String((detail.metadata as any)?.duration_ms??'—')} ms</span><span>事件：{detail.events?.length||0}</span></div>{detail.error&&<div className="workflow-run-error">{detail.error}</div>}<div className="workflow-event-list">{(detail.events||[]).map((event:any,index)=><article key={event.sequence||index}><div><b>{eventName(event.type)}</b><time>{event.timestamp?formatDate(event.timestamp):''}</time></div><p>{event.message||event.node||'运行事件'}</p>{(event.model||event.executor)&&<small>{event.model||'未记录模型'} · {event.executor||'未记录执行器'}</small>}{(event.tool_calls||[]).map((call:any,i:number)=><code key={i}>{call.display_name||call.name||'工具'} · {call.status}</code>)}</article>)}</div></>:<div className="workflow-drawer-empty">选择一条运行查看节点、模型和工具事件。</div>}</section></div>}</aside></div>}

function VersionDrawer({current,versions,busy,close,rollback}:{current:Workflow;versions:Workflow[];busy:boolean;close:()=>void;rollback:(version:number)=>void}){return <div className="workflow-side-layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="workflow-side-drawer version-drawer"><header><div><b>版本管理</b><small>每次发布生成新版本；切换版本不会创建额外版本</small></div><button onClick={close}>×</button></header>{busy&&!versions.length?<div className="workflow-drawer-empty"><span className="spinner"/>正在读取版本…</div>:<div className="workflow-version-list">{versions.map(item=><article key={item.version}><span>v{item.version}</span><div><b>{item.version===current.version?'当前版本':'已发布版本'}</b><small>{formatDate(String((item.metadata as any)?.published_at||item.updated_at))} · {item.graph?.agents?.length||0} 个节点</small></div>{item.version!==current.version&&<button disabled={busy} onClick={()=>rollback(item.version)}>选择此版本</button>}</article>)}{!versions.length&&<div className="workflow-drawer-empty">尚未发布版本，点击发布后将生成 v1。</div>}</div>}</aside></div>}

function DeleteNodeDialog({node,cancel,confirm}:{node:FlowNode;cancel:()=>void;confirm:()=>void}){return <div className="workflow-confirm-layer" onMouseDown={event=>event.target===event.currentTarget&&cancel()}><section className="workflow-confirm-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-node-title"><span className="workflow-confirm-icon">!</span><div><h2 id="delete-node-title">删除节点</h2><p>确定删除节点“{node.data.label}”吗？与该节点相连的连线也会同时删除。</p></div><footer><button onClick={cancel}>取消</button><button className="danger" autoFocus onClick={confirm}>确认删除</button></footer></section></div>}

function defaults(kind:string):Record<string,any>{if(kind==='tool')return{node_kind:kind,input_field:'input',output_field:'tool_output',tool_id:''};if(kind==='knowledge')return{node_kind:kind,knowledge_base_id:'',output_field:'documents'};if(kind==='condition')return{node_kind:kind,route_key:'route',branches:[{name:'分支 1',route:'branch_1',groups:[{conditions:[{field:'input',operator:'equals',value:''}]}]}],default_route:'default'};if(kind==='intent')return{node_kind:kind,input_field:'input',model:'',mode:'single',route_key:'route',categories:[{name:'意图1',description:'',route:'intent_1'}],default_route:'default',output_field:'intent_result'};if(kind==='script')return{node_kind:kind,language:'python',inputs:[{name:'input',path:'input'}],code:'def main(params):\n    return {"script_output": params.get("input")}',output_field:'script_output',timeout_seconds:5,retry_count:0,retry_interval_ms:200,error_strategy:'raise',route_key:'route',route:'next'};if(kind==='assign')return{node_kind:kind,assignments:[{target:'result',operation:'set',source:'input'}]};if(kind==='loop')return{node_kind:kind,loop_type:'count',max_iterations:3,input_arrays:[{path:'input.items',item_field:'loop_item'}],index_field:'loop_index',termination_field:'',termination_operator:'equals',termination_value:'',output_field:'loop_output',route_key:'route',continue_route:'continue',done_route:'done'};if(['loop_start','loop_end','batch_start','batch_end'].includes(kind))return{node_kind:kind,output_field:'input'};if(kind==='batch')return{node_kind:kind,input_arrays:[{path:'input.items',item_field:'batch_item'}],index_field:'batch_index',max_items:100,concurrency:3,failure_strategy:'continue',output_field:'batch_output',route_key:'route',done_route:'done'};return{node_kind:kind,output_field:'input',tool_ids:[],skill_ids:[],knowledge_base_ids:[],memory_bank_ids:[]}}
function fromWorkflow(wf:Workflow):Snapshot{
 const positions=(wf.metadata as any)?.editor?.positions||{},parents=(wf.metadata as any)?.editor?.parents||{},sizes=(wf.metadata as any)?.editor?.sizes||{};
 const nodes:FlowNode[]=(wf.graph.agents||[]).map((a:any,i)=>{const kind=a.config?.node_kind||'agent',parentId=a.parent_id||parents[a.id],size=sizes[a.id],config=migrateConfig(kind,a.config||{});return{id:a.id,type:'workflow',position:positions[a.id]||{x:100+i*280,y:220},...(parentId?{parentId,extent:'parent' as const,expandParent:true}:{}),...(['loop','batch'].includes(kind)?{style:{width:Number(size?.width||config.container_width||560),height:Number(size?.height||config.container_height||290)}}:{}),data:{label:a.name,kind,description:a.description||'',config,model:['device','edge','cloud'].includes(a.model)?'auto':a.model||'',sys_prompt:a.sys_prompt||''}}});
 const edges:Edge[]=[];
 (wf.graph.connections||[]).forEach((c:any)=>{if(c.conditional)Object.entries(c.path_map||{}).forEach(([route,target])=>edges.push({id:`${c.source}-${route}-${target}`,source:c.source,target:String(target),type:'smoothstep',label:route,data:{route}}));else if(c.target!=='END')edges.push({id:`${c.source}-${c.target}`,source:c.source,target:c.target,type:'smoothstep'})});
 const originalCount=nodes.length,hasStart=nodes.some(node=>node.data.kind==='start'),hasEnd=nodes.some(node=>node.data.kind==='end');
 if(hasStart&&hasEnd)return{nodes,edges};
 const usedNames=new Set(nodes.map(node=>node.data.label));
 const unique=(base:string)=>{let name=base,index=2;while(usedNames.has(name))name=`${base}${index++}`;usedNames.add(name);return name};
 const xs=nodes.map(node=>node.position.x),minX=xs.length?Math.min(...xs):380,maxX=xs.length?Math.max(...xs):100;
 let startId=nodes.find(node=>node.data.kind==='start')?.id||'';
 if(!hasStart){startId=`node-${crypto.randomUUID()}`;nodes.push({id:startId,type:'workflow',position:{x:Math.max(40,minX-280),y:220},data:{label:unique('开始'),kind:'start',description:'接收工作流输入',config:{node_kind:'start',input_fields:['input']}}})}
 let endId=nodes.find(node=>node.data.kind==='end')?.id||'';
 if(!hasEnd){endId=`node-${crypto.randomUUID()}`;nodes.push({id:endId,type:'workflow',position:{x:maxX+280,y:220},data:{label:unique('结束'),kind:'end',description:'返回工作流最终输出',config:{node_kind:'end',output_field:'input'}}})}
 if(originalCount===0&&!edges.length)edges.push({id:`${startId}-${endId}`,source:startId,target:endId,type:'smoothstep'});
 return{nodes,edges,repaired:true}
}
function toWorkflow(nodes:FlowNode[],edges:Edge[]){const agents=nodes.map(n=>({id:n.id,name:n.data.label,description:n.data.description,model:n.data.model||'',sys_prompt:n.data.sys_prompt||'',parent_id:n.parentId||null,children:nodes.filter(child=>child.parentId===n.id).map(child=>child.id),config:{...n.data.config,node_kind:n.data.kind,parent_id:n.parentId||null}}));const connections:any[]=[];const logic=new Set(nodes.filter(n=>['condition','intent','loop','batch'].includes(n.data.kind)).map(n=>n.id));edges.filter(e=>!logic.has(e.source)).forEach(e=>connections.push({source:e.source,target:e.target,conditional:false}));logic.forEach(source=>{const node=nodes.find(n=>n.id===source)!;const outgoing=edges.filter(e=>e.source===source);connections.push({source,target:'<conditional>',conditional:true,condition_key:node.data.config.route_key||'route',path_map:Object.fromEntries(outgoing.map(e=>[String(e.data?.route||e.label||'default'),e.target]))})});return{entry:nodes.find(n=>n.data.kind==='start')?.id||null,agents,connections}}
function inspectWorkflow(nodes:FlowNode[],edges:Edge[],models:ModelConnection[],app:Application|null):CheckIssue[]{
 const issues:CheckIssue[]=[],add=(message:string,node?:FlowNode)=>issues.push({nodeId:node?.id||'',nodeLabel:node?.data.label||'',message}),starts=nodes.filter(node=>node.data.kind==='start'),ends=nodes.filter(node=>node.data.kind==='end');
 if(starts.length!==1)add('必须且只能包含一个开始节点');if(ends.length!==1)add('必须且只能包含一个结束节点');
 const names=new Map<string,number>();nodes.forEach(node=>{const name=node.data.label.trim();names.set(name,(names.get(name)||0)+1);if(!name)add('节点名称不能为空',node)});nodes.filter(node=>node.data.label.trim()&&(names.get(node.data.label.trim())||0)>1).forEach(node=>add('节点名称不能重复',node));
 nodes.filter(node=>!['end','loop','batch'].includes(node.data.kind)&&!edges.some(edge=>edge.source===node.id)).forEach(node=>add('尚未连接下一个节点',node));nodes.filter(node=>node.data.kind!=='start'&&!edges.some(edge=>edge.target===node.id)).forEach(node=>add('尚未连接上一个节点',node));
 nodes.filter(node=>node.data.kind==='tool'&&!node.data.config.tool_id).forEach(node=>add('尚未选择工具',node));nodes.filter(node=>node.data.kind==='knowledge'&&!node.data.config.knowledge_base_id).forEach(node=>add('尚未选择知识库',node));
 const ready=modelAutoReady(models),usable=(id:string)=>models.some(model=>model.id===id&&model.enabled&&model.configured&&model.test_status==='succeeded');if(app?.model==='auto'&&!ready)add('工作流默认 AUTO 尚未就绪，请为端、边、云分别配置可用模型');if(app?.model&&app.model!=='auto'&&!usable(app.model))add('工作流默认模型连接不可用，请重新测试或更换模型');
 nodes.filter(node=>['llm','agent'].includes(node.data.kind)).forEach(node=>{const model=node.data.model||app?.model||'';if(!model)add('尚未选择模型',node);else if(model==='auto'&&!ready)add('AUTO 模型尚未就绪',node);else if(model!=='auto'&&!usable(model))add('模型连接不可用，请重新测试或更换模型',node)});
 nodes.filter(node=>node.data.kind==='intent').forEach(node=>{if(!node.data.config.model)add('尚未选择分类模型',node);else if(!usable(node.data.config.model))add('分类模型连接不可用',node);if(!(node.data.config.categories||[]).length)add('至少需要一个意图',node)});
 nodes.filter(node=>node.data.kind==='script').forEach(node=>{if(!node.data.config.code)add('脚本代码不能为空',node);if(!node.data.config.output_field)add('输出字段不能为空',node)});
 nodes.filter(node=>['condition','intent','loop','batch'].includes(node.data.kind)&&!edges.some(edge=>edge.source===node.id)).forEach(node=>add('尚未配置分支连线',node));
 nodes.filter(node=>['loop','batch'].includes(node.data.kind)).forEach(node=>{const children=nodes.filter(child=>child.parentId===node.id);if(children.some(child=>['loop','batch'].includes(child.data.kind)))add('子流程内不能嵌套循环或批处理',node);if(node.data.kind==='batch'&&(!(node.data.config.input_arrays||[]).length||(node.data.config.input_arrays||[]).some((item:any)=>!item.path||!item.item_field)))add('输入数组配置不完整',node)});
 if(starts.length===1){const reached=new Set<string>(),pending=[starts[0].id];while(pending.length){const id=pending.pop()!;if(reached.has(id))continue;reached.add(id);edges.filter(edge=>edge.source===id).forEach(edge=>pending.push(edge.target))}nodes.filter(node=>!reached.has(node.id)).forEach(node=>{if(!issues.some(issue=>issue.nodeId===node.id&&issue.message==='尚未连接上一个节点'))add('无法从开始节点到达',node)})}return issues
}
function nodeRoutes(node?:FlowNode){if(!node)return[];const c=node.data.config;if(node.data.kind==='condition')return[...(c.branches||[]).map((x:any)=>x.route),c.default_route||'default'];if(node.data.kind==='intent')return[...(c.categories||[]).map((x:any)=>x.route),c.default_route||'default'];if(['loop','batch'].includes(node.data.kind))return[c.continue_route||'continue',c.done_route||'done'];return[]}
function workflowNodeOrder(nodes:FlowNode[],edges:Edge[]){const byId=new Map(nodes.map(node=>[node.id,node])),ordered:FlowNode[]=[],visited=new Set<string>(),queue=nodes.filter(node=>node.data.kind==='start').map(node=>node.id);while(queue.length){const id=queue.shift()!;if(visited.has(id))continue;visited.add(id);const node=byId.get(id);if(node)ordered.push(node);edges.filter(edge=>edge.source===id).forEach(edge=>{if(!visited.has(edge.target))queue.push(edge.target)})}nodes.filter(node=>!visited.has(node.id)).sort((a,b)=>a.position.x-b.position.x||a.position.y-b.position.y).forEach(node=>ordered.push(node));return ordered}
function resizeLoopContainer(nodes:FlowNode[],parentId:string){const children=nodes.filter(node=>node.parentId===parentId);if(!children.length)return nodes;const width=Math.max(360,...children.map(node=>node.position.x+Math.max(Number(node.measured?.width||0),Number((node.style as any)?.width||0),238)+24)),height=Math.max(180,...children.map(node=>node.position.y+Math.max(Number(node.measured?.height||0),Number((node.style as any)?.height||0),78)+24));return nodes.map(node=>node.id===parentId?{...node,style:{...node.style,width,height},data:{...node.data,config:{...node.data.config,container_width:width,container_height:height}}}:node)}
function kindLabel(kind:string){return({start:'开始',end:'结束',loop_start:'循环开始',loop_end:'迭代结束',batch_start:'批处理开始',batch_end:'批处理结束',llm:'大模型',knowledge:'知识库',tool:'工具',agent:'智能体',condition:'条件判断',intent:'意图分类',script:'脚本',assign:'变量赋值',loop:'循环',batch:'批处理'} as Record<string,string>)[kind]||kind}
function kindIcon(kind:string){return({start:'▶',end:'■',loop_start:'▶',loop_end:'■',batch_start:'▶',batch_end:'■',llm:'✦',knowledge:'▤',tool:'⌁',agent:'AI',condition:'◇',intent:'◎',script:'</>',assign:'↦',loop:'↻',batch:'▦'} as Record<string,string>)[kind]||'◇'}
function kindHint(kind:string){return({loop_start:'进入本轮迭代',loop_end:'返回循环条件判断',batch_start:'进入当前批次',batch_end:'结束当前批次',llm:'调用模型生成内容',knowledge:'检索已绑定知识',tool:'调用内置或 MCP 工具',agent:'自主规划和执行任务',condition:'按条件组选择路径',intent:'使用模型进行语义分类',script:'使用代码转换数据',assign:'更新工作流或循环变量',loop:'顺序重复执行子流程',batch:'并行处理输入数组'} as Record<string,string>)[kind]||''}
function migrateConfig(kind:string,c:any){if(kind==='condition'&&!c.branches)return{...defaults(kind),...c,branches:[{name:'条件满足',route:c.true_route||'true',groups:[{conditions:[{field:c.field||'input',operator:c.operator||'contains',value:c.value}]}]}],default_route:c.false_route||'false'};if(kind==='intent'&&!c.categories)return{...defaults(kind),...c,categories:(c.intents||[]).map((x:any)=>({name:x.route||'意图',description:(x.keywords||[]).join('、'),route:x.route||'matched'}))};if(kind==='script'&&!c.code){const template=JSON.stringify(c.template||'{{input}}'),output=JSON.stringify(c.output_field||'script_output');return{...defaults(kind),...c,code:`def main(params):\n    value = ${template}.replace("{{input}}", str(params.get("input", "")))\n    return {${output}: value}`,legacy_template:c.template}}if(kind==='loop'&&!c.input_arrays)return{...defaults(kind),...c,input_arrays:[{path:c.items_path||'input.items',item_field:c.item_field||'loop_item'}]};if(kind==='batch'&&!c.input_arrays)return{...defaults(kind),...c,input_arrays:[{path:c.items_path||'input.items',item_field:c.item_field||'batch_item'}]};return{...defaults(kind),...c}}
function tierLabel(tier:ModelConnection['tier']){return tier==='device'?'端':tier==='edge'?'边':'云'}
function eventName(type:string){return({plan_created:'执行计划',node_start:'节点开始',node_end:'节点完成',knowledge_retrieval_start:'正在查询知识库',knowledge_retrieval_end:'知识库检索完成',tool_result:'工具结果',approval_required:'等待审批',final:'执行完成'} as Record<string,string>)[type]||type}
const defaultWorkflowMemory:MemoryConfig={short_term_enabled:true,context_rounds:8,context_token_budget:0,rolling_summary_enabled:true,long_term_enabled:false,memory_top_k:5,wakeup_level:'standard',auto_write:true,deduplicate:true,sensitive_filter:true,retrieval_override_enabled:false};
function normalizeWorkflowApp(app:Application):Application{return{...app,model:['','device','edge','cloud'].includes(app.model)?'auto':app.model,memory_bank_ids:app.memory_bank_ids||[],primary_memory_bank_id:app.primary_memory_bank_id||null,memory_config:{...defaultWorkflowMemory,...(app.memory_config||{})}}}
function memoryPayload(app:Application){return{model:app.model||'auto',memory_bank_ids:app.memory_bank_ids,primary_memory_bank_id:app.primary_memory_bank_id,memory_config:app.memory_config}}
function modelAutoReady(models:ModelConnection[]){return(['device','edge','cloud'] as const).every(tier=>models.some(model=>model.tier===tier&&model.auto_default&&model.enabled&&model.configured&&model.test_status==='succeeded'))}
function modelGroups(models:ModelConnection[]){return(['device','edge','cloud'] as const).map(tier=><optgroup key={tier} label={`${tierLabel(tier)}模型`}>{models.filter(model=>model.tier===tier).map(model=><option key={model.id} value={model.id} disabled={!model.enabled||!model.configured||model.test_status!=='succeeded'}>{model.name} · {model.model_id}{model.test_status!=='succeeded'?'（需测试）':!model.configured?'（密钥未配置）':!model.enabled?'（已禁用）':''}</option>)}</optgroup>)}
function serializeEditor(nodes:FlowNode[],edges:Edge[],app:Application|null){return JSON.stringify({nodes:nodes.map(n=>({id:n.id,position:n.position,parentId:n.parentId||'',size:['loop','batch'].includes(n.data.kind)?{width:Number((n.style as any)?.width||n.measured?.width||360),height:Number((n.style as any)?.height||n.measured?.height||180)}:undefined,data:n.data})),edges:edges.map(e=>({source:e.source,target:e.target,route:e.data?.route||''})),memory:app?memoryPayload(app):null})}
function formatDate(value:string){if(!value)return'';const date=new Date(value);return Number.isNaN(date.getTime())?value:date.toLocaleString('zh-CN',{hour12:false})}
